### ISSUE TITLE
题解中的markdown代码块运行异常

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#1]
一道题解：http://xmoj.tech/problem_solution.php?cid=6248&pid=3
我没有启用的时候代码块可以显示，但是现在无法加载代码周围的灰框
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/f1c8b2af-b7df-4399-a1c0-cbec69647c7c)
（缺少代码周围的灰框）
原本：
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/a8a4931b-3fc2-4f9a-a3cb-866fa3d8d593)

**Comment by langningchen** [comment]
Working on it

**Comment by langningchen** [comment]
Will fix in 0.1.32, please wait

**Comment by langningchen** [comment]
Solved, wait for release!
