### ISSUE TITLE
Github有bug?

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#106]
我为什么不能edit任何branch了...

**Comment by boomzero** [comment]
全部显示为protected branch....

**Comment by boomzero** [comment]
dev, 我自己创建的branch都这样

**Comment by boomzero** [comment]
@langningchen 你的branch protection...
![err](https://github.com/langningchen/XMOJ-Script/assets/85378277/2eaf0b78-e3a8-4086-89c4-f5b0ae722d32)

**Comment by langningchen** [comment]
我上午没空，下午解决

**Comment by langningchen** [comment]
@boomzero 不好意思，昨天随便改改，应该是改错了

**Comment by boomzero** [comment]
@langningchen 看xmoj私信

**Comment by boomzero** [comment]
突然发现一个东西:
![](https://github.com/langningchen/XMOJ-Script/assets/85378277/f5165f96-e4a1-407d-8a62-3a055e0fea40)

**Comment by boomzero** [comment]
我生成的release notes

**Comment by boomzero** [comment]
~欢迎new contributor!~

**Comment by langningchen** [comment]
@boomzero 你再试试

**Comment by langningchen** [comment]
应该是选择 Dev 和 Master，我当时选错了，选了 All branches ，因为当时只有那两个 Branch

**Comment by langningchen** [comment]
> 我生成的release notes
> 
> v0.2.60

怎么弄的？

**Comment by boomzero** [comment]
> > 我生成的release notes
> > v0.2.60
> 
> 怎么弄的？

有一个button

**Comment by langningchen** [comment]
手动弄得？
