### ISSUE TITLE
[Bug] 提醒查看链接404

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#108]

**Comment by langningchen** [comment]
知道，正准备修

**Comment by langningchen** [comment]
刚才在做 https://github.com/langningchen/OJ

**Comment by langningchen** [comment]
#108 加载不出来，不知道为什么，等到一会儿加载出来再干

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/607ade5d-1cc8-4ff8-8b05-69460592e8e6)

看左侧中间

**Comment by boomzero** [comment]
> 刚才在做 https://github.com/langningchen/OJ

What does that do?

**Comment by langningchen** [comment]
自己做的OJ

**Comment by langningchen** [comment]
为什么我的VSCode里面还没有这个Issue……

**Comment by boomzero** [comment]
> 自己做的OJ

%%%

**Comment by langningchen** [comment]
@boomzero 你不要忘了分配给你的两个任务

**Comment by langningchen** [comment]
一个是关于使用公开头像的，一个是关于增加加密机制的

**Comment by langningchen** [comment]
如果你有空的话，你帮我把图片也换一下，然后assign你那边把我的就去掉了

**Comment by langningchen** [comment]
#75 #76 #93

**Comment by langningchen** [comment]
我今天下午把branch protect给调好了，你那应该没有问题了，你可以正常的提交代码了

**Comment by langningchen** [comment]
这个Issue等我VScode上面出来了我再修吧

**Comment by langningchen** [comment]
这个问题应该挺好弄，就一行代码写错的事

**Comment by boomzero** [comment]
> 这个问题应该挺好弄，就一行代码写错的事

所以`good first issue` 啊

**Comment by langningchen** [comment]
已经有的提醒没法改
