### ISSUE TITLE
userinfo上方的用户名和昵称消失

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#11]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/ba9cc4a8-0742-40f5-b189-6e4918562f60)
userinfo上方的用户名和昵称消失

**Comment by PythonSmall-Q** [comment]
mentions:langningchen

**Comment by langningchen** [comment]
https://github.com/langningchen/XMOJ-Script/blob/fbd74cc77064c8aea0c540cf5311e4926c0ec9a9/XMOJ.user.js#L1629

**Comment by langningchen** [comment]
Fixed in the new release
