### ISSUE TITLE
[Question] Rating颜色机制

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#122]
询问一下rating的颜色是怎样判定的？

**Comment by boomzero** [comment]
Rating=AC 率*10

**Comment by boomzero** [comment]
Rating>=500 -> red
400<=Rating<500 ->yellow
300<=Rating<400 ->green
Rating<300 ->blue

**Comment by boomzero** [comment]
> Rating>=500 -> red 400<=Rating<500 ->yellow 300<=Rating<400 ->green Rating<300 ->blue

看源代码

**Comment by boomzero** [comment]
~如果你想要绿名可以交`while(1)`把AC率刷下去~

**Comment by boomzero** [comment]
I think this issue can be closed now
