### ISSUE TITLE
[Feature request] Make admins have special badges

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#127]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

Make admins purple named in the discussion panel

### 原因

~I want to be purple~

**Comment by boomzero** [comment]
>     * [x]  我已知晓XMOJ Script的开发组之强大，有求必应qaq

?

**Comment by PythonSmall-Q** [comment]
emm我的论坛做了紫名了

**Comment by PythonSmall-Q** [comment]
> > * [x]   我已知晓XMOJ Script的开发组之强大，有求必应qaq
> 
> ?

是我写的。挺好玩的

**Comment by langningchen** [comment]
@boomzero 你挑一个颜色，告诉我具体的RGB

**Comment by langningchen** [comment]
要么加一个badge吧，就不改颜色了

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/cb985d24-8102-499c-8e70-b0aca192ace9)

毕竟我想要符合Bootstrap规范

**Comment by boomzero** [comment]
> @boomzero 你挑一个颜色，告诉我具体的RGB

#800080

**Comment by boomzero** [comment]
`style:"color:` 啊

**Comment by langningchen** [comment]
如果可以加Badge就用Badge

**Comment by langningchen** [comment]
> `style:"color:` 啊

这样就不符合规范了

**Comment by langningchen** [comment]
按理来说只能用内置的颜色

**Comment by boomzero** [comment]
> 如果可以加Badge就用Badge

可以吧

**Comment by langningchen** [comment]
那就好

**Comment by boomzero** [comment]
> 按理来说只能用内置的颜色

所以我不喜欢bootstrap

**Comment by langningchen** [comment]
> > 按理来说只能用内置的颜色
> 
> 所以我不喜欢bootstrap

。。。

**Comment by langningchen** [comment]
等等，还是不符合规范吧

**Comment by boomzero** [comment]
~也可以让付费用户有Badge, 和`exlg`一样~
