### ISSUE TITLE
[Bug] 目前默认开启Debug mode

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#144]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Debug mode默认开启

### 重现步骤

Not applicable

### 控制台错误信息

Not applicable

**Comment by langningchen** [comment]
这不是一个好主意

**Comment by langningchen** [comment]
我可能程序出了一点问题

**Comment by langningchen** [comment]
应该好了吧？ @boomzero
