### ISSUE TITLE
[Bug] README.md 显示失败

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#145]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Github Actions 标签显示失败

### 重现步骤

打开Github

### 控制台错误信息

没有错诶

**Comment by boomzero** [comment]
> ### 检查项
> 
>     * [x]  我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug。
> 
>     * [x]  我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。
> 
> 
> ### 描述
> 
> Github Actions 标签显示失败
> ### 重现步骤
> 
> 打开Github
> ### 控制台错误信息
> 
> 没有错诶

?
