### ISSUE TITLE
[Feature request] 更新Issue模板

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#146]
### 描述

- [x] #147
- [x] #148
- [x] #149
- [x] #150
- [x] #151
- [x] #152

### 原因

每次输入太麻烦

**Comment by boomzero** [comment]
>     * [ ]  自动assign @langningchen

...
要用github actions

**Comment by boomzero** [comment]
>     * [ ]  [更新bug描述的语句不通顺 #149](https://github.com/langningchen/XMOJ-Script/issues/149)

?

**Comment by langningchen** [comment]
> >     * [ ]  自动assign @langningchen
> 
> ...
> 要用github actions

好吧，那就不用了

**Comment by langningchen** [comment]
> >  * [ ]  [更新bug描述的语句不通顺 #149](https://github.com/langningchen/XMOJ-Script/issues/149)
> 
> ?
> 

![Screenshot_20230828_064959_GitHub.jpg](https://github.com/langningchen/XMOJ-Script/assets/81672884/18e57990-eb40-4c5f-a57c-b63a795fd5e7)

**Comment by boomzero** [comment]
> > > * [ ]   [更新bug描述的语句不通顺 #149](https://github.com/langningchen/XMOJ-Script/issues/149)
> > 
> > 
> > ?
> 
> ![Screenshot_20230828_064959_GitHub.jpg](https://user-images.githubusercontent.com/81672884/263558008-18e57990-eb40-4c5f-a57c-b63a795fd5e7.jpg)

?

**Comment by boomzero** [comment]
通顺啊

**Comment by langningchen** [comment]
这句话语句有点奇怪，你改一句话

**Comment by boomzero** [comment]
> > > ```
> > > * [ ]  自动assign @langningchen
> > > ```
> > 
> > 
> > ...
> > 要用github actions
> 
> 好吧，那就不用了

#151 也要啊, 所以可以做

**Comment by boomzero** [comment]
@langningchen 你在pull request里update version会自动导致merge conflict....

**Comment by langningchen** [comment]
确实会导致merch conflict，但是我还没有想到怎么解决

**Comment by boomzero** [comment]
done!

**Comment by langningchen** [comment]
thx!
