### ISSUE TITLE
[ENHANCEMENT] 增加黑白选择

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#15]
**Is your feature request related to a problem? Please describe. **
NO

**Describe the solution you'd like**
Dear author, i pleed you to add a feature allowing me to choose dark or light mode

**Describe alternatives you've considered**
add a button in the config page choosing dark mode, auto disabled

**Additional context**
Add any other context or screenshots about the feature request here. Type `None` if there is no additional context.

**Comment by langningchen** [comment]
Fixed in 0.1.35, please wait for release. Thanks.
