### ISSUE TITLE
[Bug] test

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#165]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

test

**Comment by boomzero** [comment]
success!

**Comment by langningchen** [comment]
Good!
