### ISSUE TITLE
[Feature Request] 修复XMOJ导出AC代码的问题

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#173]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

每行结尾有多余的 `^M`

### 原因

https://github.com/langningchen/XMOJ/pull/1

**Comment by langningchen** [comment]
@boomzero 修好了

**Comment by boomzero** [comment]
THX
