### ISSUE TITLE
[BUG] 主页新闻框消失

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#19]
**Describe the bug**
新闻框消失
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/9b5b52e7-d2f6-423f-a842-4202f2941e67)

**Expected behavior**

**Environment**
 - Browser Version: `e.g. Microsoft Edge Version 123.4.5678.9 (Official build) canary (64-bit)`
 - Script Version: `e.g. 0.1.88`

**Screenshots**

**Error Information**
Open DevTools (`F12`) and switch to `Console` zone. Copy the recent error here. (Note: your page may reload after closing the DevTools.) Type `None` if there is no error information.

**Additional context**
Add any other context about the problem here. Type `None` if there is no additional context.

**Comment by langningchen** [comment]
Ack

**Comment by langningchen** [comment]
It's tricky. Time make be long before we fix it.

**Comment by langningchen** [comment]
Finally fixed this in 0.1.35, wait for the new release!
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/a5d3f1a5-05d1-4f53-bf54-3fe6cbacaadb)
