### ISSUE TITLE
[Feature Request] 发帖前提供预览

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#191]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

发帖前提供预览

### 原因

经常发错

~为什么这个还是必填~

**Comment by langningchen** [comment]
就是使用markdown编辑器吗？

**Comment by boomzero** [comment]
> 就是使用markdown编辑器吗？

yes

**Comment by langningchen** [comment]
好的

**Comment by langningchen** [comment]
这个有点难

**Comment by langningchen** [comment]
不太愿干

**Comment by langningchen** [comment]
要么你来吧

**Comment by langningchen** [comment]
常用的几个编辑器我都试了，不能适配我们这种用户脚本加载的情况

**Comment by langningchen** [comment]
@boomzero 你能找到合适的Markdown编辑器吗？

**Comment by boomzero** [comment]
markdown-palettes ?

**Comment by boomzero** [comment]
@langningchen 他只要load js 和 css 然后 
```js
var editor = new MarkdownPalettes('#editor');
```

**Comment by langningchen** [comment]
> markdown-palettes ?

这个洛谷的我真没考虑

**Comment by langningchen** [comment]
@boomzero 我试试

**Comment by langningchen** [comment]
但是中国访问速度最快的 BootCDN 没有这个项目

**Comment by boomzero** [comment]
> 但是中国访问速度最快的 BootCDN 没有这个项目

ghproxy...

**Comment by boomzero** [comment]
我记得阿里云有npm镜像

**Comment by langningchen** [comment]
帮我找找 @boomzero

**Comment by boomzero** [comment]
自己放在github上, 然后ghproxy不就行了

**Comment by langningchen** [comment]
好吧 @PythonSmall-Q 帮我弄 放在你的 https://github.com/PythonSmall-Q/CDN 上面

**Comment by PythonSmall-Q** [comment]
加速地址：githubdown1.eu.org/https://github.com/*****

**Comment by PythonSmall-Q** [comment]
emm你直接调用luogu-dev的repo我这边ssh出了问题手动传太累了 @langningchen 直接就是githubdown1.eu.org/https://github.com/luogu-dev/{reponame}/{filename}

**Comment by PythonSmall-Q** [comment]
加速全部走cloudflare。支持git

**Comment by langningchen** [comment]
好的

**Comment by langningchen** [comment]
有空的时候看看

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q 这个没有给JS，下载的时候给的是Zip，所以没法直接调用luogu-dev的Repo

**Comment by boomzero** [comment]
> @boomzero @PythonSmall-Q 这个没有给JS，下载的时候给的是Zip，所以没法直接调用luogu-dev的Repo

不能self host吗

**Comment by boomzero** [comment]
zip里有js文件的啊

**Comment by boomzero** [comment]
自动翻译好评

**Comment by langningchen** [comment]
所以有必要翻译吗……

**Comment by boomzero** [comment]
~有, 显得高级~

**Comment by langningchen** [comment]
好吧

**Comment by langningchen** [comment]
> > @boomzero @PythonSmall-Q 这个没有给JS，下载的时候给的是Zip，所以没法直接调用luogu-dev的Repo
> 
> 不能self host吗

https://github.com/langningchen/XMOJ-Script/issues/191#issuecomment-1703815452

**Comment by boomzero** [comment]
...我来传

**Comment by boomzero** [comment]
https://github.com/boomzero/cdn/blob/master/markdown-palettes.min.js

**Comment by boomzero** [comment]
@langningchen

**Comment by boomzero** [comment]
...

**Comment by boomzero** [comment]
@boomzero

**Comment by langningchen** [comment]
这个翻译真只能

**Comment by langningchen** [comment]
@boomzero 如果我不使用编辑器，而是加一个右侧预览行吗？

**Comment by boomzero** [comment]
可以
