### ISSUE TITLE
[Feature Request] 允许付费用户添加Label

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#199]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

允许用户支付5RMB来增加Label

### 原因

~我没零花钱了~

**Comment by PythonSmall-Q** [comment]
我有label吗（？

**Comment by PythonSmall-Q** [comment]
我算付费吗？这样吧，那个autolog我算了。就当赞助吧（……

**Comment by PythonSmall-Q** [comment]
@langningchen 图片upload的bug修了

**Comment by langningchen** [comment]
@PythonSmall-Q 到时候给你算付费

**Comment by langningchen** [comment]
我可以给你加上管理员 label

**Comment by langningchen** [comment]
@PythonSmall-Q 需要吗？

**Comment by langningchen** [comment]
告诉你：直接修改文件 XMOJ.user.js ，将第11行加上你自己的名字就好了

https://github.com/langningchen/XMOJ-Script/blob/b2c420cd80bdf58943badd71099cd9b599887e8b/XMOJ.user.js#L32

**Comment by PythonSmall-Q** [comment]
好的呀

**Comment by langningchen** [comment]
你试试

**Comment by PythonSmall-Q** [comment]
好嘞我来试试

**Comment by PythonSmall-Q** [comment]
艹真行

**Comment by langningchen** [comment]
但是这只是有Label，没有实际权限

**Comment by langningchen** [comment]
你虽然能看到删除别人回复的按钮，但是按了以后会报错

**Comment by langningchen** [comment]
如果你想要有实际权限，改这里：

https://github.com/langningchen/XMOJ-Script/blob/b2c420cd80bdf58943badd71099cd9b599887e8b/Server/Source/Process.ts#L6

**Comment by langningchen** [comment]
改好了以后你可以提出PR，我帮你通过

**Comment by langningchen** [comment]
@PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
我改dev还是master？

**Comment by langningchen** [comment]
dev，如果你交到master上面会被自动关闭

**Comment by PythonSmall-Q** [comment]
okay

**Comment by langningchen** [comment]
你好像要创建第200号PR

**Comment by PythonSmall-Q** [comment]
我人麻了还在加载

**Comment by PythonSmall-Q** [comment]
之前早上都上不去。还是靠重启路由器

**Comment by PythonSmall-Q** [comment]
@langningchen 艹你看看哪里炸了

**Comment by langningchen** [comment]
@PythonSmall-Q Cloudflare pages

**Comment by boomzero** [comment]
可以加一下自定义label

**Comment by langningchen** [comment]
> 可以加一下自定义label

就是添加自定义Label

**Comment by PythonSmall-Q** [comment]
是不是就像我在xmojbbs上的“代码使用他”这种喇叭了

**Comment by langningchen** [comment]
对的

**Comment by boomzero** [comment]
需要找一个平台让用户打钱

**Comment by boomzero** [comment]
(https://opencollective.com/) ?

**Comment by langningchen** [comment]
> (https://opencollective.com/) ?

我看看 @boomzero

**Comment by langningchen** [comment]
这个中国应该能访问吧？

**Comment by langningchen** [comment]
还有就是支持什么微信支付宝支付吗？

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/7b437a56-6d8e-40fa-8ae5-9cc146399c92)
我看了，这只支持 Paypal 和银行卡，但是我相信除了我大部分学生都没有 Paypal 账户

**Comment by langningchen** [comment]
我发现我有爱发电的账号 https://afdian.net/a/langningc2009 @boomzero

**Comment by boomzero** [comment]
> ![image](https://user-images.githubusercontent.com/81672884/264188558-7b437a56-6d8e-40fa-8ae5-9cc146399c92.png)
> 我看了，这只支持 Paypal 和银行卡，但是我相信除了我大部分学生都没有 Paypal 账户

那是他配置的问题吧

**Comment by boomzero** [comment]
这个不扣钱

**Comment by boomzero** [comment]
不像爱发电扣除%6

**Comment by langningchen** [comment]
> 那是他配置的问题吧

谁的配置？我可以开启使用支付宝吗？

**Comment by PythonSmall-Q** [comment]
@langningchen 给我一下你的opencollective 注册邮箱

**Comment by langningchen** [comment]
> @langningchen 给我一下你的opencollective 注册邮箱

我还没有注册

**Comment by PythonSmall-Q** [comment]
6

**Comment by PythonSmall-Q** [comment]
我邀请你了。jpxx哪个邮箱

**Comment by PythonSmall-Q** [comment]
那个

**Comment by langningchen** [comment]
好的

**Comment by langningchen** [comment]
我才发现我的Outlook一直没开……

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/4c3f04a1-3f6b-49a6-8f45-20be4d6cc48e)

额

**Comment by PythonSmall-Q** [comment]
这个嘛？

**Comment by langningchen** [comment]
不是

**Comment by langningchen** [comment]
我就是表明一下我又有3837封邮件没有读了

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/6b8a7305-bed4-4966-8cdd-99351384f1bb)

**Comment by langningchen** [comment]
I've accepted

**Comment by langningchen** [comment]
@PythonSmall-Q 

> ERROR
> Only an admin of the host collective can edit the host fee for this collective

Why do you choose USD?

**Comment by PythonSmall-Q** [comment]
我在选择财务托管

**Comment by langningchen** [comment]
你先弄，弄好了告诉我，我先写 Badge

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/d2cba176-557a-4b68-bce6-1f8033c634f2)
给你权限了

**Comment by langningchen** [comment]
就是branch `langningchen/badge-and-code-sharing`，我的这个添加Label的**前端**已经写好了，有谁有空帮我写一下**后端**？ @boomzero @PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
赞助搞好了。需要你们写接口。用的是“易支付”

**Comment by PythonSmall-Q** [comment]
接口文档和密钥需要的话我xmoj里面私信发了

**Comment by PythonSmall-Q** [comment]
3%的费率还是比较低的

**Comment by langningchen** [comment]
好了， @boomzero @PythonSmall-Q 你们可以试一试Label功能

**Comment by langningchen** [comment]
我给你们开放了权限

**Comment by boomzero** [comment]
@langningchen `未找到标签`是什么啊

**Comment by PythonSmall-Q** [comment]
label在哪里（？
@langningchen

**Comment by boomzero** [comment]
> label在哪里（？ @langningchen

修改账户

**Comment by PythonSmall-Q** [comment]
ok

**Comment by PythonSmall-Q** [comment]
然后点啥？

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/77a5b460-57c9-4344-be87-df8e8543c0e0)

**Comment by langningchen** [comment]
@PythonSmall-Q 你没有更新版本吧

**Comment by langningchen** [comment]
> @langningchen `未找到标签`是什么啊

@boomzero 啊，我记得给你加了权限啊，我再检查一下

**Comment by langningchen** [comment]
> @langningchen `未找到标签`是什么啊

应该没错吧

**Comment by PythonSmall-Q** [comment]
哦那他修改了之后会显示在哪里呢？

**Comment by langningchen** [comment]
用户名的后面

**Comment by langningchen** [comment]
我写了一个函数专门显示姓名，包括 头像、名字颜色、名字、管理员标签、自定义标签

**Comment by boomzero** [comment]
@langningchen 你把我名字打错了...

**Comment by boomzero** [comment]
![uid](https://github.com/langningchen/XMOJ-Script/assets/85378277/463dc663-38a9-4cb2-beac-f02d9421fd02)

**Comment by langningchen** [comment]
好吧，怪不得，不小心多打了一个`n`
