### ISSUE TITLE
[Feature Request] 增加代码公开计划 

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#205]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

代码公开计划是用户自愿参与的，他不是公开用户的AC代码，而是在用户AC题目时，通过用户的帐户权限自动获取std的代码并保存在服务器，并且参加代码公开计划且没有退出计划过的人可以查看已获得50分以上的题目的std代码

**Comment by PythonSmall-Q** [comment]
我同意。就是蛋糕拼接那道题没有std。只能用我题解里面发的

**Comment by langningchen** [comment]
@PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
我不会js……

**Comment by PythonSmall-Q** [comment]
我擅长程序设计但不擅长程序编写

**Comment by langningchen** [comment]
> （我是神犇

那就好

**Comment by PythonSmall-Q** [comment]
艹改我文字

**Comment by PythonSmall-Q** [comment]
你tm不得好死

**Comment by PythonSmall-Q** [comment]
艹

**Comment by langningchen** [comment]
Report content 了解一下

**Comment by PythonSmall-Q** [comment]
6

**Comment by boomzero** [comment]
What happened

**Comment by langningchen** [comment]
@boomzero Noting happened

**Comment by PythonSmall-Q** [comment]
@langningchen @boomzero 我在设想是不是可以把我们能看到的所有代码都保存下来到某个仓库里。既然服务器再境外，我们可以存在cloudflare S3或者github 仓库里。

**Comment by PythonSmall-Q** [comment]
如果需要的话我可以看到的标程比较多

**Comment by langningchen** [comment]
到时候我会写一个程序自动从用户那面爬标程

**Comment by PythonSmall-Q** [comment]
爬的话会被aliyun封禁

**Comment by PythonSmall-Q** [comment]
我是尝试过，我的服务器再aliyun已经挂上好了

**Comment by langningchen** [comment]
> 爬的话会被aliyun封禁

当然要加延时

**Comment by langningchen** [comment]
> @langningchen @boomzero 我在设想是不是可以把我们能看到的所有代码都保存下来到某个仓库里。既然服务器再境外，我们可以存在cloudflare S3或者github 仓库里。

@PythonSmall-Q 这样不是所有人都能看到标程了吗?

**Comment by PythonSmall-Q** [comment]
那就gitlab上

**Comment by PythonSmall-Q** [comment]
我有gitlab企业团队

**Comment by langningchen** [comment]
直接存服务器上不行吗？

**Comment by PythonSmall-Q** [comment]
浪费资源（我也要看doge

**Comment by PythonSmall-Q** [comment]
cloudflare数据库有传输速率限制的

**Comment by PythonSmall-Q** [comment]
大小也限制的

**Comment by langningchen** [comment]
问题不大

**Comment by langningchen** [comment]
在Cloudflar服务器直接用JS写入本地文件行吗？

**Comment by PythonSmall-Q** [comment]
那不是也会泄露给（？

**Comment by langningchen** [comment]
给谁？

**Comment by PythonSmall-Q** [comment]
浪费本地空间？tampermonkey由本地缓存大小限制

**Comment by langningchen** [comment]
不是，写在服务器本地

**Comment by PythonSmall-Q** [comment]
cloudflare workers限制我记得有的我去看看

**Comment by langningchen** [comment]
Go ahead

**Comment by PythonSmall-Q** [comment]
这里是Workers 免费计划，只要不超过10W次，

Free
US$0
用于个人用途和简单应用
Workers 功能
包括 100,000 个请求/天 (UTC+0) 
每个请求最多占用 10 毫秒 CPU 时间
第一个请求后的延迟最低
键值存储功能 2
每天 100,000 次读取操作
每天 1,000 次写入、删除、列出操作
您的当前计划
平台基本信息
最多 30 个 Worker
最多 100 个命名空间
最多 1GB 存储
部署到全球数以百计的数据中心
免费维护且自动扩展的基础结构
没有冷启动的高性能运行时
支持 JavaScript 及另外 9 种语言
完整的 CLI 部署功能
超过 100,000 个请求/天或 1,000 个请求/10 分钟后，Worker 请求将返回错误。
超出计划限制的键值读取、写入，删除和列出操作将失败。

**Comment by PythonSmall-Q** [comment]
哦忘记告诉你了1GB存储现在是付费的

**Comment by PythonSmall-Q** [comment]
KV免费版是我不知道因为我是企业子账号……

**Comment by PythonSmall-Q** [comment]
然后那个账号还有2FA我登陆都困难

**Comment by langningchen** [comment]
好吧

**Comment by PythonSmall-Q** [comment]
本来想捐献一下账号的……

**Comment by PythonSmall-Q** [comment]
我开gitlab了哦

**Comment by langningchen** [comment]
哪儿？

**Comment by PythonSmall-Q** [comment]
等一下

**Comment by langningchen** [comment]
我现在先弄那个头像

**Comment by PythonSmall-Q** [comment]
@langningchen 你注册一个gitlab账号

**Comment by langningchen** [comment]
> 我都写好了, 别改了

怎么写好了？在哪？

**Comment by langningchen** [comment]
等等

**Comment by PythonSmall-Q** [comment]
然后告诉我账号

**Comment by boomzero** [comment]
gitlab??

**Comment by PythonSmall-Q** [comment]
嗯

**Comment by boomzero** [comment]
> @langningchen @boomzero 我在设想是不是可以把我们能看到的所有代码都保存下来到某个仓库里。既然服务器再境外，我们可以存在cloudflare S3或者github 仓库里。

D1吧

**Comment by boomzero** [comment]
我有号

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/d78289b7-ae34-4e00-a92c-a8c62b7d3040)

我选成Company了怎么办？

**Comment by PythonSmall-Q** [comment]
注意角色选择Software Developer哦否则进不了团队

**Comment by PythonSmall-Q** [comment]
艹

**Comment by PythonSmall-Q** [comment]
group id：72138879

**Comment by boomzero** [comment]
https://gitlab.com/Thomas311926

**Comment by langningchen** [comment]
我是Software Developer

**Comment by PythonSmall-Q** [comment]
@boomzero 邀请了

**Comment by langningchen** [comment]
但是Company 怎么办？

**Comment by PythonSmall-Q** [comment]
没事我试试看能不能拉

**Comment by PythonSmall-Q** [comment]
你注册完主页发我一下我直接invite

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/4470ab3d-4377-417d-95d2-58ef225c00ff)
这是什么？

**Comment by langningchen** [comment]
为什么必须要创建新项目？

**Comment by PythonSmall-Q** [comment]
退回gitlab.com

**Comment by PythonSmall-Q** [comment]
然后去自己的主页

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/055b6eed-4a65-4d06-9321-ef01ffb8e620)
然后呢？

**Comment by langningchen** [comment]
我是用Github注册的，所以用户名和Github的一样 @PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
去你自己的主页

**Comment by PythonSmall-Q** [comment]
ok

**Comment by PythonSmall-Q** [comment]
好了
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/400fb9ba-b1e9-4a3d-8153-8dab35a45d62)

**Comment by langningchen** [comment]
看到了

**Comment by langningchen** [comment]
And, then?

**Comment by langningchen** [comment]
You clone the repo?

**Comment by PythonSmall-Q** [comment]
去team里的AC Codes那个就是村的地方

**Comment by langningchen** [comment]
I'm still formating your codes!

**Comment by PythonSmall-Q** [comment]
format完直接pull

**Comment by PythonSmall-Q** [comment]
我重新下一下吧

**Comment by langningchen** [comment]
Pull? Not push?

**Comment by langningchen** [comment]
@PythonSmall-Q 为什么你的Code这么奇怪？有的是 \r\n 有的是 \n 有的竟然是 \r\r\n

**Comment by PythonSmall-Q** [comment]
啥code？

**Comment by langningchen** [comment]
就是给我的 ACCode

**Comment by PythonSmall-Q** [comment]
链接发我

**Comment by langningchen** [comment]
Wait a minitue

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/f72137d0-c5b1-444a-8ed9-9e837537e89e)
I have only less than 100 files without formatting.

**Comment by PythonSmall-Q** [comment]
okay那你来我不下载了

**Comment by langningchen** [comment]
我好了

**Comment by langningchen** [comment]
XMOJ仓库已经Push了

**Comment by langningchen** [comment]
不是，我怎么又Close了

**Comment by PythonSmall-Q** [comment]
好了去AC Code Version 2 @langningchen @boomzero

**Comment by langningchen** [comment]
@PythonSmall-Q 我现在再写头像，等等

**Comment by PythonSmall-Q** [comment]
仓库现在完整了。我记得script里面有获取题目编号的。就用这个去调用即可

**Comment by langningchen** [comment]
> 仓库现在完整了。我记得script里面有获取题目编号的。就用这个去调用即可

不太明白

**Comment by PythonSmall-Q** [comment]
谁借我一个VPN我人都要炸了

**Comment by PythonSmall-Q** [comment]
或者有人知道可以登陆的GitHub及镜像站？

**Comment by PythonSmall-Q** [comment]
@langningchen 邮箱发我一个。我现在github40分钟才能上一次

**Comment by PythonSmall-Q** [comment]
为什么我付了钱还是显示要付钱……

**Comment by langningchen** [comment]
@PythonSmall-Q

**Comment by langningchen** [comment]
@PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
emm谁借我一下VPN

**Comment by PythonSmall-Q** [comment]
我人炸了

**Comment by langningchen** [comment]
可以

**Comment by PythonSmall-Q** [comment]
邮箱打包发我谢谢

**Comment by langningchen** [comment]
@PythonSmall-Q 请进这里： https://hack.chat/?swxcln

**Comment by langningchen** [comment]
> 邮箱打包发我谢谢

@PythonSmall-Q 
不太方便

**Comment by PythonSmall-Q** [comment]
那咋办？

**Comment by langningchen** [comment]
邮箱我不太方便，可以使用： https://hack.chat/?swxcln

**Comment by PythonSmall-Q** [comment]
快删

**Comment by langningchen** [comment]
@PythonSmall-Q 好了

**Comment by langningchen** [comment]
> 快删

新进来的人看不到旧的聊天记录，进来人也能看到通知

**Comment by PythonSmall-Q** [comment]
好

**Comment by PythonSmall-Q** [comment]
好卡（doge我换个服

**Comment by langningchen** [comment]
> 好卡（doge我换个服

？

**Comment by PythonSmall-Q** [comment]
US的好像很卡的样子

**Comment by langningchen** [comment]
没有把

**Comment by langningchen** [comment]
我这里很好

**Comment by langningchen** [comment]
就是branch `langningchen/badge-and-code-sharing`，我的这个增加代码公开计划的后端已经写好了，有谁有空帮我写一下前端？ @boomzero @PythonSmall-Q

**Comment by langningchen** [comment]
正在写前端，获取标程写好了，但是上传没有写好

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/7641e6f6-edda-4844-8d50-efc31f0a1cd9)

我正在上传自己的标程

**Comment by langningchen** [comment]
https://github.com/langningchen/XMOJ-Script/assets/81672884/b9f16e1a-9350-4dcc-8da7-7de4a10bdb13

可以断点续传，如视频所示

**Comment by langningchen** [comment]
我不敢一直上传，所以就上传10%等一分钟

**Comment by langningchen** [comment]
@PythonSmall-Q @boomzero 代码公开计划做好了，你们试一试，现在还没有发布预览版，在`langningchen/badge-and-code-sharing`分支

**Comment by langningchen** [comment]
@boomzero 你先看看这个

**Comment by boomzero** [comment]
@langningchen ~但是我不会用~

**Comment by langningchen** [comment]
就是在提交界面找一个大于50分的提交，旁边就会有查看标程的按钮

**Comment by langningchen** [comment]
前提是你得手动复制一下我那个分支的代码，因为我没有发布预览版

**Comment by langningchen** [comment]
太棒了！

**Comment by langningchen** [comment]
你上传应该快很多了，因为有很多题我都上传过了

**Comment by langningchen** [comment]
说实话，这个挺消耗我们服务器和XMOJ服务器的资源的

**Comment by langningchen** [comment]
你这里还挺快，我总共传了20分钟

**Comment by langningchen** [comment]
我怕被封号，所以我都是每上传10%就强制刷新中断一下，等一分钟再继续传

**Comment by boomzero** [comment]
> 说实话，这个挺消耗我们服务器和XMOJ服务器的资源的

~~至少比那个在签到题上交1000个`while(true)`的那个人好~~

**Comment by langningchen** [comment]
谁呀？

**Comment by boomzero** [comment]
卡住了

**Comment by boomzero** [comment]
```
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    onload moz-extension://4717b6c4-3ee5-44bc-a09e-655f90d3213d/userscripts/XMOJ.user.js?id=c3bd36c0-f9c6-46b2-b9ee-0328befe0fba:3919
    St http://www.xmoj.tech/userinfo.php?ByUserScript=1:9
    i http://www.xmoj.tech/userinfo.php?ByUserScript=1:33
    St http://www.xmoj.tech/userinfo.php?ByUserScript=1:9
    r http://www.xmoj.tech/userinfo.php?ByUserScript=1:22
    Fo http://www.xmoj.tech/userinfo.php?ByUserScript=1:23
    g http://www.xmoj.tech/userinfo.php?ByUserScript=1:69
    g http://www.xmoj.tech/userinfo.php?ByUserScript=1:69
```

**Comment by boomzero** [comment]
1862

**Comment by langningchen** [comment]
可能是服务器运行的时候CPU时间超了

**Comment by langningchen** [comment]
你刷新重试一下

**Comment by boomzero** [comment]
> 你刷新重试一下

不行

**Comment by boomzero** [comment]
一上来就卡

**Comment by boomzero** [comment]
> 实在不行你可以通过控制台下断点的方法，把ACList这个数组里面这一项去掉就可以了

?

**Comment by boomzero** [comment]
这个有bug?

**Comment by boomzero** [comment]
> > 这个有bug?
> 
> 可能就是他的标程找不到而已

那能skip吗

**Comment by langningchen** [comment]
> > 实在不行你可以通过控制台下断点的方法，把ACList这个数组里面这一项去掉就可以了
> 
> ?

按f12在命令行里面搜索ACList关键字，你应该能看懂我写的脚本代码的

**Comment by boomzero** [comment]
没交std?

**Comment by langningchen** [comment]
> 没交std?

应该按理说没这种问题的

**Comment by boomzero** [comment]
~说句闲话, 我在改综评报告~

**Comment by langningchen** [comment]
没事，你先弄吧，我也去睡觉了

**Comment by boomzero** [comment]
> 好的, 在传了

done

**Comment by langningchen** [comment]
这个应该算是做好了，那就Close了

**Comment by PythonSmall-Q** [comment]
这玩意儿到底怎么用？

**Comment by PythonSmall-Q** [comment]
@langningchen

**Comment by PythonSmall-Q** [comment]
我知道怎么用了

**Comment by PythonSmall-Q** [comment]
则玩意儿一直报错

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/f49dac3e-cc69-4bd7-aaa1-cf97a867575c)

**Comment by PythonSmall-Q** [comment]
@langningchen

**Comment by langningchen** [comment]
@PythonSmall-Q 在什么时候保存？刚开始上传还是上传到一半？

**Comment by langningchen** [comment]
@PythonSmall-Q  `0.2.102` 版本能显示详细的错误信息你尝试再来一次，然后把错误信息截屏发给我
