### ISSUE TITLE
[Bug] 关于账号

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#206]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我为什么打开xmoj发现我自动登上了 @langningchen 的号...

**Comment by PythonSmall-Q** [comment]
艹好神奇

**Comment by PythonSmall-Q** [comment]
赶紧导出AC记录(bushi

**Comment by langningchen** [comment]
我知道

**Comment by langningchen** [comment]
是因为额……

**Comment by langningchen** [comment]
我们现在用的是一个Token

**Comment by langningchen** [comment]
所以我们的账号只能登陆一个

**Comment by langningchen** [comment]
> 赶紧导出AC记录(bushi

@PythonSmall-Q 不用导出，直接看这里： https://github.com/langningchen/XMOJ

**Comment by PythonSmall-Q** [comment]
6

**Comment by langningchen** [comment]
@PythonSmall-Q 🤫

**Comment by PythonSmall-Q** [comment]
luogu代码你有吗？

**Comment by PythonSmall-Q** [comment]
我要洛谷刷分

**Comment by langningchen** [comment]
我自己洛谷练习的很少

**Comment by langningchen** [comment]
也有的，不过没什么用

**Comment by langningchen** [comment]
你可以用别人的，直接用 Github Search 搜索 Luogu 全都是

**Comment by PythonSmall-Q** [comment]
https://github.com/PythonSmall-Q/OI-Codes
我的xmoj

**Comment by langningchen** [comment]
@boomzero 所以我用你的Token退出我的登录然后我换一个Token登录就好了

**Comment by langningchen** [comment]
> https://github.com/PythonSmall-Q/OI-Codes 我的xmoj

@boomzero 已经把他的ACCode Merge 到我的仓库里了，你同意我把你的ACCode也Merge进去吗？

**Comment by PythonSmall-Q** [comment]
可以

**Comment by langningchen** [comment]
2 days ago

**Comment by PythonSmall-Q** [comment]
要不你的merge到我这里？

**Comment by langningchen** [comment]
你这些全是AC的代码吗？

**Comment by PythonSmall-Q** [comment]
还是我的到你这里吧我来merge

**Comment by langningchen** [comment]
> 还是我的到你这里吧我来merge

不用，我一会儿手动处理Conflict

**Comment by langningchen** [comment]
我那里有一些时没有AC的

**Comment by langningchen** [comment]
@boomzero 没事了，我已经退出登陆了

**Comment by langningchen** [comment]
> 还是我的到你这里吧我来merge

@PythonSmall-Q 我正在整理你的Code，所以还没有合并进去
