### ISSUE TITLE
[Enhancement] 增加gravatar与libavatar支持

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#221]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

用户可以在设置中选择使用gravatar还是cravatar还是libavatar
我想也可以优先我的那个gravatar镜像，如果出来默认头像就是cravatar还是不行就random

**Comment by boomzero** [comment]
能加libavatar吗

**Comment by langningchen** [comment]
就用cravatar不行吗？QAQ

**Comment by PythonSmall-Q** [comment]
cravatar的头像不全。

**Comment by PythonSmall-Q** [comment]
而且经常挂

**Comment by langningchen** [comment]
有空再弄吧

**Comment by PythonSmall-Q** [comment]
这个api文件比较：
https://image-compare.hcti.io/

**Comment by langningchen** [comment]
不是，主要问题是如果这样，服务器就要再多存一个数据

**Comment by langningchen** [comment]
又多消耗一份服务器资源，我觉得没必要

**Comment by PythonSmall-Q** [comment]
不会占用服务器资源吧

**Comment by langningchen** [comment]
会的，每次用户都要保存一下他使用的服务

**Comment by langningchen** [comment]
而且每次显示都要查询一下

**Comment by langningchen** [comment]
@PythonSmall-Q
