### ISSUE TITLE
[Bug] 未登录去讨论区会跳转到不存在页面

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#222]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

会自动跳转到 http://www.xmoj.tech/discuss3/loginpage.php

### 重现步骤

在其他页面注销, 然后点讨论 or 等cookie过期

**Comment by langningchen** [comment]
这个问题一直都存在，就是不知道怎么修

**Comment by boomzero** [comment]
加一个跳转?

**Comment by boomzero** [comment]
如果path是那个自动跳转

**Comment by langningchen** [comment]
不是，是因为我跳转的时候是用的是相对路径，而应该用绝对路径才能正常跳转

**Comment by langningchen** [comment]
因为讨论的目录比其他的都要深一层，所以就会出跳转的问题

**Comment by boomzero** [comment]
你就加一个如果访问这个404 page就跳转

**Comment by langningchen** [comment]
访问到404页面以后用户脚本就执行不起来了

**Comment by langningchen** [comment]
所以，解决方法就是直接把所有的相对路径全换成绝对路径就好了

**Comment by boomzero** [comment]
thx
