### ISSUE TITLE
[Feature Request] 用github actions测试update功能

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#223]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

用github actions测试update功能

**Comment by langningchen** [comment]
具体怎么说？

**Comment by boomzero** [comment]
自动发布一个?

**Comment by langningchen** [comment]
自动发布什么？现在不一定是用Github Actions自动发布新版本了吗？

**Comment by boomzero** [comment]
想办法写一个unit test

**Comment by langningchen** [comment]
不会……

**Comment by boomzero** [comment]
> 不会……

我记得github copilot labs可以生成

**Comment by langningchen** [comment]
额，确实，但是好像不是这一种

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q 既然都没有人会，那就没法实现了
