### ISSUE TITLE
[Bug] pr updateVersion

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#226]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

UpdateVersion 一直制造merge conflict...

**Comment by langningchen** [comment]
这个因为你的分支落后于Dev分支

**Comment by langningchen** [comment]
请确保你的分支是最新的

**Comment by langningchen** [comment]
@boomzero
