### ISSUE TITLE
[Feature Request] add username colors everywhere

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#227]
### 描述

This is only in ACM ranking and discuss now.

- [x] OI ranking 
- ~~User homepage~~
- [x] http://www.xmoj.tech/problemstatus.php
- [x] 订正排名

**Comment by langningchen** [comment]
开学了估计没太有空

**Comment by langningchen** [comment]
有时间来吧

**Comment by boomzero** [comment]
> 开学了估计没太有空

+1

**Comment by langningchen** [comment]
不过这个弄起来挺简单的，因为我已经把显示姓名的包装到一个函数里了

**Comment by langningchen** [comment]
这个函数包括显示用户头像，显示名字颜色，以及显示用户标签

**Comment by PythonSmall-Q** [comment]
开学了我基本就没办法维护了……

**Comment by PythonSmall-Q** [comment]
太忙了。9/3区交流活动，9/28运动会……

**Comment by langningchen** [comment]
我也不行了，我在想开学以后是不是就要用public achieve了

**Comment by boomzero** [comment]
不需要archive啊

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/2426f85c-bf9e-4615-a1b0-0624e8447b4b)

**Comment by langningchen** [comment]
User homepage 都有 Rating 了，就不加了（因为加有点麻烦）

**Comment by boomzero** [comment]
thx

**Comment by boomzero** [comment]
哦对, 还有订正排名

**Comment by langningchen** [comment]
好的

**Comment by boomzero** [comment]
thx
