### ISSUE TITLE
[Feature Request] 官网允许search engine crawler

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#233]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

### 原因

![gs](https://github.com/langningchen/XMOJ-Script/assets/85378277/047b7b1f-4f37-4e0b-b577-d6dae17d22e2)

**Comment by boomzero** [comment]
done, I think

**Comment by boomzero** [comment]
@langningchen ?

**Comment by PythonSmall-Q** [comment]
403那个点进去发个图我看看是什么原因

**Comment by PythonSmall-Q** [comment]
是不是robots.txt没加或者是Cloudflare里面允许

**Comment by boomzero** [comment]
> 是不是robots.txt没加或者是Cloudflare里面允许

@PythonSmall-Q 我在WAF里ban了known bots...

**Comment by langningchen** [comment]
@boomzero Still need I to triage?

**Comment by boomzero** [comment]
> @boomzero Still need I to triage?

@langningchen 搞好了, 不需要triage了
