### ISSUE TITLE
[Feature Request] Follow best practises in the official website

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#234]
### 描述

- [x] #235
- [x] #237
- [x] #236

### 原因

![](https://github.com/langningchen/XMOJ-Script/assets/85378277/d1414724-8a43-4eea-b686-d0bff2b75a72)

**Comment by PythonSmall-Q** [comment]
这玩意儿建议开一下cloudflare那个压缩缓存。免费的

**Comment by PythonSmall-Q** [comment]
我记得开启方式是去discord频道然后干个啥事情的

**Comment by boomzero** [comment]
> 这玩意儿建议开一下cloudflare那个压缩缓存。免费的

有cache 啊

**Comment by boomzero** [comment]
> 我记得开启方式是去discord频道然后干个啥事情的

?

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q 你们搞吧，搜索引擎这玩意儿我不熟

**Comment by PythonSmall-Q** [comment]
> 这玩意儿建议开一下cloudflare那个压缩缓存。免费的

emm是压缩和cache是不一样的

**Comment by PythonSmall-Q** [comment]
我都看不到具体的Cloudflare设置我怎么搞（bushi

> @boomzero @PythonSmall-Q 你们搞吧，搜索引擎这玩意儿我不熟

**Comment by PythonSmall-Q** [comment]
@langningchen 

> 我都看不到具体的Cloudflare设置我怎么搞（bushi
> 
> > @boomzero @PythonSmall-Q 你们搞吧，搜索引擎这玩意儿我不熟

**Comment by boomzero** [comment]
@PythonSmall-Q Ok, 我看一下

**Comment by boomzero** [comment]
@PythonSmall-Q Image optimization 要交钱

**Comment by boomzero** [comment]
@PythonSmall-Q Rocket loader 要开吗

**Comment by boomzero** [comment]
还有Auto Minify

**Comment by PythonSmall-Q** [comment]
Rocket Loader要开可以的

**Comment by PythonSmall-Q** [comment]
Auto Minify要开的

**Comment by PythonSmall-Q** [comment]
Image Optimization就算了。毕竟你们的账户没付钱

**Comment by PythonSmall-Q** [comment]
其实开了没太大差别。也就几张图片

**Comment by boomzero** [comment]
> Rocket Loader要开可以的

thx, 开了

**Comment by boomzero** [comment]
@PythonSmall-Q 
![compress](https://github.com/langningchen/XMOJ-Script/assets/85378277/de4b3c96-b2ac-49c5-bff3-2b5b8a6ae381)
压缩是这个吗, 开了

**Comment by PythonSmall-Q** [comment]
嗯

**Comment by PythonSmall-Q** [comment]
再诊断一下，结果能完整发一下吗？只看一点有的坐牢

**Comment by PythonSmall-Q** [comment]
看不出来能干啥

**Comment by boomzero** [comment]
@PythonSmall-Q OK

**Comment by boomzero** [comment]
https://pagespeed.web.dev/analysis/https-web-xmoj-bbs-tech/1i0yad6vxa?utm_source=search_console&form_factor=mobile&hl=en

**Comment by boomzero** [comment]
![rst](https://github.com/langningchen/XMOJ-Script/assets/85378277/763ead91-766a-4c4c-a275-ae2ec74ba288)
...

**Comment by boomzero** [comment]
Defer offscreen images试一试

**Comment by langningchen** [comment]
Accessibility 比较低

**Comment by langningchen** [comment]
我是有意的

**Comment by langningchen** [comment]
因为我不想让 ~盲人~ 视障人员来看我们的网页，再说也没有视障人员来用这个脚本

**Comment by boomzero** [comment]
> 因为我不想让 ~盲人~ 视障人员来看我们的网页，再说也没有视障人员来用这个脚本

...

**Comment by boomzero** [comment]
before:
![](https://github.com/langningchen/XMOJ-Script/assets/85378277/d1414724-8a43-4eea-b686-d0bff2b75a72)
after:
![rst](https://github.com/langningchen/XMOJ-Script/assets/85378277/763ead91-766a-4c4c-a275-ae2ec74ba288)
...

**Comment by boomzero** [comment]
主要是image 没有alt

**Comment by langningchen** [comment]
对的，图片和按钮没有解释文本

**Comment by boomzero** [comment]
> 对的，图片和按钮没有解释文本

其实可以让alt为空

**Comment by boomzero** [comment]
还有`<meta
  name="description"
  content="...">`

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/6ccef249-f564-4ce9-b8e7-665358d39c18)
这几个玩意儿可以弄弄

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/4735ed7c-845f-4aa4-9757-0497633399ff)
这俩最好保持5s以内

**Comment by PythonSmall-Q** [comment]
assign我干吗我有没有cloudflare设置

**Comment by langningchen** [comment]
你要吗？

**Comment by langningchen** [comment]
QWQ

**Comment by PythonSmall-Q** [comment]
我随便

**Comment by PythonSmall-Q** [comment]
如果你要家的话就是seanoj_noreply@yeah.net。记得允许pages，D1和website

**Comment by langningchen** [comment]
好的

**Comment by langningchen** [comment]
@PythonSmall-Q @boomzero 怎么加来着…… QWQ

**Comment by PythonSmall-Q** [comment]
members

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/c763dd6a-2554-45c7-97d0-9544bb37e425)
@langningchen

**Comment by langningchen** [comment]
Ohh

**Comment by langningchen** [comment]
@PythonSmall-Q 去接受吧，我权限懒得选了
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/ed14558f-8ad3-4efb-a4ac-ec36941206ec)

**Comment by boomzero** [comment]
@PythonSmall-Q any ideas?

**Comment by PythonSmall-Q** [comment]
等我有空了看

**Comment by boomzero** [comment]
@PythonSmall-Q 主要是dns也很慢

**Comment by boomzero** [comment]
~所以我们要多query几次, 让我们的网址ip留在各大dns服务商的cache里

**Comment by boomzero** [comment]
```fish
 while True
      dig www.xmoj-bbs.tech
end
```

**Comment by boomzero** [comment]
~md,我终端死机了~

**Comment by langningchen** [comment]
> ```fish
> while True
>       dig www.xmoj-bbs.tech
> end
> ```
> @langningchen ~用fish跑一下~

.......

**Comment by langningchen** [comment]
> ```fish
> while True
>       dig www.xmoj-bbs.tech
> end
> ```
> 
> @langningchen ~用fish跑一下~

@boomzero 我跑了 😆 

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/b4403fed-0181-49e2-afdc-9007e5ee04c2)

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/c8b451b3-f289-4e51-91a7-e9535ed4779b)

**Comment by boomzero** [comment]
> ![image](https://user-images.githubusercontent.com/81672884/266768568-c8b451b3-f289-4e51-91a7-e9535ed4779b.png)

~不错~

**Comment by boomzero** [comment]
因为所有task都done了, 所以close
