### ISSUE TITLE
[Feature Request] 讨论多人回复只提醒一次

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#242]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

http://www.xmoj.tech/discuss3/thread.php?tid=251

**Comment by langningchen** [comment]
我就说嘛，这个有点难，所以准备改成个讨论尽管有多人回复也只提醒一次

**Comment by boomzero** [comment]
@langningchen 改了

**Comment by langningchen** [comment]
好的

**Comment by langningchen** [comment]
与 #270 一样，又要改数据库结构了

**Comment by langningchen** [comment]
我已经临时把提醒全删掉了

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/ce6d2568-4147-4294-a390-7cc223742f84)

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q 如果这样，那么在提示的时候就无法显示发送提示的用户

**Comment by boomzero** [comment]
> @boomzero @PythonSmall-Q 如果这样，那么在提示的时候就无法显示发送提示的用户

没事
