### ISSUE TITLE
[Feature Request] 在提醒中加上用户名颜色和badge

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#243]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

**Comment by langningchen** [comment]
OK

**Comment by boomzero** [comment]
显示`[object Promise]`

**Comment by boomzero** [comment]
async+await?

**Comment by langningchen** [comment]
呃，可能忘记加await了

**Comment by langningchen** [comment]
好了
