### ISSUE TITLE
[Feature Request] Make the oi-ranking prettier

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#244]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

### 原因

![](https://github.com/langningchen/XMOJ-Script/assets/85378277/e6c714cd-f2ea-454d-9f1a-4273d8b7a4fb)

The contrast is weird

**Comment by langningchen** [comment]
好吧，我原来改过这个，但是不知道为什么可能没保存，或者被Git给弄掉了，我找找看

**Comment by langningchen** [comment]
还好有Git，能翻一翻历史

**Comment by langningchen** [comment]
唉，找不到了，重新写吧

**Comment by langningchen** [comment]
什么颜色呢？

**Comment by langningchen** [comment]
Is this better? 
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/5c3d77e5-449a-468d-92fc-62155355ee10)

**Comment by PythonSmall-Q** [comment]
emm这个挺好看的

**Comment by PythonSmall-Q** [comment]
好消息：9/3我不用去交流啦！

**Comment by langningchen** [comment]
> 好消息：9/3我不用去交流啦！

我还在高老师那边再在考试前上五次课 @PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
我也要

**Comment by langningchen** [comment]
你上哪个班？ @PythonSmall-Q

**Comment by boomzero** [comment]
订正排名也改一下 @langningchen

**Comment by langningchen** [comment]
改好了
