### ISSUE TITLE
[Feature Request] 短消息显示message_id

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#246]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

### 原因

~~我刚刚删我的PHPSESSID那条消息时填错了message_id...~~

**Comment by boomzero** [comment]
![del](https://github.com/langningchen/XMOJ-Script/assets/85378277/50e0ba56-66c7-41a7-9412-d27a5f69d69e)

**Comment by boomzero** [comment]
应该是278...

**Comment by langningchen** [comment]
这个没必要吧……普通人显示了也没用，你倒是可以提一个Issue叫短消息7天后自动销毁

**Comment by boomzero** [comment]
> 这个没必要吧……普通人显示了也没用，你倒是可以提一个Issue叫短消息7天后自动销毁

~可以, 不然你发的密码一直在里面~
