### ISSUE TITLE
[Bug] 讨论区点击用户名会404

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#248]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

see #222

**Comment by langningchen** [comment]
呃呃呃

**Comment by boomzero** [comment]
@langningchen

**Comment by langningchen** [comment]
你@我干什么

**Comment by langningchen** [comment]
我知道了这个错了

**Comment by boomzero** [comment]
@langningchen what happened

**Comment by langningchen** [comment]
就是上次没改全

**Comment by boomzero** [comment]
~说句闲话, 不要抄袭当年代码~

**Comment by boomzero** [comment]
@langningchen 能把抄代码蓝名加回去吗

**Comment by langningchen** [comment]
没必要吧……

**Comment by boomzero** [comment]
> 没必要吧……

Why not?

**Comment by langningchen** [comment]
都有标签了，还要蓝名干什么？

**Comment by boomzero** [comment]
警示

**Comment by langningchen** [comment]
没必要吧……

**Comment by boomzero** [comment]
> 没必要吧……

以前有的啊

**Comment by langningchen** [comment]
后来我删掉了，因为这个如果加上也很麻烦，没法用统一的获取用户名的接口

**Comment by boomzero** [comment]
> 后来我删掉了，因为这个如果加上也很麻烦，没法用统一的获取用户名的接口

好吧

**Comment by boomzero** [comment]
?

**Comment by boomzero** [comment]
@langningchen
