### ISSUE TITLE
打开mail.php显示错误

### ISSUE THREAD

**Issue by lianzhongzhe** [langningchen/XMOJ-Script#25]
打开mail.php显示`JSON解析错误：SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON`
刷新一下就发现自己被注销了

**Comment by langningchen** [comment]
需要知道更多复现信息

**Comment by lianzhongzhe** [comment]
更新之后变花样报错了
![image](https://github.com/langningchen/XMOJ-Script/assets/122505030/d215f2ad-5428-4161-96fd-837eda8320d5)
刷新几遍都是这样的

**Comment by langningchen** [comment]
现在解决了，这是服务器的错误所以你不用更新。导致错误的功能已经被禁用。

**Comment by langningchen** [comment]
这是因为 #27 导致的错误
