### ISSUE TITLE
讨论区无法删除帖子

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#27]
删除时显示 JSON解析错误：SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by langningchen** [comment]
Finally, fixed!

**Comment by boomzero** [comment]
@langningchen thx

**Comment by langningchen** [comment]
@boomzero 你再试一试，应该可以了

**Comment by boomzero** [comment]
@langningchen 建议删完后跳到主页,不然会显示错误：没有此讨论
