### ISSUE TITLE
[Feature Request] 自己@自己时不提醒

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#270]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

**Comment by langningchen** [comment]
好的

**Comment by boomzero** [comment]
thx
