### ISSUE TITLE
[Feature Request] use alpha tag for prerelease like v0.2.103alpha-1

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#271]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

### 原因

~~现在的版本号有点吓人啊~~

**Comment by PythonSmall-Q** [comment]
确实

**Comment by PythonSmall-Q** [comment]
是不是应该进入0.3时代了

**Comment by langningchen** [comment]
Emm.

**Comment by langningchen** [comment]
@boomzero UserScript管理器好像不认识英文字母

**Comment by langningchen** [comment]
这个版本号不吓人，你没看Windows版本号都几万的

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/574bd187-5766-47fd-ae99-0a02bcf2d295)

25936

**Comment by boomzero** [comment]
@langningchen ~我们不是windows啊~

**Comment by langningchen** [comment]
> @boomzero UserScript管理器好像不认识英文字母

主要是这个原因
