### ISSUE TITLE
[Feature Request] 把这个repo变成github团队

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#289]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

### 原因

~~看起来高级~~

**Comment by langningchen** [comment]
额，好吧

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/5629fcac-fe3a-4372-b350-e982398c0493)
行吗？

**Comment by langningchen** [comment]
@boomzero

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q Invited you to the org

**Comment by boomzero** [comment]
thx

**Comment by boomzero** [comment]
把repo转进去?

**Comment by langningchen** [comment]
一会儿

**Comment by boomzero** [comment]
@langningchen

**Comment by langningchen** [comment]
我知道

**Comment by langningchen** [comment]
我正在改 #242 ，不然到时候本地和远程同步容易出问题

**Comment by PythonSmall-Q** [comment]
已加入

**Comment by langningchen** [comment]
@PythonSmall-Q 好的

**Comment by langningchen** [comment]
@PythonSmall-Q 你在线，就帮我 Review #294 ，没有 Review 我没法 Merge

**Comment by boomzero** [comment]
测试

**Comment by langningchen** [comment]
我要准备换了，请大家做好准备 @boomzero @PythonSmall-Q

**Comment by langningchen** [comment]
啊，好了

**Comment by langningchen** [comment]
准备换回来

**Comment by langningchen** [comment]
换好了

**Comment by boomzero** [comment]
why?

**Comment by boomzero** [comment]
@langningchen

**Comment by langningchen** [comment]
因为我不是高级团队，所以权限配置有问题

**Comment by langningchen** [comment]
还有你的自动翻译我也准备删掉，因为会造成修改冲突，他先获取了，然后我修改了，他翻译以后在修改就把我修改的覆盖掉了

**Comment by langningchen** [comment]
并且有图片的时候再放一遍很占空间

**Comment by boomzero** [comment]
> 还有你的自动翻译我也准备删掉，因为会造成修改冲突，他先获取了，然后我修改了，他翻译以后在修改就把我修改的覆盖掉了
> 
> Also, I am going to delete your automatic translation, because it will cause modification conflicts. He obtained it first, and then I modified it. After he translated it, he modified it and overwritten what I modified

不会的, 他会在翻译的

**Comment by langningchen** [comment]
> > 还有你的自动翻译我也准备删掉，因为会造成修改冲突，他先获取了，然后我修改了，他翻译以后在修改就把我修改的覆盖掉了
> > Also, I am going to delete your automatic translation, because it will cause modification conflicts. He obtained it first, and then I modified it. After he translated it, he modified it and overwritten what I modified
> 
> 不会的, 他会在翻译的

但是并没有

**Comment by boomzero** [comment]
@langningchen 有的啊

**Comment by boomzero** [comment]
这不是一个坏主意啊

**Comment by boomzero** [comment]
翻译参见https://github.com/walinejs/waline/blob/main/.github/workflows/translator.yml

**Comment by PythonSmall-Q** [comment]
emm那个团队就不要了？

**Comment by langningchen** [comment]
那个团队先留着，等等看情况
