### ISSUE TITLE
建议恢复BBS

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#3]
建议恢复bbs页面

**Comment by langningchen** [comment]
What do you mean by "恢复"?

**Comment by langningchen** [comment]
You want me to write a server to support BBS?

**Comment by langningchen** [comment]
I can write it, but it may take some days.

**Comment by PythonSmall-Q** [comment]
no, just to add the bbs icon back

**Comment by langningchen** [comment]
But I don't know how is this button like since I have never seen it.

**Comment by langningchen** [comment]
#22

**Comment by langningchen** [comment]
Working steps:
- [x] Set up server
- [x] Fix the post new thread
- [x] Fix the comment in new thread
- [ ] Add delete, edit utilities

**Comment by langningchen** [comment]
Finally, add this enhancement! It has **already** released.
