### ISSUE TITLE
[Feature Request] dev不改变 XMOJ.user.js 时不发布新版本

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#301]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

---
### Check items

- [X] I have confirmed that the XMOJ enhancement script is the latest version, and the latest version does not implement this function.
- [X] I have searched the [Issues page](https://github.com/langningchen/XMOJ-Script/Issues) and confirmed that this proposal has not been submitted.

### describe

rt

**Comment by PythonSmall-Q** [comment]
emm确实有点烦

**Comment by PythonSmall-Q** [comment]
nnd 你别翻译了

**Comment by PythonSmall-Q** [comment]
我再次感谢actions

**Comment by PythonSmall-Q** [comment]
艹

**Comment by PythonSmall-Q** [comment]
> 艹

看看能不能翻译

**Comment by langningchen** [comment]
就是 @boomzero 非得要翻译，说显得很高级

**Comment by boomzero** [comment]
> 就是 @boomzero 非得要翻译，说显得很高级
> 
> It’s just that @boomzero has to translate it, saying it looks very advanced

...

**Comment by boomzero** [comment]
@langningchen dev不是删了吗

**Comment by langningchen** [comment]
Deleting `dev`? Are you crazy?! @boomzero

**Comment by boomzero** [comment]
...

**Comment by boomzero** [comment]
> @langningchen dev不是删了吗(翻译)

**Comment by langningchen** [comment]
没有删除dev

**Comment by boomzero** [comment]
> Deleting `dev`? Are you crazy?! @boomzero

You can revert the change even if you delete it, so it's not that crazy.

**Comment by boomzero** [comment]
> 没有删除dev
> 
> did not remove dev

翻译action 删了...

**Comment by langningchen** [comment]
对的，是我删的

**Comment by boomzero** [comment]
Of course you didn't delete dev

**Comment by boomzero** [comment]
> 对的，是我删的

对啊, 就是这个意思

**Comment by langningchen** [comment]
issue #301 不太好解决

**Comment by langningchen** [comment]
只在dev分支删除了翻译，还没有提交到master，所以还没生效

**Comment by boomzero** [comment]
let me try

**Comment by langningchen** [comment]
@boomzero 话说它为什么PR merge以后没有自动close issue?

**Comment by boomzero** [comment]
> @boomzero 话说它为什么PR merge以后没有自动close issue?

不是merge到master @langningchen

**Comment by langningchen** [comment]
哦，原来是这样
