### ISSUE TITLE
[Bug] 部分页面无法点击右上角menu

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#309]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

rt, 如果看源代码会发现被替换掉了

### 重现步骤

去`http://www.xmoj.tech/modifypage.php` ~~when you're unlucky~~

### 控制台错误信息

```
Uncaught TypeError: s.createPopper is not a function
    _createPopper dropdown.js:241
    show dropdown.js:139
    toggle dropdown.js:121
    <anonymous> dropdown.js:446
    i event-handler.js:118
9 dropdown.js:241:26
    _createPopper dropdown.js:241
    show dropdown.js:139
    toggle dropdown.js:121
    <anonymous> dropdown.js:446
    i event-handler.js:118

```

**Comment by langningchen** [comment]
`如果看源代码会发现被替换掉了`是什么意思？

**Comment by langningchen** [comment]
@boomzero 我这里有尝试了一下，没法复现……

**Comment by langningchen** [comment]
因为我已经引入了这个JS

https://github.com/langningchen/XMOJ-Script/blob/289bf392da20654b7a0a967f9cfc31e9c8246bf6/XMOJ.user.js#L361C1-L363

**Comment by langningchen** [comment]
你再试试，如果总是不行再重开Issue

**Comment by boomzero** [comment]
@langningchen ~说句闲话, 你作业写的好快啊~

**Comment by langningchen** [comment]
> @langningchen 可能和我的vpn有关吧, 建议如果失败换用[jsDelivr](https://www.jsdelivr.com/)

可以，enhancement见

**Comment by langningchen** [comment]
@boomzero
