### ISSUE TITLE
[Feature Request] 切换至jsDelivr

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#311]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

**Comment by langningchen** [comment]
加载失败是不行的，应当全部使用

**Comment by boomzero** [comment]
> 加载失败是不行的，应当全部使用

jsdelivr在中国某些地区开不了吧

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/0a0c57ea-a72b-41fe-b1ca-35ee9f05c503)

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/548e7dfe-dbde-419a-96f0-eb6ab4bb2d09)

@boomzero 看了这两张图，你觉得还要换成jsDilivr吗？

**Comment by langningchen** [comment]
加载失败是没法检测的，因为加载附加脚本归 Tampermonkey 管，而不是我的 userjs 管

**Comment by boomzero** [comment]
那就算了吧...

**Comment by boomzero** [comment]
不过我们的discuss api应该和jsdelivr差不多

**Comment by langningchen** [comment]
> 不过我们的discuss api应该和jsdelivr差不多

额，确实

**Comment by PythonSmall-Q** [comment]
Jsdelivr不建议切换。中国访问太慢

Sent from Mail for Windows

From: Zhu Chenrui
Sent: 2023年9月6日 21:57:09
To: langningchen/XMOJ-Script
Cc: Subscribed
Subject: [langningchen/XMOJ-Script] [Feature Request] 如果bootcdn加载失败切换至jsDelivr (Issue #311)

检查项
• [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
• [X] 我已在 Issues 页面 中搜索，确认了这一提案未被提交过。
描述
rt
原因
No response
