### ISSUE TITLE
Version 6.0 of ansi_up.js is incompatible with XMOJ-Script

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#33]
Because ansi_up.js switched to an ES6 module, currently XMOJ-script will report 
`Uncaught SyntaxError: export declarations may only appear at top level of a module www.xmoj.tech:3242`

**Comment by boomzero** [comment]
fixed in v0.1.51

**Comment by langningchen** [comment]
@boomzero No actually fixed, but not load the ansi_up.js depencency. This can cause the submit compile error check failed.

**Comment by langningchen** [comment]
THe compile error check is denpend on this file.

**Comment by boomzero** [comment]
@langningchen can't use use an older version, from what I understand version 5.1 is still supported

**Comment by boomzero** [comment]
我开一个pr

**Comment by boomzero** [comment]
@langningchen https://github.com/langningchen/XMOJ-Script/pull/34

**Comment by langningchen** [comment]
OK

**Comment by boomzero** [comment]
> OK

thx
