### ISSUE TITLE
[Feature Request] 不要替换样例里的文字

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#342]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt, 如果不可以可以去掉xiaoming的替换

### 原因

替换后样例会不对

**Comment by langningchen** [comment]
比如哪道道题？

**Comment by boomzero** [comment]
http://www.xmoj.tech/problem.php?id=4210

**Comment by boomzero** [comment]
@langningchen

**Comment by langningchen** [comment]
但是即使样例不一样，但是也不影响输入输出结果啊

**Comment by boomzero** [comment]
> 但是即使样例不一样，但是也不影响输出结果啊

不是啊,xiaoming 和 gaolaoshi 长度不同

**Comment by langningchen** [comment]
额，好吧

**Comment by langningchen** [comment]
我那个是全局 HTML 替换，所以要加特判有些困难
