### ISSUE TITLE
[Bug] CI/CD breaks when the pr title contains '

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#344]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

rt

**Comment by langningchen** [comment]
有人有解决方案吗？@boomzero @PythonSmall-Q

**Comment by boomzero** [comment]
@langningchen 目测是 ' 影响json格式

**Comment by langningchen** [comment]
@boomzero 不是，是命令行拼接的问题

**Comment by langningchen** [comment]
https://github.com/langningchen/XMOJ-Script/blob/77bbc37a029cb192a01cc6e096529791d3450115/.github/workflows/UpdateVersion.yml#L20

**Comment by langningchen** [comment]
JSON肯定没问题，JS的JSON库不会出现问题的

**Comment by langningchen** [comment]
#402

**Comment by langningchen** [comment]
你应该能看到错误日志

https://github.com/langningchen/XMOJ-Script/actions/runs/6171607602/job/16750190070#step:3:1

**Comment by langningchen** [comment]
```log
2023-09-13T11:07:01.1778581Z ##[group]Run node ./Update/UpdateVersion.js *** 402 "test #344 ""
2023-09-13T11:07:01.1840731Z ##[endgroup]
2023-09-13T11:07:01.2010536Z /home/runner/work/_temp/8377dfd7-f465-451e-a776-dac2fb50a18b.sh: line 1: unexpected EOF while looking for matching `"'
```

**Comment by langningchen** [comment]
他之前的命令行是
```bash
node ./Update/UpdateVersion.js *** 402 "test #344 ""
```
所以就会出错

**Comment by langningchen** [comment]
这样就是会导致双引号有多余的，没有被结束

**Comment by langningchen** [comment]
看到错误信息的意思也是在寻找后双引号的时候命令结束

**Comment by langningchen** [comment]
无法实现
