### ISSUE TITLE
[Bug] 更新日志不全

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#346]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

rt, 只有pr title的第一个单词

**Comment by langningchen** [comment]
Fixed
