### ISSUE TITLE
[Feature Request] 讨论回复时用md引用功能

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#363]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt, 和github quote this reply差不多

**Comment by langningchen** [comment]
我使用的MarkDown解析器不支持解析引用 `>`

**Comment by langningchen** [comment]
https://github.com/markedjs/marked

**Comment by boomzero** [comment]
@langningchen 支持啊

**Comment by boomzero** [comment]
https://marked.js.org/demo/?text=Marked%20-%20Markdown%20Parser%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0A%5BMarked%5D%20lets%20you%20convert%20%5BMarkdown%5D%20into%20HTML.%20%20Markdown%20is%20a%20simple%20text%20format%20whose%20goal%20is%20to%20be%20very%20easy%20to%20read%20and%20write%2C%20even%20when%20not%20converted%20to%20HTML.%20%20This%20demo%20page%20will%20let%20you%20type%20anything%20you%20like%20and%20see%20how%20it%20gets%20converted.%20%20Live.%20%20No%20more%20waiting%20around.%0A%3E%201%0A%3E%201%0A%3E%3E%202%0A%0AHow%20To%20Use%20The%20Demo%0A-------------------%0A%0A1.%20Type%20in%20stuff%20on%20the%20left.%0A2.%20See%20the%20live%20updates%20on%20the%20right.%0A%0AThat%27s%20it.%20%20Pretty%20simple.%20%20There%27s%20also%20a%20drop-down%20option%20above%20to%20switch%20between%20various%20views%3A%0A%0A-%20**Preview%3A**%20%20A%20live%20display%20of%20the%20generated%20HTML%20as%20it%20would%20render%20in%20a%20browser.%0A-%20**HTML%20Source%3A**%20%20The%20generated%20HTML%20before%20your%20browser%20makes%20it%20pretty.%0A-%20**Lexer%20Data%3A**%20%20What%20%5Bmarked%5D%20uses%20internally%2C%20in%20case%20you%20like%20gory%20stuff%20like%20this.%0A-%20**Quick%20Reference%3A**%20%20A%20brief%20run-down%20of%20how%20to%20format%20things%20using%20markdown.%0A%0AWhy%20Markdown%3F%0A-------------%0A%0AIt%27s%20easy.%20%20It%27s%20not%20overly%20bloated%2C%20unlike%20HTML.%20%20Also%2C%20as%20the%20creator%20of%20%5Bmarkdown%5D%20says%2C%0A%0A%3E%20The%20overriding%20design%20goal%20for%20Markdown%27s%0A%3E%20formatting%20syntax%20is%20to%20make%20it%20as%20readable%0A%3E%20as%20possible.%20The%20idea%20is%20that%20a%0A%3E%20Markdown-formatted%20document%20should%20be%0A%3E%20publishable%20as-is%2C%20as%20plain%20text%2C%20without%0A%3E%20looking%20like%20it%27s%20been%20marked%20up%20with%20tags%0A%3E%20or%20formatting%20instructions.%0A%0AReady%20to%20start%20writing%3F%20%20Either%20start%20changing%20stuff%20on%20the%20left%20or%0A%5Bclear%20everything%5D(%2Fdemo%2F%3Ftext%3D)%20with%20a%20simple%20click.%0A%0A%5BMarked%5D%3A%20https%3A%2F%2Fgithub.com%2Fmarkedjs%2Fmarked%2F%0A%5BMarkdown%5D%3A%20http%3A%2F%2Fdaringfireball.net%2Fprojects%2Fmarkdown%2F%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=9.0.0

**Comment by langningchen** [comment]
啊？呃

**Comment by langningchen** [comment]
好吧

**Comment by langningchen** [comment]
@boomzero 看一下[这里](http://www.xmoj.tech/discuss3/thread.php?tid=265)

**Comment by langningchen** [comment]
@boomzero 我知道了，我用的是 `4.3.0` 的 `marked` ，最新版本是 `9.0.0`

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q `bootcdn` 没有更新，最新版的 `marked` 也只到了 `4.3.0` ，所以准备换用 `cdnjs.cloudflare.com` ，不过这个也很慢

**Comment by PythonSmall-Q** [comment]
那用我的那个cdn吧

**Comment by langningchen** [comment]
> 那用我的那个cdn吧

哪个？是那个 https://github.com/PythonSmall-Q/CDN + 你的Githubproxy ？

**Comment by langningchen** [comment]
@PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
直接githubdown1.eu.org/用户/仓库/file。我那个cdn不会动态更新

**Comment by langningchen** [comment]
好吧

**Comment by PythonSmall-Q** [comment]
用release会更快

**Comment by PythonSmall-Q** [comment]
cdn的cache时间是48hour

**Comment by langningchen** [comment]
好的

**Comment by langningchen** [comment]
@PythonSmall-Q 要么你帮我找一个 marked 的地址，他的 Release 里面没有 JS ~我懒得找~

**Comment by PythonSmall-Q** [comment]
https://cdn.jsdelivr.net/npm/marked/marked.min.js 这个是吗？ @langningchen

**Comment by langningchen** [comment]
对的 @PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
@langningchen  https://githubdown1.eu.org/https://github.com/PythonSmall-Q/CDN/releases/download/marked/marked.min.js

**Comment by langningchen** [comment]
谢谢！

**Comment by langningchen** [comment]
不过你这个也没法同步更新……

**Comment by PythonSmall-Q** [comment]
别用的太频繁，然后看看 https://seanproxy1.statuspage.io

**Comment by PythonSmall-Q** [comment]
> 不过你这个也没法同步更新……

你要让我更新就更新，或者我给你一个collaberator

**Comment by langningchen** [comment]
> 别用的太频繁

这个你得看同学们脚本的使用情况

**Comment by PythonSmall-Q** [comment]
不多吧

**Comment by PythonSmall-Q** [comment]
服务器有的时候会炸

**Comment by langningchen** [comment]
> 服务器有的时候会炸

频率不高就好

**Comment by langningchen** [comment]
啊啊啊！我明白了，不是 JS 版本的问题，而是我把 <kbd>></kbd> 变成了 <kbd>&gt</kbd> ，所以导致引用失败！
