### ISSUE TITLE
[Bug] 关于actions

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#367]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

为什么https://github.com/langningchen/XMOJ-Script/commit/54ee1a8f1a882c75bd380353b5c6bbabd6d05764

github actions自动commit 到dev?????

**Comment by langningchen** [comment]
你说的是 #366 吗？

**Comment by boomzero** [comment]
yes

**Comment by langningchen** [comment]
> yes

我明白了，这是因为你往master分支上提交了pull
 request，我默认认为你的per是从dev分支上提交的，但是并不是

**Comment by langningchen** [comment]
这个东西的原理就是这样的：如果你从dev分支往master分支上提交了PR，就会自动更新版本号为发布状态，而不是预览。尽管我有一个自动化检查是否是dev分支上提交来的，但是他和自动化发布是同一优先级的，所以就导致PR还没被关掉，这个就已经把代码提交到dev分支了

**Comment by langningchen** [comment]
所以最好的解决方法是在自动更新脚本之前检查是否是dev分支来的。如果不是就不更新为发布状态，如果是再更新
