### ISSUE TITLE
[Bug] OI赛制下状态页无限刷新

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#375]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

rt, 因为判题机一直是local

### 重现步骤

去http://www.xmoj.tech/contest.php?cid=6419
交一题

**Comment by langningchen** [comment]
为什么一直是LOCAL

**Comment by boomzero** [comment]
OI赛制...

**Comment by langningchen** [comment]
呃，好吧

**Comment by boomzero** [comment]
@langningchen 你能发布一个东西测试一下 #370 吗

**Comment by langningchen** [comment]
@PythonSmall-Q @boomzero 要么就撤销 #124 #186 ？
