### ISSUE TITLE
[Feature Request] 更换预编译接口加快预编译速度

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#376]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

### 原因

因为只有在OI赛制下才有用, 不然很浪费时间

**Comment by PythonSmall-Q** [comment]
哈？

**Comment by PythonSmall-Q** [comment]
ACM不能与编译码？

**Comment by PythonSmall-Q** [comment]
其实小明的OI赛制是没有tag的。个人认为无法实现

**Comment by PythonSmall-Q** [comment]
@langningchen 你看看

**Comment by boomzero** [comment]
@PythonSmall-Q 可以爬contestrank-oi.php吧

**Comment by langningchen** [comment]
> 其实小明的OI赛制是没有tag的。个人认为无法实现

@PythonSmall-Q ？没明白

**Comment by langningchen** [comment]
@boomzero 为什么会很浪费时间？

**Comment by langningchen** [comment]
要么就把预编译去掉

**Comment by boomzero** [comment]
> 要么就把预编译去掉

不要啊

**Comment by langningchen** [comment]
这个预编译好像没啥用

**Comment by boomzero** [comment]
http://www.xmoj.tech/ceinfo.php?sid=776420

**Comment by boomzero** [comment]
我赛时交的代码...

**Comment by boomzero** [comment]
去掉l就ac了

**Comment by langningchen** [comment]
好吧

**Comment by PythonSmall-Q** [comment]
> @PythonSmall-Q 可以爬contestrank-oi.php吧

OI赛制就是赛时无法查看，理论可行 @langningchen

**Comment by PythonSmall-Q** [comment]
我之前搞错了

**Comment by langningchen** [comment]
> > @PythonSmall-Q 可以爬contestrank-oi.php吧
> 
> OI赛制就是赛时无法查看，理论可行 @langningchen

什么理论可行？

**Comment by langningchen** [comment]
@boomzero 你理解 @PythonSmall-Q 的意思吗？

**Comment by PythonSmall-Q** [comment]
OI赛制的rank赛时不可查看

**Comment by PythonSmall-Q** [comment]
@langningchen

**Comment by langningchen** [comment]
@PythonSmall-Q 为什么理论可行？你认为可以怎么看到？

**Comment by boomzero** [comment]
> OI赛制的rank赛时会显示不可查看

**Comment by langningchen** [comment]
@boomzero 确实不可查看啊，我就说`你认为可以怎么看到？`

**Comment by PythonSmall-Q** [comment]
看不了的。xmoj本身的feature

**Comment by langningchen** [comment]
所以我就很奇怪你们在讨论一些什么 @PythonSmall-Q @boomzero

**Comment by langningchen** [comment]
所以这个 Issue 怎么解决？

**Comment by boomzero** [comment]
> 所以我就很奇怪你们在讨论一些什么 @PythonSmall-Q @boomzero

爬oiranking, 如果无法查看说明是oi赛,就预编译

**Comment by langningchen** [comment]
哦，好吧

**Comment by langningchen** [comment]
@boomzero 你在线，看看 http://www.xmoj.tech/discuss3/thread.php?tid=265 是不是被我 XSS 了

**Comment by PythonSmall-Q** [comment]
你干了个啥？

**Comment by PythonSmall-Q** [comment]
那个iframe出不来

**Comment by PythonSmall-Q** [comment]
@langningchen

**Comment by boomzero** [comment]
没有

**Comment by boomzero** [comment]
我的script alert不了

**Comment by boomzero** [comment]
说句闲话, 这是什么鬼?
ping:
```
92 bytes from 192.168.1.1 (192.168.1.1): Communication prohibited by filter
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 80a7   0 0000  3f  01 2e44 192.168.10.20  1.1.1.1 

```

**Comment by langningchen** [comment]
> 那个iframe出不来

当然了，因为安全考虑

**Comment by langningchen** [comment]
只有你用旧版本的脚本，才能出来 @PythonSmall-Q

**Comment by boomzero** [comment]
@langningchen 内嵌html不行吗?

**Comment by langningchen** [comment]
> @langningchen 内嵌html不行吗?

怎么不行？

**Comment by langningchen** [comment]
@PythonSmall-Q https://github.github.com/gfm/#disallowed-raw-html-extension-

**Comment by langningchen** [comment]
原来我的过滤在后端，现在转移到前端了

**Comment by boomzero** [comment]
> 说句闲话, 这是什么鬼? ping:
> 
> ```
> 92 bytes from 192.168.1.1 (192.168.1.1): Communication prohibited by filter
> Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
>  4  5  00 5400 80a7   0 0000  3f  01 2e44 192.168.10.20  1.1.1.1 
> ```

移动网炸了, 好评

**Comment by PythonSmall-Q** [comment]
6666

**Comment by PythonSmall-Q** [comment]
我觉得只有OI预编译这件事其实没有啥必要。毕竟平时也需要预编译（特别是我 @langningchen @boomzero

**Comment by langningchen** [comment]
所以我觉得最好的解决方案是找一个更快的预编译接口 @boomzero @PythonSmall-Q

**Comment by langningchen** [comment]
因为我现在这个接口是在国外的，所以可能比较慢

**Comment by boomzero** [comment]
> 我觉得只有OI预编译这件事其实没有啥必要。毕竟平时也需要预编译（特别是我 @langningchen @boomzero

平时不能直接交吗

**Comment by langningchen** [comment]
> > 我觉得只有OI预编译这件事其实没有啥必要。毕竟平时也需要预编译（特别是我 @langningchen @boomzero
> 
> 平时不能直接交吗

@boomzero 他说他平时也会交CE的代码

**Comment by boomzero** [comment]
> > > 我觉得只有OI预编译这件事其实没有啥必要。毕竟平时也需要预编译（特别是我 @langningchen @boomzero
> > 
> > 
> > 平时不能直接交吗
> 
> @boomzero 他说他平时也会交CE的代码

?

**Comment by boomzero** [comment]
> > > > 我觉得只有OI预编译这件事其实没有啥必要。毕竟平时也需要预编译（特别是我 @langningchen @boomzero
> > > 
> > > 
> > > 平时不能直接交吗
> > 
> > 
> > @boomzero 他说他平时也会交CE的代码
> 
> ?

那为什么要预编译.

**Comment by langningchen** [comment]
> 那为什么要预编译.

就是防止交上去CE的代码降低AC率

**Comment by langningchen** [comment]
@boomzero

**Comment by langningchen** [comment]
@boomzero 所以没问题了吧

**Comment by langningchen** [comment]
我可以更换预编译接口

**Comment by langningchen** [comment]
/-investigating /working-on-it

**Comment by langningchen** [comment]
/-working-on-it @boomzero 你试试，应该快一些了
