### ISSUE TITLE
[Bug] Prerelease 炸了

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#385]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

asset没传

**Comment by langningchen** [comment]
@boomzero 有吗？我看着挺正常的啊
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/cdcf9c64-db2f-4797-ab93-17feec031fa9)

**Comment by boomzero** [comment]
但是没传release asset

**Comment by boomzero** [comment]
去release页面看

**Comment by langningchen** [comment]
@boomzero 传了啊

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/ad9b1603-cf12-40f5-b755-263f045e8573)

**Comment by PythonSmall-Q** [comment]
确实

**Comment by boomzero** [comment]
> @boomzero 传了啊
> 
> ![image](https://user-images.githubusercontent.com/81672884/266821762-ad9b1603-cf12-40f5-b755-263f045e8573.png)

点开

**Comment by boomzero** [comment]
@langningchen

**Comment by langningchen** [comment]
@boomzero 哦，好的

**Comment by langningchen** [comment]
@boomzero 这是因为你的 #364 改的

**Comment by boomzero** [comment]
> @boomzero 这是因为你的 #364 改的

...

**Comment by boomzero** [comment]
#367 搞的...

**Comment by langningchen** [comment]
是吗？不是吧……？

**Comment by langningchen** [comment]
@boomzero 你仔细看看 https://github.com/softprops/action-gh-release/tree/v1/

**Comment by langningchen** [comment]
应该是这样写

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/501a7c42-d8be-4b1c-8704-5bc36f3065b5)
