### ISSUE TITLE
[Feature Request] 使用相对时间

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#387]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

使用相对时间，比如“一分钟前”，如果鼠标悬停再显示详细时间

### 原因

详细时间太占空间了

**Comment by langningchen** [comment]
@boomzero 我为什么变成了新人……？

**Comment by PythonSmall-Q** [comment]
666666
