### ISSUE TITLE
[Feature Request] 增加lock功能

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#389]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

增加lock功能

**Comment by PythonSmall-Q** [comment]
数据库我加了，要不你做一下前后端。cf的api不会用……你写的script的异步没看懂…… @langningchen

**Comment by langningchen** [comment]
@PythonSmall-Q 我觉得我写的TS挺简单的啊

**Comment by PythonSmall-Q** [comment]
本傻狗摆了

**Comment by PythonSmall-Q** [comment]
我除了c++什么都不会

**Comment by langningchen** [comment]
Emm

**Comment by PythonSmall-Q** [comment]
em现在不是没人再做吗

**Comment by langningchen** [comment]
我可能得等到下周末才有空做了

**Comment by boomzero** [comment]
> @PythonSmall-Q 我觉得我写的TS挺简单的啊

ts 好难, 我只会js...

**Comment by boomzero** [comment]
主要是type, 很烦

**Comment by langningchen** [comment]
@boomzero  TS和C++一样，对于类型要求严格

**Comment by langningchen** [comment]
@PythonSmall-Q 你干嘛……哎呦 我刚把lock写好，本来想Close一个Issue，结果又要标签分类……

**Comment by langningchen** [comment]
不干了！

**Comment by langningchen** [comment]
真实的，气得我多打了一个 <kbd>[</kbd>

**Comment by langningchen** [comment]
@PythonSmall-Q @boomzero 如果你们想要看到锁定后的效果，把你们从 `XMOJ.user.js` 的 `AdminUserList` 中去掉
