### ISSUE TITLE
[Feature request]建议将后端移至Cloudflare D1 + workers

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#39]
### Discussed in https://github.com/langningchen/XMOJ-Script/discussions/38

<div type='discussions-op-text'>

<sup>Originally posted by **boomzero** August 15, 2023</sup>
目前后端不太稳定.
 但是这样要全部重写 server, 我有空可以写一下</div>

**Comment by boomzero** [comment]
@langningchen

**Comment by boomzero** [comment]
...

**Comment by PythonSmall-Q** [comment]
emm cloudflare workers中国上不去哦
就是那个workers.dev的网站

**Comment by boomzero** [comment]
… www.xmoj-bbs.tech

**Comment by boomzero** [comment]
> emm cloudflare workers中国上不去哦 就是那个workers.dev的网站

~为什么你是凌晨发的~

**Comment by boomzero** [comment]
> … [www.xmoj-bbs.tech](http://www.xmoj-bbs.tech) @PythonSmall-Q

有自定义域名的

**Comment by langningchen** [comment]
> emm cloudflare workers中国上不去哦
> 就是那个workers.dev的网站

怎么样？我自己注册的域名

**Comment by boomzero** [comment]
@langningchen 你可以把现在的后台也改一个域名

**Comment by langningchen** [comment]
解决了大问题！如果对于新版本的讨论有问题，欢迎提出新的Issue！

**Comment by langningchen** [comment]
新版本已经发布
