### ISSUE TITLE
[Bug]速率限制不合理

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#393]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/8a0e2b64-ec07-4dbe-ab0e-c88f0d1bde4b)
速率限制不合理
会ban掉一些合理的访问

**Comment by PythonSmall-Q** [comment]
我们讨论一下要不重新设置速率限制

**Comment by PythonSmall-Q** [comment]
@langningchen @boomzero

**Comment by PythonSmall-Q** [comment]
他连续几十个都被ban了

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/12f90403-8a68-4cc5-95d5-50a9c6eef738)
正常的request

**Comment by langningchen** [comment]
嗯，确实

**Comment by langningchen** [comment]
我也有时候动不动就被ban

**Comment by PythonSmall-Q** [comment]
我觉得改成50左右会好点

**Comment by PythonSmall-Q** [comment]
我去改了

**Comment by langningchen** [comment]
> 我觉得改成50左右会好点

什么50？每10秒钟50次吗？

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/17338457-e460-4ecf-8e52-5c951632d5bb)

**Comment by PythonSmall-Q** [comment]
我目前不会高频率炸了

Sent from Mail for Windows

**Comment by langningchen** [comment]
好的
