### ISSUE TITLE
[Bug] Release 发布的tag有误

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#397]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

https://github.com/langningchen/XMOJ-Script/compare/0.3.147...0.3.148

没有变化

tag是基于master的

**Comment by boomzero** [comment]
因此, release notes 有误

**Comment by boomzero** [comment]
?

**Comment by langningchen** [comment]
@boomzero 不就是只有那一次出错了吗？后面就没问题了啊

**Comment by boomzero** [comment]
> @boomzero 不就是只有那一次出错了吗？后面就没问题了啊

@langningchen 没fix啊

**Comment by langningchen** [comment]
@boomzero 应该没问题了，如果还不行，重开Issue
