### ISSUE TITLE
[Feature Request] 编辑回复时提供预览

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#398]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

**Comment by langningchen** [comment]
这个不是已经实现了吗？

**Comment by boomzero** [comment]
没有啊

**Comment by boomzero** [comment]
就是使用edit reply

**Comment by langningchen** [comment]
哦，好的

**Comment by boomzero** [comment]
@langningchen `This issue or pull request changes the main user script` 是什么鬼
~issue怎么change main userscript~

**Comment by langningchen** [comment]
@boomzero 意思就是说解决这个Issue需要更改用户脚本。

**Comment by langningchen** [comment]
语义可能不太准确

**Comment by boomzero** [comment]
@langningchen edited
