### ISSUE TITLE
[Bug] 编辑时有时候自动跳掉

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#399]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

rt

### 重现步骤

1. 点开编辑
2. 在浏览器中打开其他标签页
3. 回到xmoj标签页
4. 再试图编辑

**Comment by boomzero** [comment]
<marquee style="margin-top:10px" id="broadcast" scrollamount="1" scrolldelay="50" class="toprow">快乐学习，认真刷题，努力进步！
</marquee>

**Comment by boomzero** [comment]
@langningchen any ideas?

**Comment by langningchen** [comment]
知道问题
