### ISSUE TITLE
[Bug] 比赛状态页status.php?cid=无法上传std

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#400]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

rt

**Comment by boomzero** [comment]
庆祝 #400 🎉

**Comment by langningchen** [comment]
好的

**Comment by boomzero** [comment]
@langningchen review needed?

**Comment by langningchen** [comment]
@boomzero 因为我还没有仔细看具体的原因

**Comment by langningchen** [comment]
/-investigating
