### ISSUE TITLE
[Feature Request] join hacktoberfest

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#401]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

@langningchen 加一下 hacktoberfest topic

https://hacktoberfest.com/participation/#maintainers

### 原因

~可以吸引人贡献~

**Comment by boomzero** [comment]
~我好像可以骗到4个pr~

**Comment by langningchen** [comment]
hacktoberfest 是什么？

**Comment by langningchen** [comment]
为什么需要更多人贡献？他们又没法访问xmoj

**Comment by boomzero** [comment]
> 为什么需要更多人贡献？他们又没法访问xmoj

后端+actions

**Comment by boomzero** [comment]
@langningchen ~你为什么中午12点comment~

**Comment by boomzero** [comment]
> > 为什么需要更多人贡献？他们又没法访问xmoj
> 
> 后端+actions

后端就是一个ts forum

**Comment by langningchen** [comment]
> @langningchen ~你为什么中午12点comment~

我在学校看的，午休的时间

**Comment by langningchen** [comment]
> > 为什么需要更多人贡献？他们又没法访问xmoj
> 
> 后端+actions

我觉得没必要吧，因为毕竟我的Actions写的不是很成熟，所以他们在其他仓库往我们仓库PR的时候会出各种古怪的问题

**Comment by boomzero** [comment]
> > > 为什么需要更多人贡献？他们又没法访问xmoj
> > 
> > 
> > 后端+actions
> 
> 所以他们在其他仓库往我们仓库PR的时候会出各种古怪的问题

没事

**Comment by boomzero** [comment]
> > > 为什么需要更多人贡献？他们又没法访问xmoj
> > 
> > 
> > 后端+actions
> 
> 我觉得没必要吧，因为毕竟我的Actions写的不是很成熟，所以他们在其他仓库往我们仓库PR的时候会出各种古怪的问题

加一下不行吗

**Comment by boomzero** [comment]
> > @langningchen ~你为什么中午12点comment~
> 
> 我在学校看的，午休的时间

你们班可以动电脑?

**Comment by boomzero** [comment]
> > > @langningchen ~你为什么中午12点comment~
> > 
> > 
> > 我在学校看的，午休的时间
> 
> 你们班可以动电脑?

~我们动电脑会死~

**Comment by boomzero** [comment]
> > > > @langningchen ~你为什么中午12点comment~
> > > 
> > > 
> > > 我在学校看的，午休的时间
> > 
> > 
> > 你们班可以动电脑?
> 
> ~我们动电脑会死~

~虽然我知道副校长网络管理系统的密码~

**Comment by langningchen** [comment]
> ~我们动电脑会死~

为什么？

**Comment by langningchen** [comment]
> ~虽然我知道副校长网络管理系统的密码~

怎么知道的？弱密码还是注入？

**Comment by langningchen** [comment]
> 加一下不行吗

可以

**Comment by langningchen** [comment]
@boomzero

**Comment by boomzero** [comment]
> > ~虽然我知道副校长网络管理系统的密码~
> 
> 怎么知道的？弱密码还是注入？

他告诉我了

**Comment by boomzero** [comment]
> > ~我们动电脑会死~
> 
> 为什么？

会被班主任骂

**Comment by boomzero** [comment]
> > > > > @langningchen ~你为什么中午12点comment~
> > > > 
> > > > 
> > > > 我在学校看的，午休的时间
> > > 
> > > 
> > > 你们班可以动电脑?
> > 
> > 
> > ~我们动电脑会死~
> 
> ~虽然我知道副校长网络管理系统的密码~

~每次登陆我都忍不住点一下`工资收入查询`~

**Comment by boomzero** [comment]
> > ~虽然我知道副校长网络管理系统的密码~
> 
> 怎么知道的？弱密码还是注入？

~我回头试一下SQL, 应该可以~

**Comment by boomzero** [comment]
> > > ~虽然我知道副校长网络管理系统的密码~
> > 
> > 
> > 怎么知道的？弱密码还是注入？
> 
> ~我回头试一下SQL, 应该可以~

我们学校IT垃圾到在线选课系统都是用的系统时间, 所以我直接改时间抢课

**Comment by boomzero** [comment]
> > > ~虽然我知道副校长网络管理系统的密码~
> > 
> > 
> > 怎么知道的？弱密码还是注入？
> 
> ~我回头试一下SQL, 应该可以~

但是外网上不去

**Comment by boomzero** [comment]
他的密码确实挺弱的, 就是他的手机号加上**(不能说,不然会死)

**Comment by boomzero** [comment]
@langningchen 加了吗

**Comment by langningchen** [comment]
> @langningchen 加了吗
> 

等周末

**Comment by boomzero** [comment]
> > @langningchen 加了吗
> 
> 等周末

就一个tag啊

**Comment by langningchen** [comment]
> 我们学校IT垃圾到在线选课系统都是用的系统时间, 所以我直接改时间抢课

~你什么学校~

**Comment by boomzero** [comment]
> > @langningchen 加了吗
> 
> 等周末

就一个tag啊0

> > 我们学校IT垃圾到在线选课系统都是用的系统时间, 所以我直接改时间抢课
> 
> ~你什么学校~

https://www.smfms.cn/2018/

**Comment by langningchen** [comment]
@boomzero 应该可以了
