### ISSUE TITLE
[Feature Request] 减少XMOJ服务器负担

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#403]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

在我的服务器上缓存有效的PHPSESSID

**Comment by boomzero** [comment]
你这...~~直接反手复制~~

**Comment by PythonSmall-Q** [comment]
666《安全问题》

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q 应该没什么问题

**Comment by boomzero** [comment]
> @boomzero @PythonSmall-Q 应该没什么问题

会有token重复吗

**Comment by langningchen** [comment]
> 会有token重复吗

应该没问题吧

**Comment by langningchen** [comment]
@boomzero

**Comment by PythonSmall-Q** [comment]
token我觉得大概率不重复
