### ISSUE TITLE
[Bug] 安装链接失效

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#405]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/ff3d046b-e2fa-4287-b7ce-db122df31615)

### 重现步骤

在TM里面实用工具从URL安装

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/ba93f07f-aa01-42ca-a677-73bebe0d4b82)
处得来的

**Comment by langningchen** [comment]
好吧，那就是我的浏览器的问题
