### ISSUE TITLE
[Feature Request] dismiss notifications

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#406]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

**Comment by boomzero** [comment]
@langningchen 可以merge dev了吗

**Comment by langningchen** [comment]
@boomzero 为什么你总是这么着急merge dev……

**Comment by PythonSmall-Q** [comment]
因为已经一周没发布了

**Comment by langningchen** [comment]
额

**Comment by langningchen** [comment]
你把那些提醒全都查看不就好了吗？ @boomzero

**Comment by boomzero** [comment]
> 你把那些提醒全都查看不就好了吗？ @boomzero

?

**Comment by langningchen** [comment]
@boomzero 就是点击查看按钮，然后设为已读

**Comment by boomzero** [comment]
> @boomzero 就是点击查看按钮，然后设为已读

提醒太多了, 一个一个点有点烦

**Comment by langningchen** [comment]
@boomzero 你就读一下不行吗？反正到时候也会读的

**Comment by langningchen** [comment]
要么加一个功能叫 "dismiss" ，你可以写 Feature Request

**Comment by langningchen** [comment]
/-needs-triage /good-first-issue /working-on-it
