### ISSUE TITLE
[Bug] live playback will play two seperate streams of audio

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#41]
@langningchen 
How to reproduce:
1. Go to a live playback page like http://www.xmoj.tech/contest_video.php?cid=6255
2. Play it with this script enabled

**Comment by langningchen** [comment]
这个我知道，但是和 #26 一样是加载顺序的问题，不太好修

**Comment by langningchen** [comment]
我再试一试能不能修

**Comment by langningchen** [comment]
@boomzero

**Comment by boomzero** [comment]
Can you reopen this?

**Comment by langningchen** [comment]
Oh, I forgot it

**Comment by boomzero** [comment]
> Oh, I forgot it

thx

**Comment by langningchen** [comment]
Err... It's tricky

**Comment by langningchen** [comment]
有点奇怪

**Comment by langningchen** [comment]
@boomzero 我都把HTML元素删光了但是还在响 😕 

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/c95254b1-44b8-4df5-bfaa-ceeb06b60d60)

**Comment by boomzero** [comment]
> @boomzero 我都把HTML元素删光了但是还在响 😕
> 
> ![image](https://user-images.githubusercontent.com/81672884/262541941-c95254b1-44b8-4df5-bfaa-ceeb06b60d60.png)

!

**Comment by boomzero** [comment]
javascript?

**Comment by langningchen** [comment]
有可能

**Comment by langningchen** [comment]
散了，还是不改了吧

**Comment by boomzero** [comment]
...

**Comment by boomzero** [comment]
Than can you fix https://github.com/langningchen/XMOJ-Script/issues/45

**Comment by langningchen** [comment]
> Then can you fix #45

https://github.com/langningchen/XMOJ-Script/issues/45#issuecomment-1689199576

**Comment by boomzero** [comment]
@langningchen 我知道了, 原来的video框 autoplay, 被你替换后声音还在

**Comment by langningchen** [comment]
有道理，但是怎么把声音去掉呢？我只是把他的video框清空了而已

**Comment by boomzero** [comment]
@langningchen 看一下https://greasyfork.org/en/scripts/8022-disable-audio-video-autoplay/code

**Comment by boomzero** [comment]
确实奇怪...

**Comment by boomzero** [comment]
![](https://github.com/langningchen/XMOJ-Script/assets/85378277/d2b325b8-d8cc-4406-9960-a919e48ecbb2)

...

**Comment by boomzero** [comment]
done

**Comment by boomzero** [comment]
@langningchen Please review

**Comment by langningchen** [comment]
@boomzero Please solve the conversation
