### ISSUE TITLE
[Bug]我的badge没了qwq

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#415]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/221ee41a-28d5-4c52-a139-e901f072bb59)
为什么我的badge不见了，你们看的见吗？

**Comment by PythonSmall-Q** [comment]
救命

**Comment by langningchen** [comment]
@PythonSmall-Q 

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/e5588d52-5d5b-499e-b357-de5d9285c659)

**Comment by langningchen** [comment]
你是不是随意修改了数据 `localStorage` ？你可以尝试重置用户脚本数据

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/a1539f49-45ff-4517-b8be-cb577df5a991)

@PythonSmall-Q
