### ISSUE TITLE
[Bug] at出错

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#422]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/d2c5869f-79b6-4a87-91c6-b43dccf57e3c)
为什么@会出来的是html？？？

**Comment by PythonSmall-Q** [comment]
无论怎么改只有我错的

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/6f743820-1ba5-4706-8b83-6412df4d5dd2)
现在是这个样子的

**Comment by langningchen** [comment]
是我的正则写错了

**Comment by langningchen** [comment]
/-investigating
