### ISSUE TITLE
[Feature Request] 将API放置于新的域名

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#428]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

不使用 `www.xmoj-bbs.tech` ，而是  `api.xmoj-bbs.tech`

**Comment by boomzero** [comment]
...

**Comment by boomzero** [comment]
向前兼容啊

**Comment by boomzero** [comment]
不然老版本会炸

**Comment by langningchen** [comment]
@boomzero 当然兼容

**Comment by langningchen** [comment]
我那个旧的www先不删
