### ISSUE TITLE
[Feature request] Add captcha

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#43]
...
http://www.xmoj.tech/discuss3/thread.php?tid=221

**Comment by langningchen** [comment]
不能用fetch或者new XMLHttpRequest

**Comment by langningchen** [comment]
这样会被跨域阻止

**Comment by boomzero** [comment]
我用的<script>

**Comment by langningchen** [comment]
如果你用了`mode: no-cors`，那么就得不到返回体

**Comment by langningchen** [comment]
要用 `GM_xmlhttpRequest` ，然后用 `eval`

**Comment by boomzero** [comment]
除非把他的script复制下来

**Comment by langningchen** [comment]
~~另外，我让你把`鬼替换`提Issue，不是这个Captcha~~

**Comment by boomzero** [comment]
> ~另外，我让你把`鬼替换`提Issue，不是这个Captcha~

...

**Comment by langningchen** [comment]
> 放在html里

哪个HTML里面？

**Comment by boomzero** [comment]
那不是防止SQL injection的吗

**Comment by langningchen** [comment]
> 那不是防止SQL injection的吗

？哪个是防止SQL的？

**Comment by boomzero** [comment]
> > 那不是防止SQL injection的吗
> 
> ？哪个是防止SQL的？

替换

**Comment by langningchen** [comment]
哦，是的

**Comment by langningchen** [comment]
那个不叫SQL注入，叫HTML注入

**Comment by langningchen** [comment]
再说你也不用提Issue了，我已经修好了

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/31ecaf88-bb7a-49af-b805-6605c21f867d)

**Comment by boomzero** [comment]
> 那个不叫SQL注入，叫HTML注入

替换`"` 是防SQL的

**Comment by boomzero** [comment]
> 再说你也不用提Issue了，我已经修好了

thx

**Comment by langningchen** [comment]
> 替换`"` 是防SQL的

怎么能用替换？这个太不严谨了！一定要用prepare

**Comment by langningchen** [comment]
Captcha 我前端加进去了
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/39c6899a-c489-4f3f-8912-927ff43a1d29)

**Comment by boomzero** [comment]
Great!

**Comment by boomzero** [comment]
你能push一下吗, 我写backend

**Comment by boomzero** [comment]
> > 替换`"` 是防SQL的
> 
> 怎么能用替换？这个太不严谨了！一定要用prepare

~有没有可能原来xmoj没prepare (~

**Comment by boomzero** [comment]
@langningchen

**Comment by boomzero** [comment]
不过这样旧版本就会没发帖

**Comment by langningchen** [comment]
> 你能push一下吗, 我写backend

Backend我也写好了。

**Comment by langningchen** [comment]
> > > 替换`"` 是防SQL的
> > 
> > 怎么能用替换？这个太不严谨了！一定要用prepare
> 
> ~有没有可能原来xmoj没prepare (~

你说的是原来的xmoj还是原来的xmoj-script？

**Comment by langningchen** [comment]
> 哦对, 我在domain whitelist加了www.xmoj.tech
> 还有别的要whitelist的吗

没了吧

**Comment by langningchen** [comment]
> 哦对, 我在domain whitelist加了www.xmoj.tech
> 还有别的要whitelist的吗

没了吧？

**Comment by langningchen** [comment]
这几天我晚上六点以后都无法用电脑上线

**Comment by langningchen** [comment]
@boomzero 但是我现在想加了验证码会不会降低用户的体验程度？现在我只设置了在发帖和回复的时候要加验证码，编辑删除等都没有

**Comment by langningchen** [comment]
那个验证码每次发之前都要点一下，真的算挺麻烦，我觉得要么现在先注释掉，等到时候有人开始刷屏了再把它加上

**Comment by boomzero** [comment]
> 那个验证码每次发之前都要点一下，真的算挺麻烦，我觉得要么现在先注释掉，等到时候有人开始刷屏了再把它加上

但是我这里可以自动验证, ~说明他觉得你是bot~

**Comment by boomzero** [comment]
我可以设置让他可以自动验证, 不需要点一下

**Comment by boomzero** [comment]
> 那个验证码每次发之前都要点一下，真的算挺麻烦，我觉得要么现在先注释掉，等到时候有人开始刷屏了再把它加上

? 你等一下他会自动勾呀

**Comment by boomzero** [comment]
> 我可以设置让他可以自动验证, 不需要点一下

done

**Comment by boomzero** [comment]
> > > > 替换`"` 是防SQL的
> > > 
> > > 
> > > 怎么能用替换？这个太不严谨了！一定要用prepare
> > 
> > 
> > ~有没有可能原来xmoj没prepare (~
> 
> 你说的是原来的xmoj还是原来的xmoj-script？

xmoj

**Comment by langningchen** [comment]
> > 我可以设置让他可以自动验证, 不需要点一下
> 
> done

谢谢

**Comment by langningchen** [comment]
> xmoj

这是不可能的，因为xmoj使用的是开源的hustoj，而开源的项目这种低级的漏洞是不会出现，我阅读过hustoj的源码，他的安全性还是算可以的

**Comment by langningchen** [comment]
但是有的时候网络不好就会导致验证码加载不出来，这个可能就会造成一点问题

**Comment by boomzero** [comment]
> 但是有的时候网络不好就会导致验证码加载不出来，这个可能就会造成一点问题

~你连的是高老师的网吗~

**Comment by langningchen** [comment]
……

**Comment by langningchen** [comment]
已经发布
