### ISSUE TITLE
[Feature Request] 自己造图床

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#432]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

使用 GitHub 私有仓库 + Cloudflare Workers ，参考 [这篇](https://zhuanlan.zhihu.com/p/626135137) 文章

**Comment by boomzero** [comment]
@langningchen SEO修好了!

**Comment by PythonSmall-Q** [comment]
可以用团队的repo @langningchen  物尽其用

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q 你们到时候可别去 Cloudflare 后台偷我的 PAT 啊！不过我也只给 repo 权限 😆

**Comment by langningchen** [comment]
好麻烦啊！Workers流量的问题、GitHub权限的问题、JS前端事件触发的问题……让我不想继续了 /wontfix

**Comment by boomzero** [comment]
> 好麻烦啊！Workers流量的问题、GitHub权限的问题、JS前端事件触发的问题……让我不想继续了

考虑Cloudflare R2?

**Comment by boomzero** [comment]
但是没有credit card, 而且免费额度可能不够

**Comment by boomzero** [comment]
或者iframe 洛谷图床

**Comment by langningchen** [comment]
@boomzero 最主要的是JS前端事件触发的问题 /-wontfix /user-script

**Comment by langningchen** [comment]
@boomzero 帮我解决一下JS前端事件触发的问题 /help-wanted

**Comment by boomzero** [comment]
什么问题?

**Comment by langningchen** [comment]
@boomzero 就是按了 <kbd>Ctrl+V</kbd> 无法触发 `onpaste` 事件

**Comment by langningchen** [comment]
右键点粘贴也不行

**Comment by PythonSmall-Q** [comment]
这个actions太贴心了qaq

**Comment by PythonSmall-Q** [comment]
有点被他暖到（不是

**Comment by boomzero** [comment]
@langningchen 我没有code啊

**Comment by boomzero** [comment]
神奇

**Comment by boomzero** [comment]
~你有没有开奇妙插件~

**Comment by boomzero** [comment]
但是不需要onpaste吧

**Comment by langningchen** [comment]
@boomzero 你没有什么代码？就帮我在JS端实现<kbd>Ctrl+V</kbd>后获取到图片的Base64就好了

**Comment by boomzero** [comment]
> @boomzero 你没有什么代码？就帮我在JS端实现Ctrl+V后获取到图片的Base64就好了

~好高级, 不会~

**Comment by boomzero** [comment]
但是我不知道为什么需要

**Comment by boomzero** [comment]
@langningchen 直接
```html
<div class="mb-3">
  <label for="formFile" class="form-label">Default file input example</label>
  <input class="form-control" type="file" id="formFile">
</div>
```
不就行了吗

**Comment by langningchen** [comment]
文件选择上传？好吧

**Comment by PythonSmall-Q** [comment]
听起来不错

**Comment by langningchen** [comment]
不过我觉得还是直接 <kbd>Ctrl+V</kbd> 更方便，也不知道 Github 这个是怎么做的

**Comment by langningchen** [comment]
你们每次都去洛谷使用洛谷图床不烦吗？

**Comment by langningchen** [comment]
可以参考：
- https://github.githubassets.com/assets/app/assets/modules/github/upload/attachment-upload.ts
- https://github.githubassets.com/assets/app/assets/modules/github/upload/batch-upload.ts
- https://github.githubassets.com/assets/app/assets/modules/github/upload/batch.ts

**Comment by langningchen** [comment]
还有 https://github.githubassets.com/assets/node_modules/@github/file-attachment-element/dist/index.js 的 218 行：
```javascript
function onPaste(event) {
    if (!event.clipboardData)
        return;
    if (!event.clipboardData.items)
        return;
    const container = event.currentTarget;
    if (!(container instanceof FileAttachmentElement))
        return;
    const file = pastedFile(event.clipboardData.items);
    if (!file)
        return;
    const files = [file];
    container.attach(files);
    event.preventDefault();
}
```

**Comment by langningchen** [comment]
我好像明白了

**Comment by langningchen** [comment]
GitHub 太棒了！他提供TS，而且有注释，码风良好，不压行、不混淆！

**Comment by langningchen** [comment]
/-help-wanted /working-on-it 我再试试

**Comment by langningchen** [comment]
反复尝试发现 onpaste 还是不能再 XMOJ 界面生效，不知道为什么，所以我准备使用 onkeydown <kbd>Ctrl+V</kbd>

**Comment by langningchen** [comment]
呃呃呃，终于找到问题了

**Comment by langningchen** [comment]
> ~你有没有开奇妙插件~

真的被 @boomzero 说中了

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/cf672c7d-a745-441c-bc2b-447c43f278bb)

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/ffa31c46-957a-48e5-a1f5-8035cc82ac26)

中间终于有 ClipboardEvent 了

**Comment by langningchen** [comment]
Github 能用因为在他过滤黑名单里面

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/0a503f23-e217-4cf7-bd2a-c9c025bd0e6a)

**Comment by boomzero** [comment]
6

**Comment by langningchen** [comment]
又出现问题了，不知道为什么获取到的图片和原本的不一样，获取到的图片会被插入或修改一些内容 /help-wanted

一组实例：
- 正确：https://github.com/langningchen/XMOJ-Script/assets/81672884/6a454c56-f389-4d02-8938-463ee79bbf3d
- 错误：https://api.xmoj-bbs.tech/GetImage?ImageID=brpjzozoixntrwenzijdtgseldcosayh

对应实例，左图为正图片，右图错误图片
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/71149739-3d02-4bdb-9633-0cb922855389) 

@boomzero @PythonSmall-Q 能不能帮一下忙

**Comment by langningchen** [comment]
代码在对应的分支上

**Comment by langningchen** [comment]
上传图片的接口已经没问题了

**Comment by boomzero** [comment]
怎么用啊?

**Comment by boomzero** [comment]
复制不进去啊

**Comment by langningchen** [comment]
上传？粘贴后就上传了

**Comment by langningchen** [comment]
会在 Console 输出 ImageID

**Comment by langningchen** [comment]
注意你要用分支的代码

**Comment by langningchen** [comment]
你已经传了三张了

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/3cae5e5a-7580-42ca-aa6e-5ab66cf4cb42)

1 minute ago 的就是

**Comment by langningchen** [comment]
四张

**Comment by boomzero** [comment]
> 注意你要用分支的代码

.

**Comment by boomzero** [comment]
所以你没写使用图片的代码吗

**Comment by langningchen** [comment]
还在写后台

**Comment by langningchen** [comment]
https://api.xmoj-bbs.tech/GetImage?ImageID= + ImageID

例如：https://api.xmoj-bbs.tech/GetImage?ImageID=brpjzozoixntrwenzijdtgseldcosayh

**Comment by langningchen** [comment]
不过获取到的不太对

**Comment by langningchen** [comment]
我说过了：https://github.com/langningchen/XMOJ-Script/issues/432#issuecomment-1742081286

**Comment by langningchen** [comment]
我检查过， GitHub Rest API 返回的内容没有错，是用 Curl 检查的

```bash
curl "https://api.github.com/repos/langningchen/XMOJ-Script-Pictures/contents/rptzrfmpxufetajrvzeccnwqlsesbgmp" \
    -H"Authorization: Bearer ***" \
    -H"User-Agent: XMOJ-Script-Server" \
    -H"Accept: application/vnd.github.raw" \
    --output /mnt/c/Users/jpxx_/OneDrive/Desktop/API.png
diff /mnt/c/Users/jpxx_/OneDrive/Desktop/Raw.png /mnt/c/Users/jpxx_/OneDrive/Desktop/API.png
```

**Comment by langningchen** [comment]
所以不是上传的错误

**Comment by langningchen** [comment]
我又试了试不用 Curl ，用 JS 的 Fetch

```js
let ImageData = await fetch(new URL("https://api.github.com/repos/langningchen/XMOJ-Script-Pictures/contents/ggqzbaghexjxuzwyzvteioeejlouqtcw"), {
    method: "GET",
    headers: {
        "Authorization": "Bearer ***",
        "Accept": "application/vnd.github.text",
        "User-Agent": "XMOJ-Script-Server"
    }
}).then((Response) => {
    return Response.text();
});
let a = document.createElement("a");
a.href = URL.createObjectURL(new Blob([ImageData], { type: "image/png" }));
a.download = "Fetch.png";
a.click();
```

```bash
diff Error.png Fetch.png
```

结果发现 Fetch 得到的和错误的一样，所以 ~我误会了 CloudFlare ，~ 原来是 Fetch 的问题

**Comment by langningchen** [comment]
有人说是 text 的问题，应该要用 Blob ，但是还是不对

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/bef5c1de-e583-4886-aaf7-e410bb7f87dc)

**Comment by langningchen** [comment]
现在准备用 XMLHttpRequest

**Comment by langningchen** [comment]
还是不行……

**Comment by PythonSmall-Q** [comment]
加油做模拟赛！

**Comment by PythonSmall-Q** [comment]
我看你们二老还没交题欸~

**Comment by langningchen** [comment]
> 我看你们二老还没交题欸~

@PythonSmall-Q 确实

**Comment by langningchen** [comment]
上面是正确的，下面是用 fetch 和 GitHub API 获取到的，发现有些字符被替换为了 `FFFD` ？

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/534a7e3d-973d-496e-95b5-6b8c754de40e)

**Comment by langningchen** [comment]
用 Curl 和 Github API 获取到的是对的，和正确的一样，但是使用 fetch 或者 XMLHttpRequest 获取到的就有个别字符是错的，是不是字符编码的问题？

**Comment by PythonSmall-Q** [comment]
> > 我看你们二老还没交题欸~
> 
> @PythonSmall-Q 确实

做了点题，结果发现状态不在都做不出来qwq

**Comment by langningchen** [comment]
@PythonSmall-Q 那就来帮我解决问题吧

**Comment by langningchen** [comment]
经查询， `U+FFFD` 是替换字符，表示UTF-8中没有对应的字符，显示为黑色的菱形和一个问好 `�`

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q 有什么思路吗？我现在准备去网上问一问

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/963916a1-0d53-4f75-8559-a09ba6131818)

**Comment by langningchen** [comment]
https://stackoverflow.com/questions/77213213/why-is-the-response-malformed-when-using-fetch-in-js

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q Horray!

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/c732434c-631c-471a-ad7d-fbb0d350b122)

**Comment by langningchen** [comment]
StackOverflow users give me the answer! :teda:

**Comment by langningchen** [comment]
/-help-wanted @boomzero @PythonSmall-Q 你们快去试试吧！

**Comment by langningchen** [comment]
/-working-on-it

**Comment by langningchen** [comment]
@boomzero 解决了，问题就删了
