### ISSUE TITLE
[Feature Request] 增加清除缓存功能

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#435]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

在用户脚本管理器菜单中除了重置数据，再加一个清除缓存

### 原因

想要看到Badge效果但是不想清除全部数据的时候会用到

**Comment by PythonSmall-Q** [comment]
清除缓存不能清开关

**Comment by langningchen** [comment]
> 清除缓存不能清开关

只是清除缓存，不是清除数据

**Comment by langningchen** [comment]
@PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
okay
