### ISSUE TITLE
[Feature Request] sitemap

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#438]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

**Comment by PythonSmall-Q** [comment]
搞sitemap干嘛

**Comment by PythonSmall-Q** [comment]
（？？？

**Comment by langningchen** [comment]
@PythonSmall-Q 方便搜索引擎

**Comment by PythonSmall-Q** [comment]
我在做了

**Comment by PythonSmall-Q** [comment]
https://github.com/langningchen/XMOJ-Script/pull/472

**Comment by langningchen** [comment]
@PythonSmall-Q

https://github.com/langningchen/XMOJ-Script/issues/472#issuecomment-1732192939 谁来干？
