### ISSUE TITLE
[Feature Request] Delete spam replies from database

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#44]
reply里怎么这么多刷屏的
我可以手动删

**Comment by boomzero** [comment]
see http://www.xmoj.tech/discuss3/thread.php?tid=29

**Comment by boomzero** [comment]
also is there a reason for wrapping comments with ` ``` `? it messes up the formatting

**Comment by langningchen** [comment]
我现在没拿电脑，所以访问不了，但是我看这个帖子应该是之前就有的，好像不是通过新的讨论创建的

**Comment by langningchen** [comment]
明天我拿电脑看一下吧

**Comment by langningchen** [comment]
> reply里怎么这么多刷屏的
> 我可以手动删

如果刷屏是2019年及以前的，那就别管，如果是新发的，那就可以删，不过不删的话问题也不大

**Comment by boomzero** [comment]
> > also is there a reason for wrapping comments with `` ``` ``? it messes up the formatting
> 
> 旧版本的讨论我全都用代码框包裹了，因为他那时还不支持Markdown，所以就有人直接发代码，就会导致格式乱

那你加一个换行吧

**Comment by boomzero** [comment]
```md
```
```
```

**Comment by langningchen** [comment]
> ` ``` `
> `       `
> ` ``` `
> 

什么意思？我不太明白

**Comment by boomzero** [comment]
就是在他们的` ``` `后加\n

**Comment by langningchen** [comment]
应该不用吧，如果有新的刷屏而且很严重你就删
