### ISSUE TITLE
[Feature Request] 使用bark发送通知

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#447]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

https://github.com/Finb/Bark

**Comment by langningchen** [comment]
所以这需要每个苹果用户上传他自己的密钥是吗？

**Comment by boomzero** [comment]
对的

**Comment by boomzero** [comment]
是api-key

**Comment by langningchen** [comment]
但是又要耗费服务器，一个新的资源去存每个人的APIKey了

**Comment by boomzero** [comment]
@langningchen 今天总共有Read queries: 26 write: 0

**Comment by boomzero** [comment]
> 但是又要耗费服务器，一个新的资源去存每个人的APIKey了

新开一个table?

**Comment by boomzero** [comment]
> @langningchen 今天总共有Read queries: 26 write: 0

服务器非常非常空闲

**Comment by langningchen** [comment]
> @langningchen ~说明一下, 我现在体温38.2, 所以我的回复可能非常非常不及时~

Emm，好好休息

**Comment by langningchen** [comment]
> > @langningchen 今天总共有Read queries: 26 write: 0
> 
> 服务器非常非常空闲

主要原因是我觉得用这个东西的人不多

**Comment by PythonSmall-Q** [comment]
hh我体温37.8昏沉了一天

**Comment by langningchen** [comment]
> hh我体温37.8昏沉了一天

@PythonSmall-Q @boomzero 你们怎么都发烧了？

**Comment by langningchen** [comment]
> hh我体温37.8昏沉了一天

@PythonSmall-Q @boomzero 你们怎么都发烧了？

**Comment by boomzero** [comment]
> > hh我体温37.8昏沉了一天
> 
> @PythonSmall-Q @boomzero 你们怎么都发烧了？

6

**Comment by langningchen** [comment]
说实话我不太想做这个 Issue ，你看看行不行，因为用苹果产品的同学好像不多 /-investigating /question

**Comment by boomzero** [comment]
@langningchen 可以

**Comment by langningchen** [comment]
@boomzero 感谢你又帮助发布 `1.0.X` 减轻了负担！
