### ISSUE TITLE
[Bug] autolabel 炸了

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#448]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

https://github.com/langningchen/XMOJ-Script/actions/workflows/AutoLabel.yml

~~每日一炸~~

**Comment by langningchen** [comment]
Test

**Comment by langningchen** [comment]
Test

**Comment by langningchen** [comment]
Trigger不了了？

**Comment by langningchen** [comment]
好像可以

**Comment by langningchen** [comment]
终于找到原因了， ~我是傻子，~ 竟然忘了 checkout

**Comment by langningchen** [comment]
试试 Checkout 以后行吗

**Comment by langningchen** [comment]
Test

**Comment by langningchen** [comment]
最後測試

**Comment by langningchen** [comment]
再来

**Comment by langningchen** [comment]
似乎好了，测试一下 /sever

**Comment by langningchen** [comment]
再来 /-server

**Comment by langningchen** [comment]
原来我删除这个单词拼错了 /-sever

**Comment by langningchen** [comment]
Good!
