### ISSUE TITLE
[Feature Request] 后台存PHPSESSID的hash

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#449]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

直接存不好吧

**Comment by boomzero** [comment]
@langningchen 我写

**Comment by langningchen** [comment]
@boomzero 是不是你干的？Server又炸了！

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/47bf16e1-fd55-433c-afe0-8ddbb9e8576d)
