### ISSUE TITLE
[Feature Request] set new releases as the latest release

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#457]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt, 参见https://github.com/softprops/action-gh-release/pull/304
可以考虑用fork

**Comment by boomzero** [comment]
~好像提别人的pr会显示` @langningchen mentioned this pull request now`~

**Comment by langningchen** [comment]
他的那个仓库管理者似乎弃坑了，PR都不管了

**Comment by boomzero** [comment]
> 他的那个仓库管理者似乎弃坑了，PR都不管了

~那能把我设为 collaborator 吗(~

**Comment by boomzero** [comment]
\-needs-triage

**Comment by boomzero** [comment]
@github-actions test

**Comment by langningchen** [comment]
> @github-actions test

@boomzero ？

**Comment by boomzero** [comment]
> > @github-actions test
> 
> @boomzero ？

没事, 就是测试一个东西

**Comment by boomzero** [comment]
@langningchen 应该需要只允许issue的author或collaborator改label

**Comment by boomzero** [comment]
为什么我不能 @ github-actions

**Comment by boomzero** [comment]
.

**Comment by langningchen** [comment]
我试试

**Comment by langningchen** [comment]
@actions @github-actions

**Comment by langningchen** [comment]
@boomzero 是第一种 @actions

**Comment by langningchen** [comment]
@github-actions

**Comment by langningchen** [comment]
@github-actions[bot]

**Comment by langningchen** [comment]
@boomzero 现在本来就是嘛？

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/b277309f-d3df-49d3-be33-c9052b8f31c9)

难道是你手动更新的？

**Comment by boomzero** [comment]
@langningchen 

> ![image](https://user-images.githubusercontent.com/81672884/270089232-b277309f-d3df-49d3-be33-c9052b8f31c9.png)
> 
> 难道是你手动更新的？

是的...

**Comment by boomzero** [comment]
@langningchen /-question /enhancement

**Comment by langningchen** [comment]
好吧……

**Comment by boomzero** [comment]
> /Github-related

@langningchen 为什么不行

**Comment by langningchen** [comment]
我也不知道

**Comment by langningchen** [comment]
我再试试 /Github-related

**Comment by langningchen** [comment]
好像真的不行^

**Comment by langningchen** [comment]
@boomzero 可以的，只不过你打错了标签的名字

**Comment by langningchen** [comment]
但是问题是怎么实现这个？我看了你发的那个仓库，但是好像没有看懂…… /help-wanted

**Comment by boomzero** [comment]
@langningchen 加一个make_latest:true

**Comment by boomzero** [comment]
mabye?

**Comment by langningchen** [comment]
@boomzero 刚新发的 Release 自动设为了 Latest，这个肯定不是你改的了 /invalid 

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/00bd02de-0b7b-463b-bcdf-6c70bcb55b0c)

**Comment by boomzero** [comment]
> @boomzero 刚新发的 Release 自动设为了 Latest，这个肯定不是你改的了
> 
> ![image](https://user-images.githubusercontent.com/81672884/270143687-00bd02de-0b7b-463b-bcdf-6c70bcb55b0c.png)

?那为什么有一次没有设

**Comment by boomzero** [comment]
Github奇怪bug.
