### ISSUE TITLE
[Bug] 无法注销

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#46]
保存密码后如果注销会立刻重新登录

**Comment by boomzero** [comment]
~为什么所有open的issue都是我开的~

**Comment by langningchen** [comment]
好吧，我今天到时候复现一下，试一试

**Comment by langningchen** [comment]
原因是因为注销以后它就会自动跳转到一个需要登录的界面，而在需要登录界面，如果你开了自动登录以后，它就会自动跳转到登录界面，并且自动登录，所以就造成了无法注销的情况

**Comment by boomzero** [comment]
> 原因是因为注销以后它就会自动跳转到一个需要登录的界面，而在需要登录界面，如果你开了自动登录以后，它就会自动跳转到登录界面，并且自动登录，所以就造成了无法注销的情况

建议清除localstorage中密码

**Comment by langningchen** [comment]
就是在注销的时候清除密码？

**Comment by langningchen** [comment]
好的，好主意，一会儿我干

**Comment by langningchen** [comment]
现在我去解决验证码

**Comment by langningchen** [comment]
@boomzero 这个可能不是很好弄，除非我替换掉注销按钮，因为`logout.php`返回的是`302`，这会导致脚本无法再`logout.php`页面执行

**Comment by langningchen** [comment]
修好了
