### ISSUE TITLE
[Feature Request] Make updateversion `git pull` before pushing

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#460]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

### 原因

https://github.com/langningchen/XMOJ-Script/actions/runs/6271911064/job/17032410542

**Comment by langningchen** [comment]
@boomzero 我还在学校呢……

**Comment by boomzero** [comment]
> @boomzero 我还在学校呢……

啊

**Comment by boomzero** [comment]
你们几点放学

**Comment by boomzero** [comment]
.

**Comment by boomzero** [comment]
> @boomzero 我还在学校呢……

~那你怎么triage的!

**Comment by boomzero** [comment]
> @boomzero 就是正巧看到

@langningchen 看一下https://github.com/langningchen/XMOJ-Script/pull/459

**Comment by langningchen** [comment]
@boomzero 我要回家了，下线
