### ISSUE TITLE
[Feature Request] 在讨论区增加板块选择功能

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#462]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

qaq在讨论区增加分类标签 就像洛谷一样

**Comment by PythonSmall-Q** [comment]
为什么我们的项目有点像洛谷了

**Comment by PythonSmall-Q** [comment]
我觉得这个功能呢，挺变态的

**Comment by PythonSmall-Q** [comment]
help-wanted

**Comment by PythonSmall-Q** [comment]
我设计都很难

**Comment by langningchen** [comment]
你又创建了一个新标签……

**Comment by langningchen** [comment]
为什么不用 `investivating` ？

**Comment by PythonSmall-Q** [comment]
好看

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/a4a66cb7-9632-4080-9042-afe82e3e8e2a)
站务版设计

**Comment by langningchen** [comment]
创建新标签别忘了更改

https://github.com/langningchen/XMOJ-Script/blob/c8027e0003e6b7613713ea468afcf3b18d4f8e1f/Update/AutoLabel.js#L8-L36

**Comment by langningchen** [comment]
> 站务版设计

你这是直接改的 HTML ？

**Comment by langningchen** [comment]
所以你是要增加 “标签” 功能还是 “板块” 功能？

**Comment by PythonSmall-Q** [comment]
板块

**Comment by langningchen** [comment]
那改一下标题

**Comment by langningchen** [comment]
板块简单，比标签简单多了

**Comment by langningchen** [comment]
/-designing /working-on-it /Cloudflare-related

**Comment by PythonSmall-Q** [comment]
脱手

**Comment by PythonSmall-Q** [comment]
转手给万能的cln

**Comment by PythonSmall-Q** [comment]
去搞新的brainstorm了

**Comment by langningchen** [comment]
@PythonSmall-Q 你要哪些 Board ？站务版、灌水区、学术版够了吧？

**Comment by PythonSmall-Q** [comment]
我初步设计是站务版，灌水版，学术版，题目总版

**Comment by PythonSmall-Q** [comment]
（感觉被洛谷influence了

**Comment by langningchen** [comment]
题目总版归并到学术版行吗？

**Comment by PythonSmall-Q** [comment]
可以呀

**Comment by langningchen** [comment]
数据库改好了，该写代码了

**Comment by PythonSmall-Q** [comment]
站务的内容都是0了，其他的太多了就不改了

**Comment by PythonSmall-Q** [comment]
@langningchen 再加一个反馈版3吧

**Comment by langningchen** [comment]
我们发布的最近的都改改，之前的别改了

**Comment by langningchen** [comment]
> @langningchen 再加一个反馈版3吧

可以，还要改数据表 board_id ，你改一下

**Comment by PythonSmall-Q** [comment]
全改了

**Comment by PythonSmall-Q** [comment]
/-priority-low

**Comment by PythonSmall-Q** [comment]
/-priority-high

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/ccf887aa-f516-4388-9248-60eae67aabeb)
什么情况

**Comment by langningchen** [comment]
你的网络问题

**Comment by PythonSmall-Q** [comment]
6

**Comment by langningchen** [comment]
我要下线了

**Comment by PythonSmall-Q** [comment]
好了终于没问题了

**Comment by langningchen** [comment]
/-working-on-it OK
