### ISSUE TITLE
[Feature Request] 增加turnstile解决率

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#475]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/7844d2dd-62b3-4e7d-bbf1-c3025f8fcb61)
如图，api解决率有点吓人qaq

**Comment by langningchen** [comment]
@PythonSmall-Q 怎么增加？ /help-wanted /-need-triage

**Comment by boomzero** [comment]
?

**Comment by boomzero** [comment]
这是正常的啊

**Comment by boomzero** [comment]
~因为都在吃瓜, 没人发消息~

**Comment by boomzero** [comment]
只有发布评论才会向API验证token的真实性

**Comment by boomzero** [comment]
所以很少的token被真正验证过

**Comment by boomzero** [comment]
所以API解决率才这么低

**Comment by boomzero** [comment]
@PythonSmall-Q
