### ISSUE TITLE
[Bug] Post time is set using the incorrect time zone

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#48]

**Comment by langningchen** [comment]
一会儿打完月赛修

**Comment by PythonSmall-Q** [comment]
艹原来还有月赛我都不知道…………

**Comment by langningchen** [comment]
> 艹原来还有月赛我都不知道…………

@PythonSmall-Q 已经结束了……

**Comment by langningchen** [comment]
为解决此问题，我可能要重置数据库结构，正好可以把先前的数据修一下 @boomzero 你来修一修

**Comment by langningchen** [comment]
直接用BBSSpider.js爬取数据，然后修就好了 @boomzero

**Comment by langningchen** [comment]
https://github.com/langningchen/XMOJ-Script/blob/master/Server/Source/BBSSpider.js

最好不要用现成的数据：https://github.com/langningchen/XMOJ-Script/blob/master/Server/Source/BBSSpider.json
因为那个好像有点问题

**Comment by langningchen** [comment]
把js复制到xmoj的任意界面的控制台运行，不要用nodejs本地运行

**Comment by langningchen** [comment]
另外，如果你要commit也从dev分支 @boomzero

**Comment by boomzero** [comment]
@langningchen 我刚开了add-color 分支

**Comment by boomzero** [comment]
我在讨论区加用户名颜色

**Comment by boomzero** [comment]
![cl](https://github.com/langningchen/XMOJ-Script/assets/85378277/a0747611-4259-41ee-8618-dd3b5e307b61)
... 可能要调一下颜色

**Comment by boomzero** [comment]
![](https://github.com/langningchen/XMOJ-Script/assets/85378277/d5ba6bce-7a78-4339-a1f1-9eac61e42aa8)
much better

**Comment by langningchen** [comment]
可以

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/1c150b63-9e90-4254-9ce1-07f02a01ea05)

好了

**Comment by boomzero** [comment]
![time3](https://github.com/langningchen/XMOJ-Script/assets/85378277/41f097df-943c-4d61-86a0-25ef9c787435)
...

**Comment by boomzero** [comment]
@langningchen

**Comment by langningchen** [comment]
你使用了Dev分支的XMOJ.user.js了吗？

**Comment by langningchen** [comment]
@boomzero
