### ISSUE TITLE
[Bug] 编辑功能 在代码框内显示错乱

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#49]
http://www.xmoj.tech/discuss3/thread.php?tid=179

**Comment by boomzero** [comment]
fixed, 不要overwrite

**Comment by langningchen** [comment]
...你胡乱编辑人家的代码干什么……

**Comment by langningchen** [comment]
@boomzero 旧的东西别动了，要么我就全删了

**Comment by boomzero** [comment]
> ...你胡乱编辑人家的代码干什么……

不是啊, 我只是修格式

**Comment by boomzero** [comment]
加了 ` ``` `

**Comment by langningchen** [comment]
好吧

**Comment by langningchen** [comment]
这个BUG是因为你只加了一半的` ``` `吧，只加了前半段没有后半段

**Comment by boomzero** [comment]
没有啊

**Comment by boomzero** [comment]
> 这个BUG是因为你只加了一半的`` ``` ``吧，只加了前半段没有后半段

加一个 \n 就没事了啊

**Comment by langningchen** [comment]
好吧，按理来说不应该

**Comment by langningchen** [comment]
前面的格式你先别修了，我准备重新导入

**Comment by langningchen** [comment]
@boomzero 我格式全部修好了，在本地手动干的，明天再上传吧

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/23b4d700-d4fa-4b79-90b0-9b2800918154)

**Comment by langningchen** [comment]
@boomzero 都帮他们加上了代码框和 $\TeX$

**Comment by langningchen** [comment]
@boomzero 哭死，因为Git出错重新Clone了仓库，导致数据库内容全没了！又得要重新修！

**Comment by langningchen** [comment]
@boomzero 一个小时以后终于又改好了
