### ISSUE TITLE
[Bug] 忽略提醒后立刻不显示该提醒

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#490]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

rt

**Comment by langningchen** [comment]
但是应该刷新以后消息就不见了吧？

**Comment by langningchen** [comment]
我没有检查忽略是否好用因为当时我没有提醒…… /question

**Comment by boomzero** [comment]
> 但是应该刷新以后消息就不见了吧？

没有

**Comment by langningchen** [comment]
额，好吧

**Comment by boomzero** [comment]
你@我一下?

**Comment by langningchen** [comment]
@boomzero 你给我发一条消息我检查一下

**Comment by langningchen** [comment]
好的，我检查一下

**Comment by langningchen** [comment]
@boomzero 经过测试，点击以后确实没有消失，但是刷新以后就没了 /-question /invalid /-needs-triage

**Comment by langningchen** [comment]
@boomzero 你可以更改标题为 `忽略提醒后立刻不显示该提醒`

**Comment by boomzero** [comment]
> @boomzero 经过测试，点击以后确实没有消失，但是刷新以后就没了

thx

**Comment by boomzero** [comment]
/-invalid

**Comment by langningchen** [comment]
@boomzero 你以後能不能不要發這種空的回復？

**Comment by langningchen** [comment]
也就是不要将 `/` 命令单独作为一个回复，而是在其他的回复中

**Comment by langningchen** [comment]
比如，你应该发 `thx /-invalid` ，而不是 `thx` 和 `/-invalid`
