### ISSUE TITLE
[Bug] server炸了

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#492]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

rt

### 控制台错误信息

```
数据库查询失败：Error: D1_TYPE_ERROR: Type 'undefined' not supported for value 'undefined'
```

**Comment by langningchen** [comment]
啊啊啊 /-needs-triage /investigaing

**Comment by langningchen** [comment]
应该就是因为我刚才 `wrangler deploy` 了一下

**Comment by langningchen** [comment]
就是你的 MD5 造成的

**Comment by boomzero** [comment]
> 就是你的 MD5 造成的

.

**Comment by boomzero** [comment]
6

**Comment by langningchen** [comment]
现在好了吧？我把 MD5 删了

**Comment by boomzero** [comment]
好了

**Comment by boomzero** [comment]
MD5怎么回事

**Comment by boomzero** [comment]
~我当时没有测试~

**Comment by langningchen** [comment]
好像就是 MD5 is undefined

**Comment by boomzero** [comment]
啊?

**Comment by boomzero** [comment]
不是string吗

**Comment by langningchen** [comment]
可能是 CryptoJS 引用错了，我现在正在改用 CryptoTS

**Comment by langningchen** [comment]
/-investigating
