### ISSUE TITLE
[Bug] @渲染出错

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#499]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/1dbe94df-cad1-4f56-85c3-2c18921fea80)
如图，这个渲染似乎有点炸裂

**Comment by langningchen** [comment]
好的，我知道了，因为我更改没有更改全。你看一下旧的@应该是能渲染成功的，但是新发的不行

**Comment by langningchen** [comment]
~现在的AutoLabel真体贴人，看到我回复就帮我加好标签了~

**Comment by langningchen** [comment]
/-investigating 好了，修复旧的要改所有数据库，所以要等一会儿
