### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#5]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/61b4731b-2fa8-43a9-b108-2de998b810f2)
点击登录按钮无反应

**Comment by langningchen** [comment]
Please provide move information

**Comment by PythonSmall-Q** [comment]
1st step, click logout
2nd step: go to login page( automatic)
3rd step: file in the username and password
final situation: cracked, can't login

**Comment by langningchen** [comment]
Please add `www.` prefix in the URL. If it doesn't work, please reopen this issue. Thanks.

**Comment by PythonSmall-Q** [comment]
emm加了www是可以了，但是这样我每次都要加www了……

**Comment by langningchen** [comment]
I will fix it if possible

**Comment by PythonSmall-Q** [comment]
consider adding  redirection to www.xmoj.tech via 302 status code

**Comment by PythonSmall-Q** [comment]
maybe i will make a PR

**Comment by langningchen** [comment]
> maybe i will make a PR

Thanks

**Comment by PythonSmall-Q** [comment]
https://github.com/langningchen/XMOJ-Script/pull/17

**Comment by langningchen** [comment]
Fixed in 0.1.34, please wait for release. Thanks.
