### ISSUE TITLE
[Feature Request] 增加favicon

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#509]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

增加icon，要不一起设计一下？

**Comment by boomzero** [comment]
@PythonSmall-Q  你是说favicon吗

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q 好主意啊

**Comment by langningchen** [comment]
@PythonSmall-Q 注意以后不要随便去掉 needs-triage 标签，不然 Actions 容易出问题

**Comment by PythonSmall-Q** [comment]
为什么我和boomzero发言就不能investigating，只有langningchen能触发所有的便捷化操作

**Comment by PythonSmall-Q** [comment]
（区别对待qwq

**Comment by langningchen** [comment]
@PythonSmall-Q 就是区别对待，你们俩只是合作者，我是拥有者，权限不一样

**Comment by boomzero** [comment]
> 为什么我和boomzero发言就不能investigating，只有langningchen能触发所有的便捷化操作

可以啊 /user-script

**Comment by boomzero** [comment]
@PythonSmall-Q ~除非我把你用户名打错了~ /-user-script

**Comment by PythonSmall-Q** [comment]
emm你看看吧我似乎触发不了自动化
















在 2023-09-27 21:31:04，"Zhu Chenrui" ***@***.***> 写道：

@PythonSmall-Q除非我把你用户名打错了 /-user-script

**Comment by boomzero** [comment]
@PythonSmall-Q 经测试, 可以

**Comment by boomzero** [comment]
除非你把标签名打错了... /-user-script

**Comment by boomzero** [comment]
所以我觉得这样并不快捷

**Comment by langningchen** [comment]
@boomzero， @PythonSmall-Q 说的是我回复了能自动删除 needs-triage，加上 investigating

**Comment by PythonSmall-Q** [comment]
![xmoj](https://github.com/langningchen/XMOJ-Script/assets/106425289/7947e8d6-20cd-44a0-a6eb-948d7d92a7e6)

**Comment by PythonSmall-Q** [comment]
这个如何@langningchen @boomzero

**Comment by langningchen** [comment]
@PythonSmall-Q Good

**Comment by PythonSmall-Q** [comment]
没问题就merge dev 然后赶紧merge master否则不能生效

**Comment by langningchen** [comment]
@PythonSmall-Q 有问题

**Comment by langningchen** [comment]
去看 Review

**Comment by PythonSmall-Q** [comment]
@langningchen 你的那个navbar好了么

**Comment by PythonSmall-Q** [comment]
Fixed！！！

**Comment by langningchen** [comment]
/-working-on-it /-help-wanted OK

**Comment by PythonSmall-Q** [comment]
wc？明明是我点remove咋变成bot了（？？

**Comment by langningchen** [comment]
@PythonSmall-Q 你看看其他的几个 @ 你地问题

**Comment by langningchen** [comment]
> wc？明明是我点remove咋变成bot了（？？

看来你点晚了

**Comment by PythonSmall-Q** [comment]
啥@ ？

**Comment by langningchen** [comment]
我这个Comment让Bot删的

https://github.com/langningchen/XMOJ-Script/issues/509#issuecomment-1740551052

**Comment by langningchen** [comment]
#432 能不能帮帮忙？

**Comment by langningchen** [comment]
@PythonSmall-Q  还有 #512 你说的 https://github.com/langningchen/XMOJ-Script/issues/512#issuecomment-1733520690

**Comment by langningchen** [comment]
再评判一下 #514 是否必要

**Comment by langningchen** [comment]
你直接看 https://github.com/notifications 不就好了吗？
