### ISSUE TITLE
[BUG] Fix code scanning alert - Clear text storage of sensitive information

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#512]
Tracking issue for:
- [ ] https://github.com/langningchen/XMOJ-Script/security/code-scanning/1

**Comment by PythonSmall-Q** [comment]
9/28-30我抽空看看

**Comment by langningchen** [comment]
> 9/28-30我抽空看看

谢谢！

**Comment by boomzero** [comment]
hash也不行 /user-script

**Comment by boomzero** [comment]
可以encrypt

**Comment by boomzero** [comment]
```js
var express = require('express');
var crypto = require('crypto'),
    password = getPassword();

function encrypt(text){
  var cipher = crypto.createCipher('aes-256-ctr', password);
  return cipher.update(text, 'utf8', 'hex') + cipher.final('hex');
}

var app = express();
app.get('/remember-password', function (req, res) {
  let pw = req.param("current_password");
  // GOOD: Encoding the value before setting it.
  res.cookie("password", encrypt(pw));
});
```

**Comment by langningchen** [comment]
> ```js
> var express = require('express');
> var crypto = require('crypto'),
>     password = getPassword();
> 
> function encrypt(text){
>   var cipher = crypto.createCipher('aes-256-ctr', password);
>   return cipher.update(text, 'utf8', 'hex') + cipher.final('hex');
> }
> 
> var app = express();
> app.get('/remember-password', function (req, res) {
>   let pw = req.param("current_password");
>   // GOOD: Encoding the value before setting it.
>   res.cookie("password", encrypt(pw));
> });
> ```

@boomzero 我解释一下，他这个是服务端的程序，对于我们客户端没用

**Comment by boomzero** [comment]
@langningchen I know, ~I tried~

**Comment by boomzero** [comment]
但是crypto-js的aes.js会有内部错误

**Comment by langningchen** [comment]
这肯定是你的问题，人家肯定没问题的，肯定是你传入的参数有问题

**Comment by boomzero** [comment]
> 这肯定是你的问题，人家肯定没问题的，肯定是你传入的参数有问题

我在写https://github.com/boomzero/OJsys, 所以没看

**Comment by boomzero** [comment]
> 这肯定是你的问题，人家肯定没问题的，肯定是你传入的参数有问题

.

**Comment by boomzero** [comment]
你能看一眼吗?
我这里一直r is not defined

**Comment by langningchen** [comment]
好吧
