### ISSUE TITLE
[Bug] 官网炸了

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#517]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在使用留白的网络的时候无法访问 `xmoj-bbs.tech` ，导致检查更新、讨论加载全部出问题，现在在考虑是被墙了还是留白的问题

### 重现步骤

在 留白空间 访问

**Comment by langningchen** [comment]
/question /website /server /Cloudflare-related /priority-high @boomzero @PythonSmall-Q 帮我检查一下

**Comment by PythonSmall-Q** [comment]
查看中，请稍后

**Comment by PythonSmall-Q** [comment]
我这边一片正常

**Comment by PythonSmall-Q** [comment]
留白的公网IP给我一下，查看地址：ip2location.com

**Comment by langningchen** [comment]
那就好

**Comment by langningchen** [comment]
220.200.108.32

**Comment by langningchen** [comment]
话说 Github Actions 好像忘记删了两个标签
