### ISSUE TITLE
[Feature Request] 增加下载条目

### ISSUE THREAD

**Issue by Leiwenda** [langningchen/XMOJ-Script#52]
CP Editor：https://cpeditor.org/download/

**Comment by langningchen** [comment]
我将使用[Sourceforge下载链接](https://sourceforge.net/projects/cp-editor.mirror/)，而不是官网

**Comment by langningchen** [comment]
为了统一下载地址，我的几乎所有下载都是Sourceforge上面的

**Comment by langningchen** [comment]
@Leiwenda 好了，等待发布吧
