### ISSUE TITLE
[Feature Request] 自动骗数据

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#524]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

自动提交读完stdin, 然后直接抛出错误的代码

然后看reinfo就行了

**Comment by langningchen** [comment]
az……不太道德吧

**Comment by boomzero** [comment]
@langningchen ~没事, 我天天干~

**Comment by langningchen** [comment]
好吧

**Comment by langningchen** [comment]
@boomzero 具体你是什么意思？

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/1710c1d0-7200-4f45-a629-122a10bcc90a)

**Comment by langningchen** [comment]
```
#include <bits/stdc++.h>
using namespace std;
int main()
{
	string Input;
	while (1) {
		char c = getchar();
		if (c == EOF) {
			break;
		}
		Input.push_back(c);
	}
	throw (Input.c_str());
	return 0;
}
```

**Comment by boomzero** [comment]
> ```c++
> #include <bits/stdc++.h>
> using namespace std;
> int main()
> {
> 	string Input;
> 	while (1) {
> 		char c = getchar();
> 		if (c == EOF) {
> 			break;
> 		}
> 		Input.push_back(c);
> 	}
> 	throw runtime_error(Input.c_str());
> 	return 0;
> }
> ```

**Comment by boomzero** [comment]
@langningchen

**Comment by boomzero** [comment]
记得freopen

**Comment by langningchen** [comment]
好的

**Comment by langningchen** [comment]
@boomzero 成功了

![Uploading image.png…]()

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/dcad5877-4686-4403-8d07-6b9b02c5a2d2)

**Comment by langningchen** [comment]
@boomzero 代码写好了

```cpp
#include <bits/stdc++.h>
using namespace std;
string Base64Encode(string Input)
{
    const string Base64Chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    string Output;
    for (int i = 0; i < Input.length(); i += 3)
    {
        Output.push_back(i + 0 > Input.length() ? '=' : Base64Chars[(Input[i + 0] & 0xfc) >> 2]);
        Output.push_back(i + 1 > Input.length() ? '=' : Base64Chars[((Input[i + 0] & 0x03) << 4) + ((Input[i + 1] & 0xf0) >> 4)]);
        Output.push_back(i + 2 > Input.length() ? '=' : Base64Chars[((Input[i + 1] & 0x0f) << 2) + ((Input[i + 2] & 0xc0) >> 6)]);
        Output.push_back(i + 3 > Input.length() ? '=' : Base64Chars[Input[i + 2] & 0x3f]);
    }
    return Output;
}
int main()
{
#ifdef IOFile
    freopen(IOFile ".in", "r", stdin);
    freopen(IOFile ".out", "w", stdout);
#endif
    string Input;
    while (1)
    {
        char Data = getchar();
        if (Data == EOF)
            break;
        Input.push_back(Data);
    }
    throw runtime_error("[" + Base64Encode(Input.c_str()) + "]");
    return 0;
}
```

**Comment by langningchen** [comment]
@boomzero 你试试行不行 /-investigating /working-on-it

**Comment by boomzero** [comment]
ahh, great

**Comment by boomzero** [comment]
?

**Comment by boomzero** [comment]
好智能...

**Comment by langningchen** [comment]
我也不知道……

**Comment by boomzero** [comment]
应该可以

**Comment by boomzero** [comment]
只要base64没写错

**Comment by boomzero** [comment]
/-investigating /working-on-it

**Comment by langningchen** [comment]
为什么你你就行……

**Comment by boomzero** [comment]
不过提交re代码过不了预编译

**Comment by langningchen** [comment]
确实

**Comment by boomzero** [comment]
test /github_actions /-bug /bug

**Comment by boomzero** [comment]
/-enhancement /-github_actions

**Comment by boomzero** [comment]
another test /enhancement /-bug

**Comment by boomzero** [comment]
感觉我也在spam

**Comment by boomzero** [comment]
? 不是按顺序process的吗 /-bug /enhancement

**Comment by langningchen** [comment]
应该是的啊

**Comment by boomzero** [comment]
?

**Comment by boomzero** [comment]
神奇

**Comment by langningchen** [comment]
@boomzero 太长了……导致OLE，并且错误显示不全

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/6527c044-db51-4abf-b0cb-b1656ba94faf)

**Comment by boomzero** [comment]
> @boomzero 太长了……导致OLE，并且错误显示不全
> 
> ![image](https://user-images.githubusercontent.com/81672884/271755996-6527c044-db51-4abf-b0cb-b1656ba94faf.png)

大部分题不会

**Comment by boomzero** [comment]
@actions stop

**Comment by langningchen** [comment]
但是第一个数据是对的

![Uploading image.png…]()

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/fe3bd954-c2e3-4ff6-9e45-ba01a05e4733)

**Comment by boomzero** [comment]
~为什么要base64,直接用不行吗~

**Comment by boomzero** [comment]
> ![image](https://user-images.githubusercontent.com/81672884/271756044-fe3bd954-c2e3-4ff6-9e45-ba01a05e4733.png)

那就是对的

**Comment by boomzero** [comment]
建议在http://www.xmoj.tech/problem.php?id=1012下测试

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/31b21b91-b948-4ba6-99db-3a9cb7781ac4)

**Comment by langningchen** [comment]
@boomzero 数据已经可以了，但是怎么展示呢？

**Comment by boomzero** [comment]
> ![image](https://user-images.githubusercontent.com/81672884/271756641-31b21b91-b948-4ba6-99db-3a9cb7781ac4.png)

好吧, 看来我们的题库不一样

**Comment by boomzero** [comment]
> @boomzero 数据已经可以了，但是怎么展示呢？

就放代码框?

**Comment by langningchen** [comment]
@boomzero 试一下， #566

**Comment by langningchen** [comment]
/-working-on-it 应该没问题了，先Close
