### ISSUE TITLE
[Feature Request]当没有修改userscript时允许pr到master

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#525]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

https://github.com/langningchen/XMOJ-Script/pull/522#issuecomment-1740570557

**Comment by langningchen** [comment]
/-investigating
