### ISSUE TITLE
[Bug] 无法发帖 / Server 炸了

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#526]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

```
数据库查询失败：Error: D1_ERROR: NOT NULL constraint failed: bbs_post.board_id
```

```
服务器运行错误：TypeError: Cannot read properties of undefined (reading 'board_name')
```

**Comment by boomzero** [comment]
related to #462 /priority-high

**Comment by boomzero** [comment]
@langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen 
@langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen 
@langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen 
@langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen 
@langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen 
@langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen 
@langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen 
@langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen 
@langningchen @langningchen @langningchen @langningchen @langningchen @langningchen @langningchen 
快triage...

**Comment by PythonSmall-Q** [comment]
我试试看能不能复现

**Comment by PythonSmall-Q** [comment]
复现成功
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/8865b3d4-ca07-4726-87fc-73ec3b6eb6b4)
确认问题存在

**Comment by PythonSmall-Q** [comment]
@langningchen

**Comment by PythonSmall-Q** [comment]
@langningchen

Sent from Mail for Windows

**Comment by langningchen** [comment]
啊啊啊

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q 来了

**Comment by PythonSmall-Q** [comment]
啊啊啊cln终于来了

Sent from Mail for Windows

**Comment by langningchen** [comment]
hhh

**Comment by PythonSmall-Q** [comment]
这个问题应该是后端加上了board_id但是前端的ts没有

**Comment by langningchen** [comment]
对的

**Comment by langningchen** [comment]
再试试

**Comment by PythonSmall-Q** [comment]
emm默认灌水版（？？

**Comment by PythonSmall-Q** [comment]
发送讨论的时候是不是应该允许选择板块

**Comment by PythonSmall-Q** [comment]
discuss3主页是不是需要加上不同的board的按钮

**Comment by PythonSmall-Q** [comment]
（转入PM模式

**Comment by langningchen** [comment]
对的，选择板块的在分支里面，还没有合并到dev

**Comment by PythonSmall-Q** [comment]
Okay

**Comment by boomzero** [comment]
@langningchen server炸了:
```
服务器运行错误：TypeError: Cannot read properties of undefined (reading 'board_name')
```

**Comment by langningchen** [comment]
@boomzero 知道

**Comment by boomzero** [comment]
还是django的models.py好用

**Comment by PythonSmall-Q** [comment]
万能的log/kk

**Comment by boomzero** [comment]
直接帮你做migrations

**Comment by langningchen** [comment]
知道原因了 @boomzero @PythonSmall-Q

**Comment by langningchen** [comment]
应该是你导致的 @PythonSmall-Q

**Comment by langningchen** [comment]
好了，就是 @PythonSmall-Q 干的，数据库改错了

**Comment by langningchen** [comment]
他没改全 /-investigating /-help-wanted

**Comment by langningchen** [comment]
@PythonSmall-Q 你在bbs_post中加了board_id为3地讨论，但是board_id表没改

**Comment by PythonSmall-Q** [comment]
wc我都没看到board_id表
