### ISSUE TITLE
[Bug]match label的regex有问题

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#529]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

应该是`\/[a-zA-Z-_]+|( first issue)`?

**Comment by langningchen** [comment]
这个简单，你来吧

**Comment by boomzero** [comment]
> 这个简单，你来吧

但是我不确定啊...

**Comment by boomzero** [comment]
所以我才开issue

**Comment by boomzero** [comment]
<details><summary>label commands</summary>
<p>

/priority-high

</p>
</details>

**Comment by langningchen** [comment]
/-investigating
