### ISSUE TITLE
[BUG] Latex显示异常

### ISSUE THREAD

**Issue by Leiwenda** [langningchen/XMOJ-Script#53]
见[此讨论](http://www.xmoj.tech/discuss3/thread.php?tid=220)

![image](https://github.com/langningchen/XMOJ-Script/assets/142971160/946889ba-6f89-49aa-8bea-31fd39788600)

**Comment by langningchen** [comment]
@Leiwenda 这个是Katex本身的BUG，不是XMOJ-Script的问题，请到[此仓库](https://github.com/KaTeX/KaTeX)提出Issue，谢谢！

**Comment by boomzero** [comment]
@langningchen 经测试Katex无此问题

**Comment by langningchen** [comment]
@boomzero 直接使用Latex无此问题，但是在特定的环境里面就有问题了

**Comment by boomzero** [comment]
@langningchen MathJax 不行吗

**Comment by langningchen** [comment]
> @langningchen MathJax 不行吗

可以试试

**Comment by langningchen** [comment]
使用MathJax你开新的Issue

**Comment by boomzero** [comment]
Fixed by #55
