### ISSUE TITLE
[Feature Request] 结束对0.1.x的支持并规划后续结束支持的计划

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#533]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

结束对0.1.x的支持并规划后续结束支持的计划

**Comment by langningchen** [comment]
实现思路？

**Comment by PythonSmall-Q** [comment]
我估计现在没人用0.1.x了，所以我们是不是可以写notice或者像windows那样跳弹窗（用addon-script）

**Comment by PythonSmall-Q** [comment]
而且0.1.x有许多bugggg

**Comment by langningchen** [comment]
> 我估计现在没人用0.1.x了，所以我们是不是可以写notice或者像windows那样跳弹窗（用addon-script）

可以啊

**Comment by PythonSmall-Q** [comment]
后续到差不多几个月之后0.2.x也可以寿终正寝了

**Comment by PythonSmall-Q** [comment]
基本上就是新的大版本0.x.x出来之后之前的版本提供帮助一个月然后让他下班

**Comment by PythonSmall-Q** [comment]
大产品是1year，但是我想我们这种一个月即可

**Comment by langningchen** [comment]
我准备等到1.0.X发布后我就不干了，交给你们俩，因为到了初三没太有空了

**Comment by langningchen** [comment]
再说考完这次 CSP ，XMOJ就不再用了

**Comment by PythonSmall-Q** [comment]
甩手掌柜

**Comment by PythonSmall-Q** [comment]
你高中不学了（？

**Comment by langningchen** [comment]
> 你高中不学了（？

如果这次考不好就不学了

**Comment by PythonSmall-Q** [comment]
不是，为什么我是she/her？？？
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/96bbf0ab-d3d5-4c38-82cc-f17acbeff300)

**Comment by PythonSmall-Q** [comment]
隐藏性别挺好的

**Comment by PythonSmall-Q** [comment]
@langningchen 加入这个团队：https://www.luogu.com.cn/team/54686

**Comment by PythonSmall-Q** [comment]
然后做这道题：https://www.luogu.com.cn/problem/T382021 你会爆炸的

**Comment by PythonSmall-Q** [comment]
> 然后做这道题：https://www.luogu.com.cn/problem/T382021 你会爆炸的

（我出的

**Comment by PythonSmall-Q** [comment]
总感觉我在spam

**Comment by langningchen** [comment]
测试

**Comment by PythonSmall-Q** [comment]
测试啥（？

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/14f6182a-5406-43f2-a614-ec172c4a9925)

**Comment by langningchen** [comment]
这应该好了

**Comment by PythonSmall-Q** [comment]
emm我也看到了

**Comment by PythonSmall-Q** [comment]
merge（？你那个pr

**Comment by boomzero** [comment]
现在旧版本不能用

**Comment by langningchen** [comment]
> 现在旧版本不能用

几乎全不能用了

**Comment by boomzero** [comment]
> > 现在旧版本不能用
> 
> 几乎全不能用了

对, 主要是板块功能对旧版本非常不友好

**Comment by boomzero** [comment]
应该不传boardid时用默认值

**Comment by boomzero** [comment]
actions 还有bug...

**Comment by boomzero** [comment]
> 我准备等到1.0.X发布后我就不干了，交给你们俩，因为到了初三没太有空了

.

**Comment by boomzero** [comment]
不过我也初三了...

**Comment by langningchen** [comment]
> 不过我也初三了...

我知道， @PythonSmall-Q 也是初三

**Comment by boomzero** [comment]
现在就是非常老的版本会炸, 因为ansi_up

**Comment by boomzero** [comment]
不然可以自动更新的

**Comment by boomzero** [comment]
This issue is now being designed, please wait for further information是什么鬼 /-designing

**Comment by boomzero** [comment]
设计issue吗

**Comment by langningchen** [comment]
@boomzero 这个是 @PythonSmall-Q 强烈建议要加的

**Comment by boomzero** [comment]
?

**Comment by boomzero** [comment]
那我rephrase一下

**Comment by boomzero** [comment]
. /designing
