### ISSUE TITLE
[Feature Request] 增加eula

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#543]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

我来做eula

**Comment by boomzero** [comment]
/-needs-triage

**Comment by PythonSmall-Q** [comment]
完成
