### ISSUE TITLE
[Bug] 无法在题目板块发布讨论

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#549]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

rt

显示请选择要发布的板块
但是没法选

**Comment by boomzero** [comment]
@langningchen /priority-high

**Comment by boomzero** [comment]
啊? /priority-high /server

**Comment by boomzero** [comment]
智能actions

**Comment by langningchen** [comment]
actions出BUG了

**Comment by boomzero** [comment]
好了吧 /priority-high blahblahblah

**Comment by boomzero** [comment]
ahhh

**Comment by boomzero** [comment]
```
Found command /good
Label good not exists
Found command  first issue
Label first issue not exists
```

**Comment by boomzero** [comment]
.

**Comment by boomzero** [comment]
@langningchen #550

**Comment by boomzero** [comment]
@langningchen 目测现在我们有7个monthly active users!

**Comment by langningchen** [comment]
> @langningchen 目测现在我们有7个monthly active users!

真棒！

**Comment by boomzero** [comment]
> > @langningchen 目测现在我们有7个monthly active users!
> 
> 真棒！

这只是现在phpsessid tabel里的unique 用户数, 实际可能更多

**Comment by langningchen** [comment]
昨天我又新邀请了一个人

**Comment by boomzero** [comment]
能不edit了吗...

**Comment by langningchen** [comment]
你看一下数据库里面是不是昨天有新多加了一个unique user

**Comment by boomzero** [comment]
xiezhiying?

**Comment by boomzero** [comment]
ahh, 好了

**Comment by boomzero** [comment]
/-good first issue

**Comment by langningchen** [comment]
> xiezhiying?

对的，应该就是他

**Comment by boomzero** [comment]
md,还是不行

**Comment by boomzero** [comment]
> /-good first issue

**Comment by langningchen** [comment]
我现在在地铁上，所以用的是手机，等一会上高铁了就能用电脑了

**Comment by langningchen** [comment]
这个不是正则表达式的问题，是每一次运行都会出问题，后面有个地方错了

**Comment by boomzero** [comment]
#552

**Comment by boomzero** [comment]
/-good first issue

**Comment by boomzero** [comment]
好了 /good first issue

**Comment by boomzero** [comment]
> 我现在在地铁上，所以用的是手机，等一会上高铁了就能用电脑了

打模拟赛ing

**Comment by langningchen** [comment]
知道

**Comment by langningchen** [comment]
/-investigating
