### ISSUE TITLE
[Feature Request] 自动提交当年代码

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#560]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

### 原因

~抢首A~

**Comment by boomzero** [comment]
~虽然不太道德~

**Comment by langningchen** [comment]
又来了……

**Comment by PythonSmall-Q** [comment]
强烈反对

**Comment by langningchen** [comment]
说实话……我也反对

**Comment by boomzero** [comment]
> 强烈反对

. 但是有些人会用

**Comment by langningchen** [comment]
> > 强烈反对
> 
> . 但是有些人会用

谁？你？

**Comment by boomzero** [comment]
> > > 强烈反对
> > 
> > 
> > . 但是有些人会用
> 
> 谁？你？

不是我 ~我几乎没做过多少题~

**Comment by langningchen** [comment]
提高AC率就是这个，再说你也不用，所以就不用了 /duplicate
