### ISSUE TITLE
[Bug] 月赛下部缺失

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#564]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/ef079d62-fe0a-4b72-b0c4-1166c646b029)

**Comment by PythonSmall-Q** [comment]
@langningchen 下部缺失

**Comment by boomzero** [comment]
可以复现 /user-script

**Comment by langningchen** [comment]
好像是的

**Comment by langningchen** [comment]
/-working-on-it
