### ISSUE TITLE
[Bug] 表格线条缺失

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#565]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/c2543b31-7b6c-4f76-bbe5-3776fb2f376e)
如图，线条缺失，看着很别扭

**Comment by boomzero** [comment]
可以复现 /user-script

**Comment by langningchen** [comment]
问题应该不大吧

**Comment by langningchen** [comment]
@PythonSmall-Q 能给一个题目URL吗？ /question

**Comment by langningchen** [comment]
@PythonSmall-Q 能给一个题目URL吗？ /question

**Comment by PythonSmall-Q** [comment]
那道题都可以。CSP-J/S和其他的有表格的题目的都有问题

**Comment by PythonSmall-Q** [comment]
/-questioin

**Comment by langningchen** [comment]
@PythonSmall-Q 给一个 PID ，我找不到

**Comment by PythonSmall-Q** [comment]
tnnd别改我在写代码。到时候又得重来

**Comment by langningchen** [comment]
@PythonSmall-Q ？重来？

**Comment by langningchen** [comment]
正好提醒我，忘记 close 了

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/40d47f4c-8180-45ae-b052-5d38b685af55)
还是炸

**Comment by PythonSmall-Q** [comment]
@langningchen

**Comment by langningchen** [comment]
这没错了啊

**Comment by langningchen** [comment]
他本来就是跨多行的单元格，所以不能加边框 @PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
好，close！！！

**Comment by langningchen** [comment]
如果你还是要边框，给 https://github.com/twbs/bootstrap 这个仓库提 Issue @PythonSmall-Q
