### ISSUE TITLE
[Bug] 短消息接受用户显示异常

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#570]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/langningchen/XMOJ-Script/assets/85378277/cdfcdb94-59e4-4413-a833-1a7770d5bbf2)

**Comment by langningchen** [comment]
复现成功

**Comment by langningchen** [comment]
/-investigating
