### ISSUE TITLE
[Feature Request] 数据库有breaking change的时候bump version

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#571]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

因为board_id所以要bump version

### 原因

不然没法support旧版本

**Comment by langningchen** [comment]
我不太明白，那个只是改服务器的代码，又不需要用户更新，为什么需要这样？

**Comment by langningchen** [comment]
哦，你说的是发送讨论的时候没有传入board_id参数对吧？

**Comment by PythonSmall-Q** [comment]
对。这是关键更新

**Comment by boomzero** [comment]
> 哦，你说的是发送讨论的时候没有传入board_id参数对吧？

对

**Comment by boomzero** [comment]
获取时也要传

**Comment by langningchen** [comment]
所以怎么bump？发一个AddonScript？

**Comment by boomzero** [comment]
现在bump啊

**Comment by langningchen** [comment]
@boomzero 我就说怎么bump？

**Comment by langningchen** [comment]
/-question /-investigating
