### ISSUE TITLE
[Bug] 无法观看/problem_video.php下的视频

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#573]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

rt

**Comment by boomzero** [comment]
http://www.xmoj.tech/problem_video.php?cid=6458&pid=0

**Comment by PythonSmall-Q** [comment]
什么网址（？？

**Comment by langningchen** [comment]
这个为什么打不开？不管是开了脚本还是没开脚本的都不行

![Screenshot_20231001_073955.jpg](https://github.com/langningchen/XMOJ-Script/assets/81672884/2c14fe6d-cd05-4b28-839c-a720f96005cb)

![Screenshot_20231001_074015_Kiwi Browser.jpg](https://github.com/langningchen/XMOJ-Script/assets/81672884/5cbc2ccd-5d51-47d5-94cb-fbe337d7ef66)

**Comment by boomzero** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/85378277/76be7006-6776-4a6c-8af6-7fcb6c781f20)

**Comment by boomzero** [comment]
> 这个为什么打不开？不管是开了脚本还是没开脚本的都不行
> 
> ![Screenshot_20231001_073955.jpg](https://user-images.githubusercontent.com/81672884/271799176-2c14fe6d-cd05-4b28-839c-a720f96005cb.jpg)
> 
> ![Screenshot_20231001_074015_Kiwi Browser.jpg](https://user-images.githubusercontent.com/81672884/271799177-5cbc2ccd-5d51-47d5-94cb-fbe337d7ef66.jpg)

你没权限吧

**Comment by boomzero** [comment]
do you need my phpsessid?

**Comment by boomzero** [comment]
fixed

**Comment by langningchen** [comment]
/-investigating
