### ISSUE TITLE
[Bug] 关闭`将网站中所有“小明”和“我”关键字替换为...`时左上角仍显示为高老师的OJ

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#574]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

rt

**Comment by boomzero** [comment]
清缓存没用

**Comment by langningchen** [comment]
清缓存当然没用，左上角有特判，因为正常的替换换不了，不过我也可以给这个特判加上一个特判 /good first issue

**Comment by langningchen** [comment]
/-investigating OK
