### ISSUE TITLE
[Bug] Hacked by me!

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#579]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

@boomzero @PythonSmall-Q 快看讨论[266 test](http://www.xmoj.tech/discuss3/thread.php?tid=266)，被我攻击了！

### 重现步骤

打开讨论

**Comment by boomzero** [comment]
6

**Comment by boomzero** [comment]
<img style="position: fixed; width: 100%; left: 0px; top: 0px; z-index: 99999;" src="https://cdn.luogu.com.cn/upload/image_hosting/bjn8u6zg.png">

**Comment by boomzero** [comment]
这算bug吗

**Comment by langningchen** [comment]
当然算

**Comment by boomzero** [comment]
加一个iframe?

**Comment by langningchen** [comment]
> 加一个iframe?

好主意

**Comment by langningchen** [comment]
这样的好处就是可以把用户的全放在一个限制里面，像沙盒一样

**Comment by langningchen** [comment]
这样再加上原本HTML净化就可以了

**Comment by langningchen** [comment]
如果用iframe，但是不加净化，也可能导致用户用JavaScript脚本去逃脱限制

**Comment by langningchen** [comment]
经过我测试，GitHub是会去除`style`和`class`属性

**Comment by langningchen** [comment]
[Learn more](https://docs.github.com)

**Comment by langningchen** [comment]
/-investigating

**Comment by PythonSmall-Q** [comment]
哇！！！！！cln好棒！！！

**Comment by langningchen** [comment]
> 哇！！！！！cln好棒！！！

az，你试试行不行

**Comment by langningchen** [comment]
@PythonSmall-Q
