### ISSUE TITLE
[Feature Request] 学术模式

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#582]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

开启学术模式后，自动关闭获取数据，~~不显示灌水版~~

**Comment by PythonSmall-Q** [comment]
此功能默认开启

**Comment by PythonSmall-Q** [comment]
具体视觉设计中

**Comment by PythonSmall-Q** [comment]
原因参见 https://github.com/langningchen/XMOJ-Script/pull/581/commits/a57ca6a040a532ffbe2e74576456ec1f3af754ef#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 的L51

**Comment by langningchen** [comment]
不是，你直接把讨论功能关了不就行了吗？ ~我不想再给1.0添加麻烦了 ~ /wontfix

**Comment by PythonSmall-Q** [comment]
我写

**Comment by PythonSmall-Q** [comment]
close和reopen那么多次的原因：![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/36057735-34bc-4830-a1b8-a56e2b922d21)

**Comment by langningchen** [comment]
？

**Comment by PythonSmall-Q** [comment]
艹不显示灌水版做不出来

**Comment by langningchen** [comment]
加油吧
