### ISSUE TITLE
[Enhancement] 关于增加用户协议的建议

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#59]
对于一个完整的程序，建议增加用户协议。可以参考这个：
https://github.com/PythonSmall-Q/CDN/blob/main/%E7%94%A8%E6%88%B7%E5%8D%8F%E8%AE%AE.md
仅为建议，不喜勿喷

**Comment by PythonSmall-Q** [comment]
最近都是大晚上开Issue实在抱歉我在新疆happy所以上线比较晚（特指次日凌晨）

**Comment by boomzero** [comment]
...

**Comment by boomzero** [comment]
http://www.xmoj.tech/discuss3/thread.php?tid=229

**Comment by boomzero** [comment]
@langningchen

**Comment by langningchen** [comment]
好的，我看看

**Comment by langningchen** [comment]
@PythonSmall-Q 你别忘记看你的autolog仓库！

**Comment by langningchen** [comment]
> 对于一个完整的程序，建议增加用户协议。可以参考这个： https://github.com/PythonSmall-Q/CDN/blob/main/%E7%94%A8%E6%88%B7%E5%8D%8F%E8%AE%AE.md 仅为建议，不喜勿喷

@PythonSmall-Q 我要改哪里？

**Comment by langningchen** [comment]
也就是你改了哪些部分？

**Comment by langningchen** [comment]
已经加上了
