### ISSUE TITLE
题号不能为负数且是不是搜索框太小了？

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#6]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/282a115a-76ce-4fa8-aafc-46112498e541)

**Comment by langningchen** [comment]
Will fix in 0.1.31

**Comment by PythonSmall-Q** [comment]
qp

**Comment by langningchen** [comment]
Fixed in 0.1.31, please wait for release. Thanks.
