### ISSUE TITLE
[Feature request] Add username color in the discussion section

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#60]
![](https://github.com/langningchen/XMOJ-Script/assets/85378277/da8a4660-9d6e-4134-9c86-a685d673a387)

**Comment by boomzero** [comment]
@langningchen #61

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/462942e0-225b-4f9a-929b-3a5be9b33e7b)
行吗？

**Comment by langningchen** [comment]
就这样了

**Comment by boomzero** [comment]
@langningchen 你忘记加讨论内部的color了, 这个我加了

**Comment by langningchen** [comment]
你还更新了次版本号……

**Comment by langningchen** [comment]
OK，我又改了一下
