### ISSUE TITLE
[Bug] 无法从网站上安装

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#63]
Cloudflare 的 feature, 如果是js file 的话他会执行这个file, 而不是展示raw

**Comment by boomzero** [comment]
所以, 安装链接不对

**Comment by boomzero** [comment]
@langningchen 你配置一下cloudflare pages,我这边删了, 因为只有repo owner才能connect repo

**Comment by langningchen** [comment]
好吧

**Comment by langningchen** [comment]
这个具体怎么弄？

**Comment by langningchen** [comment]
@boomzero

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/c708ccf0-a45b-40b3-82a3-87f1b13db235)
这个嘛？

**Comment by langningchen** [comment]
还有那个video-playback是什么？

**Comment by langningchen** [comment]
https://xmoj-script-web.pages.dev/ 这个应该行了

**Comment by langningchen** [comment]
https://web.xmoj-bbs.tech 这个应该也行了

**Comment by langningchen** [comment]
当仓库更新的时候 Cloudflare 会自动同步更新页面对吗？

**Comment by langningchen** [comment]
好了，结束

**Comment by boomzero** [comment]
> 还有那个video-playback是什么？

是我写的 #41 fix

**Comment by langningchen** [comment]
> 是我写的 41 fix

@boomzero 那我就删了
