### ISSUE TITLE
[Feature Request] 增加置顶功能

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#66]

**Comment by langningchen** [comment]
# ~~挺麻烦，也没必要，不干了！~~

**Comment by boomzero** [comment]
@langningchen 能把announcements表DROP 吗

**Comment by boomzero** [comment]
![drop](https://github.com/langningchen/XMOJ-Script/assets/85378277/87cb0690-b214-48f0-a5bd-5a1060f8af63)
done

**Comment by langningchen** [comment]
thx

**Comment by langningchen** [comment]
?

**Comment by boomzero** [comment]
@langningchen http://www.xmoj.tech/discuss3/thread.php?tid=234

**Comment by langningchen** [comment]
额，好吧 @boomzero

**Comment by boomzero** [comment]
@PythonSmall-Q

**Comment by langningchen** [comment]
~他肯定随便说说的，在我看来，他根本不可能Fix~

**Comment by boomzero** [comment]
> ~他肯定随便说说的，在我看来，他根本不可能Fix~

az, 6
