### ISSUE TITLE
[Feature Request] 讨论区markdown 支持内嵌html

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#68]
官方md spec支持内嵌html, see https://github.github.com/gfm/#raw-html

## 关于安全性

see https://github.github.com/gfm/#disallowed-raw-html-extension-

**Comment by langningchen** [comment]
知道了

**Comment by langningchen** [comment]
标题写着“GitHub Flavored Markdown Spec”呢

**Comment by langningchen** [comment]
尽管有些标签不能用HTML毕竟还有风险，并且要把现有的数据刷新，所以比较麻烦，不弄了

**Comment by langningchen** [comment]
正好也因为我想要抓紧时间把`v0.2.59`更新掉

**Comment by boomzero** [comment]
@langningchen 官方 spec: https://daringfireball.net/projects/markdown/syntax#html

**Comment by boomzero** [comment]
不需要, 反正以前也没人发html

**Comment by boomzero** [comment]
> 尽管有些标签不能用HTML毕竟还有风险，并且要把现有的数据刷新，所以比较麻烦，不弄了

Github 用户比xmoj-script多吧, 他也没出什么问题啊

**Comment by boomzero** [comment]
https://spec.commonmark.org/0.30/
https://spec.commonmark.org/0.30/#why-is-a-spec-needed-
https://spec.commonmark.org/0.30/#html-blocks

**Comment by langningchen** [comment]
> Github 用户比xmoj-script多吧, 他也没出什么问题啊

Github是公司，攻击他是要付法律责任的，我们不是公司，只是自动弄着玩一玩的，所以攻击了他不负责任

**Comment by langningchen** [comment]
要么你来解决吧，这个有点麻烦

**Comment by boomzero** [comment]
> > Github 用户比xmoj-script多吧, 他也没出什么问题啊
> 
> Github是公司，攻击他是要付法律责任的，我们不是公司，只是自动弄着玩一玩的，所以攻击了他不负责任

要是这样搞有bug的话早就report了, ~因为可以[骗钱](https://bounty.github.com/)~

**Comment by boomzero** [comment]
建议成立 Github 团队

**Comment by boomzero** [comment]
Milestone 就算了

**Comment by boomzero** [comment]
> > Github 用户比xmoj-script多吧, 他也没出什么问题啊
> 
> Github是公司，攻击他是要付法律责任的，我们不是公司，只是自动弄着玩一玩的，所以攻击了他不负责任

没事, ~去https://www.ic3.gov/举报他~

**Comment by boomzero** [comment]
> > > Github 用户比xmoj-script多吧, 他也没出什么问题啊
> > 
> > 
> > Github是公司，攻击他是要付法律责任的，我们不是公司，只是自动弄着玩一玩的，所以攻击了他不负责任
> 
> 没事, ~去https://www.ic3.gov/ 举报他~

```
Q: Can I file a complaint if I have been victimized by an individual or company in the United States, but I am not a citizen of the United States?

    Yes, if either you or the alleged subject of the Internet crime is located within the United States, regardless of citizenship, you may file a complaint with the IC3. 
```

**Comment by boomzero** [comment]
~快去举报我们封掉的ip~

**Comment by langningchen** [comment]
不用了吧

**Comment by langningchen** [comment]
那这个Issue就Close了

**Comment by langningchen** [comment]
来了！能修了！

**Comment by langningchen** [comment]
和 #363 一起

**Comment by boomzero** [comment]
Great!

**Comment by langningchen** [comment]
啊，我不小心删了两个数据表

**Comment by langningchen** [comment]
不过现在加回来了，删掉的是两个 mention ，数据丢了不太重要
