### ISSUE TITLE
[Feature Request] Debug mode 使用dev 分支

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#69]
可以在UI里加一个开debug mode的选项吗

**Comment by langningchen** [comment]
具体怎么说？

**Comment by langningchen** [comment]
开了DebugMode干什么？

**Comment by langningchen** [comment]
哦，知道了

**Comment by langningchen** [comment]
不是，你的DebugMode到底是干什么的？我怎么忘了我昨天怎么想的了 @boomzero

**Comment by langningchen** [comment]
因为长时间未回复，所以取消Milestone

**Comment by boomzero** [comment]
> 因为长时间未回复，所以取消Milestone

Sorry for the delay,I just traveled to Anhui Provence

**Comment by langningchen** [comment]
怎么用Dev分支，用它干什么？

**Comment by langningchen** [comment]
是使用Dev更新还是后台数据库使用Dev的？

**Comment by boomzero** [comment]
> 是使用Dev更新还是后台数据库使用Dev的？

使用Dev更新

~Dev有独立数据库吗~

**Comment by langningchen** [comment]
> Dev有独立数据库吗

本来想建立，后来觉得太麻烦

**Comment by PythonSmall-Q** [comment]
@langningchen 怎么使用dev版本。我想试试

**Comment by langningchen** [comment]
如果你想Dev版本，直接切换到Dev分支拷贝对应的脚本就行了

**Comment by langningchen** [comment]
@PythonSmall-Q 自动使用dev分支的功能我还没有做好

**Comment by PythonSmall-Q** [comment]
okay

**Comment by PythonSmall-Q** [comment]
所以现在是加上UserScript-DebugMode为true就可以了对吧

**Comment by PythonSmall-Q** [comment]
@langningchen

**Comment by langningchen** [comment]
好像还不行 @PythonSmall-Q

**Comment by langningchen** [comment]
毕竟我干活儿比较慢，最近又在忙着那个 `CI/CD` 的事情，那个 `Github Actions` 真的太难搞了

**Comment by PythonSmall-Q** [comment]
我手动更新了

**Comment by langningchen** [comment]
欸，我Close干嘛

**Comment by langningchen** [comment]
哇，我的 Prerelease CI/CD 竟然给我发布了！

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/c05e12fa-4079-4b93-a794-2c7af1e00571)

**Comment by langningchen** [comment]
Dev 基本上弄好了
