### ISSUE TITLE
建议更换github源

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#7]
https://ghproxy.com 网站部分不稳定。建议切换https://githubdown1.eu.org/或https://githubdown2.eu.org/或https://ghdownproxy.eu.org/

**Comment by PythonSmall-Q** [comment]
已为js关闭人机验证

**Comment by langningchen** [comment]
Please pay me for advertising

**Comment by langningchen** [comment]
:joy:

**Comment by PythonSmall-Q** [comment]
these are all free websites charging no fees with 1000000tokens a day

**Comment by PythonSmall-Q** [comment]
I have no objections even if this suggestion is refused

**Comment by langningchen** [comment]
But I think it's stable.
