### ISSUE TITLE
[Feature request] Remove Support for Safari

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#70]
Safari 上 Userscript 必须遵守CSP, 因此本脚本不能正常运行

**Comment by boomzero** [comment]
Content Security Policy

**Comment by langningchen** [comment]
参考 https://github.com/XIU2/UserScript/issues/107

**Comment by boomzero** [comment]
@langningchen 所以要Remove Support for Safari 啊, 为什么Close

**Comment by langningchen** [comment]
哦，你是这个意思啊

**Comment by boomzero** [comment]
done

**Comment by langningchen** [comment]
那你也应该给一个说明吧

**Comment by langningchen** [comment]
@boomzero 我认为你应该把 https://github.com/XIU2/UserScript/issues/107 在里面解释一下

**Comment by langningchen** [comment]
我认为你不应该去除支持，而是应该给出解决办法（尽管有点麻烦）

**Comment by boomzero** [comment]
> 我认为你不应该去除支持，而是应该给出解决办法（尽管有点麻烦）

是什么啊

**Comment by boomzero** [comment]
我就用https://github.com/quoid/userscripts, 不行

**Comment by boomzero** [comment]
有一个问题, 原来教程中允许远程自动化是干什么的, 那个不是用来开Safari的Selenium driver的吗

**Comment by boomzero** [comment]
~我绝对没有试图用Selenium攻击xmoj-bbs~

**Comment by langningchen** [comment]
好吧，那么就不支持

**Comment by langningchen** [comment]
不过我写一个说明

**Comment by langningchen** [comment]
写好了

**Comment by boomzero** [comment]
@langningchen 反正Safari装tampermonkey要付钱... 应该没人会装

**Comment by langningchen** [comment]
就这样吧，该都改了
