### ISSUE TITLE
[Bug] 申请数据按钮无效

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#73]
- 申请数据按钮无效
- ~复制要数据语句的功能可以删了~ done

**Comment by langningchen** [comment]
复制要数据语句的功能可以删了：为什么？

**Comment by langningchen** [comment]
申请数据按钮无效：这是什么东西？

**Comment by langningchen** [comment]
> 复制要数据语句的功能可以删了：为什么？

我自己最近都在用呢QWQ

**Comment by langningchen** [comment]
@boomzero

**Comment by boomzero** [comment]
> > 复制要数据语句的功能可以删了：为什么？
> 
> 我自己最近都在用呢QWQ

能在提交页面直接申请数据了, 为什么还需要去找高老师要

**Comment by langningchen** [comment]
是吗？

**Comment by langningchen** [comment]
我看看

**Comment by langningchen** [comment]
哦，我才发现

**Comment by langningchen** [comment]
好的，那就删了

**Comment by langningchen** [comment]
正好有道题，我试试这个功能，顺便Debug一下

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/180f2dc8-cef2-4e5a-96ed-9fee698d1c94)

**Comment by langningchen** [comment]
应该修好了

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/5f9d003d-3dbb-4645-80d4-cac8638b87dc)

**Comment by langningchen** [comment]
@boomzero 顺便问一下，那个Admin给我的短消息是你发的对吗

**Comment by langningchen** [comment]
我已经push到Dev分支了

**Comment by boomzero** [comment]
> @boomzero 顺便问一下，那个Admin给我的短消息是你发的对吗

是的...
