### ISSUE TITLE
[Feature Request] Encrypt Short messages

### ISSUE THREAD

**Issue by boomzero** [langningchen/XMOJ-Script#76]
rt, ~我发现我可以看到所有人的短消息~

**Comment by langningchen** [comment]
确实，我也可以

**Comment by langningchen** [comment]
@boomzero 你想要怎么加密？

**Comment by boomzero** [comment]
> @boomzero 你想要怎么加密？

~base64~

**Comment by langningchen** [comment]
...

**Comment by langningchen** [comment]
Reject

**Comment by langningchen** [comment]
要么就用AES-128 CBC吧，但是密钥是多少呢？

**Comment by boomzero** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/encrypt

**Comment by langningchen** [comment]
怎么确定密钥是一个问题

**Comment by langningchen** [comment]
你给的链接是RSA

**Comment by boomzero** [comment]
~PHPSESSID~

**Comment by langningchen** [comment]
对的，你给的链接是有AES CBC的

**Comment by boomzero** [comment]
> 你给的链接是RSA

可以aes啊

**Comment by langningchen** [comment]
> ~PHPSESSID~

怎么可能呢？

**Comment by boomzero** [comment]
服务器生成, 传给Client

**Comment by langningchen** [comment]
具体怎么实现你说清楚一点，我现在在忙着 #65 ，没太有时间一句一句问 😆

**Comment by boomzero** [comment]
我写吧

**Comment by langningchen** [comment]
好吧，注意别格式化了！

**Comment by boomzero** [comment]
密钥设为用户密码行吗

**Comment by langningchen** [comment]
哪个用户的密码？

**Comment by langningchen** [comment]
是发送的还是接受的？

**Comment by boomzero** [comment]
发消息的?

**Comment by langningchen** [comment]
还有就是你解决Issue的时候创建一个Branch，不要在Dev上面改

**Comment by langningchen** [comment]
那收消息的人怎么解密？

**Comment by boomzero** [comment]
...

**Comment by boomzero** [comment]
问题是不然服务器必须存密码

**Comment by langningchen** [comment]
确实

**Comment by langningchen** [comment]
所以不行

**Comment by langningchen** [comment]
那么就等于没加密，因为你又能知道是谁发的，又能看到他的密码，所以你想看到他发的内容这不是还可以吗？

**Comment by boomzero** [comment]
gpg?

**Comment by boomzero** [comment]
我看一下

**Comment by langningchen** [comment]
你好好想想吧

**Comment by boomzero** [comment]
找到了: https://github.com/porridgewithraisins/e2ee.js/

**Comment by boomzero** [comment]
这样服务器要存publickey

**Comment by langningchen** [comment]
我看了一下，这个不就是对称加密算法吗？

**Comment by langningchen** [comment]
这个就是AES

**Comment by boomzero** [comment]
...

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/dc5b994b-9430-4cfb-ad82-0827af3b3ceb)
你看Tag

**Comment by boomzero** [comment]
但是可以的啊

**Comment by langningchen** [comment]
但是你直接用CrpytoJS不行吗？

**Comment by boomzero** [comment]
> 但是你直接用CrpytoJS不行吗？

对的, 但是我还没想好如果服务器没有用户的publickey怎么办

**Comment by langningchen** [comment]
用户上传不就好了嘛

**Comment by boomzero** [comment]
> 用户上传不就好了嘛

接收方

**Comment by langningchen** [comment]
服务器下发不就好了吗？

**Comment by boomzero** [comment]
> 服务器下发不就好了吗？

但是服务器只有10ms cpu time

**Comment by boomzero** [comment]
够吗

**Comment by langningchen** [comment]
应该够吧

**Comment by boomzero** [comment]
> 应该够吧

有点危险

**Comment by langningchen** [comment]
试试

**Comment by langningchen** [comment]
@boomzero 怎么样？干完了没？

**Comment by boomzero** [comment]
> @boomzero 怎么样？干完了没？

~没写...~

**Comment by langningchen** [comment]
加油，你来写这个吧

**Comment by langningchen** [comment]
@boomzero 你是不是在后台看到了 @PythonSmall-Q 给我发的短消息才想到要加密的？

**Comment by langningchen** [comment]
《论 @PythonSmall-Q 的人格分裂》

**Comment by PythonSmall-Q** [comment]
艹是不是看到了我的那个aya so cute 了

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/c0e83ff3-c1a6-4736-b7f1-02b1bdc7a34e)

**Comment by langningchen** [comment]
LOL

**Comment by langningchen** [comment]
> 艹是不是看到了我的那个aya so cute 了

当然

**Comment by boomzero** [comment]
![](https://github.com/langningchen/XMOJ-Script/assets/85378277/35cfcf7d-2de2-455c-89b9-e06d3f1c47f8)

**Comment by boomzero** [comment]
我先写 #93

**Comment by langningchen** [comment]
可以

**Comment by langningchen** [comment]
我今天一会儿就不在线了，下午才能上线

**Comment by boomzero** [comment]
> 我今天一会儿就不在线了，下午才能上线

+1

**Comment by PythonSmall-Q** [comment]
> ![](https://user-images.githubusercontent.com/85378277/263502390-35cfcf7d-2de2-455c-89b9-e06d3f1c47f8.jpg)

艹真没必要放出来

**Comment by langningchen** [comment]
@PythonSmall-Q 我删了

**Comment by PythonSmall-Q** [comment]
我看看主流加密方式提点小建议吧

**Comment by PythonSmall-Q** [comment]
（搜题解那个我看看有没有什么替代方案

**Comment by langningchen** [comment]
> （搜题解那个我看看有没有什么替代方案

什么搜题？

**Comment by PythonSmall-Q** [comment]
https://www.zhihu.com/question/61332622#:~:text=%E9%80%82%E5%90%88%E5%A4%9A%E6%96%B9%E9%80%9A%E8%AE%AF%EF%BC%88%E4%BE%8B%E5%A6%82%E7%BE%A4%E8%81%8A%EF%BC%89%E7%9A%84%E5%8A%A0%E5%AF%86%E4%BD%93%E5%88%B6%E6%9C%89%E5%93%AA%E4%BA%9B%EF%BC%9F,%E7%8E%B0%E6%9C%89%E7%9A%84%E5%AF%86%E7%A0%81%E4%BD%93%E5%88%B6%EF%BC%88RSA%E3%80%81AES%E7%AD%89%EF%BC%89%E9%83%BD%E6%98%AF%E9%92%88%E5%AF%B9%E5%8F%8C%E6%96%B9%E9%80%9A%E4%BF%A1%E7%9A%84%E5%9C%BA%E6%99%AF%EF%BC%9B%20%E5%AF%B9%E4%BA%8E%E4%B8%89%E4%BA%BA%E5%8F%8A%E4%B8%89%E4%BA%BA%E4%BB%A5%E4%B8%8A%E7%9A%84%E5%A4%9A%E4%BA%BA%E9%80%9A%E4%BF%A1%E7%9A%84%E6%83%85%E6%99%AF%E4%B8%8B%EF%BC%8C%E8%A6%81%E4%BF%9D%E8%AF%81%E6%B6%88%E6%81%AF%E7%9A%84%E6%9C%BA%E5%AF%86%E6%80%A7%E4%B8%94%E4%B8%AD%E7%BB%A7%E8%8A%82%E7%82%B9%E4%B9%9F%E6%97%A0%E6%B3%95%E7%9C%8B%E5%88%B0%E6%B6%88%E6%81%AF%EF%BC%8C%E6%9C%89%E4%BB%80%E4%B9%88%E5%A5%BD%E2%80%A6
@langningchen

**Comment by PythonSmall-Q** [comment]
Encrypt可以参考这个

**Comment by langningchen** [comment]
我看看

**Comment by PythonSmall-Q** [comment]
https://github.com/langningchen/XMOJ-Script/issues/205#issuecomment-1698524550
看这个

**Comment by PythonSmall-Q** [comment]
可以用Base64的加密解密api（我在做2020CSP-S想到了

**Comment by langningchen** [comment]
> 可以用Base64的加密解密api（我在做2020CSP-S想到了

@PythonSmall-Q Base64是编码，而不是加密，并且还是那个问题，密钥怎么定 @PythonSmall-Q

**Comment by boomzero** [comment]
> > 可以用Base64的加密解密api（我在做2020CSP-S想到了
> 
> @PythonSmall-Q Base64是编码，而不是加密，并且还是那个问题，密钥怎么定 @PythonSmall-Q

End to end encryption应该很难做, 所以微信也没有

**Comment by boomzero** [comment]
> > > 可以用Base64的加密解密api（我在做2020CSP-S想到了
> > 
> > 
> > @PythonSmall-Q Base64是编码，而不是加密，并且还是那个问题，密钥怎么定 @PythonSmall-Q
> 
> End to end encryption应该很难做, 所以微信也没有

~不过微信没有的原因可能是那样就没办法过滤你的消息~

**Comment by PythonSmall-Q** [comment]
是的。密钥那就CSPGOODLUCK吧（doge

Sent from Mail for Windows

**Comment by PythonSmall-Q** [comment]
嘿嘿邮箱reply真方便爱了爱了

Sent from Mail for Windows

**Comment by boomzero** [comment]
为什么iCloud 邮件不让我发, 一直access denied

**Comment by boomzero** [comment]
> 是的。密钥那就CSPGOODLUCK吧（doge 

那不就等于没加密?

**Comment by PythonSmall-Q** [comment]
其实我也不了解加密算法。（我是蒟蒻

Sent from Mail for Windows

**Comment by boomzero** [comment]
> 其实我也不了解加密算法。（我是蒟蒻 Sent from Mail for Windows From: Zhu Chenrui Sent: 2023年9月15日 19:28:19 To: langningchen/XMOJ-Script Cc: Shan Wenxiao; Mention Subject: Re: [langningchen/XMOJ-Script] [Feature Request] Encrypt Shortmessages (Issue #76) 可以用Base64的加密解密api（我在做2020CSP-S想到了 @PythonSmall-Q Base64是编码，而不是加密，并且还是那个问题，密钥怎么定 @PythonSmall-Q End to end encryption应该很难做, 所以微信也没有 不过微信没有的原因可能是那样就没办法过滤你的消息 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

~为什么有这么多metadata~

**Comment by boomzero** [comment]
> 其实我也不了解加密算法。（我是蒟蒻 Sent from Mail for Windows From: Zhu Chenrui Sent: 2023年9月15日 19:28:19 To: langningchen/XMOJ-Script Cc: Shan Wenxiao; Mention Subject: Re: [langningchen/XMOJ-Script] [Feature Request] Encrypt Shortmessages (Issue #76) 可以用Base64的加密解密api（我在做2020CSP-S想到了 @PythonSmall-Q Base64是编码，而不是加密，并且还是那个问题，密钥怎么定 @PythonSmall-Q End to end encryption应该很难做, 所以微信也没有 不过微信没有的原因可能是那样就没办法过滤你的消息 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

+1

**Comment by boomzero** [comment]
但密钥不能固定

**Comment by PythonSmall-Q** [comment]
您们加油

Sent from Mail for Windows

**Comment by langningchen** [comment]
@PythonSmall-Q 您根本不会为什么要重开Issue……？
