### ISSUE TITLE
[BUG] 时间错误：Invalid Date

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#81]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/73615bdf-f119-42c0-a677-7fc688456eb1)

**Comment by boomzero** [comment]
#48 ?

还有posttime设成now影响吗

**Comment by langningchen** [comment]
好了
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/5b5f2759-21d1-426a-92fa-206f56d0b503)
