### ISSUE TITLE
[Feature Request] 增加头像

### ISSUE THREAD

**Issue by langningchen** [langningchen/XMOJ-Script#93]
使用公开头像服务增加头像

**Comment by boomzero** [comment]
https://en.gravatar.com/ ?

**Comment by boomzero** [comment]
Can that be accessed in china?

**Comment by boomzero** [comment]
> Can that be accessed in china?

the api, not the website

**Comment by boomzero** [comment]
哦, 有http://cn.gravatar.com/

**Comment by boomzero** [comment]
> 哦, 有http://cn.gravatar.com/

这个也打不开...

**Comment by boomzero** [comment]
但是有国内镜像

**Comment by boomzero** [comment]
问题是设置头像要到官网上设

**Comment by boomzero** [comment]
或者, 可以让用户把头像穿到洛谷图床上, 然后提供链接

**Comment by boomzero** [comment]
@langningchen

**Comment by langningchen** [comment]
不是，有gravator的国内替代品的，而且Cloudflare也可以弄一个CDN

**Comment by boomzero** [comment]
> 不是，有gravator的国内替代品的

What?

**Comment by boomzero** [comment]
https://www.libravatar.org/ 可以的,中国能开

**Comment by boomzero** [comment]
test:
![](https://cdn.libravatar.org/gravatarproxy/61906123e3434a379372364f31670311?s=80)

**Comment by boomzero** [comment]
Can you see the picture?

**Comment by boomzero** [comment]
其实有几个选项:
![df](https://github.com/langningchen/XMOJ-Script/assets/85378277/9f3212d6-e358-4847-8899-56907c31da2e)

**Comment by boomzero** [comment]
@langningchen 可以吗

**Comment by boomzero** [comment]
需要用户Email

**Comment by langningchen** [comment]
可以的

**Comment by langningchen** [comment]
Email从用户那里获取就行了

**Comment by langningchen** [comment]
如果用户没有填写Email，则弹出对话框要求在发布讨论前填写

**Comment by langningchen** [comment]
并且要加上邮箱验证码验证

**Comment by boomzero** [comment]
> 并且要加上邮箱验证码验证

How do you do this? Firebase?

**Comment by boomzero** [comment]
我可以在我的服务器上装postfix, 但是不太好写intergration代码

**Comment by langningchen** [comment]
> How do you do this? Firebase?

自己写SMTP啊

**Comment by langningchen** [comment]
用Libcurl写

**Comment by langningchen** [comment]
哦，JS好像没有libcurl

**Comment by langningchen** [comment]
我有一个PHP版的，可以参考

**Comment by langningchen** [comment]
似乎好像有： https://www.npmjs.com/package/node-libcurl

**Comment by boomzero** [comment]
Firebase 不行吗

**Comment by langningchen** [comment]
也可以，不过我喜欢造轮子

**Comment by boomzero** [comment]
> 也可以，不过我喜欢造轮子

...

**Comment by langningchen** [comment]
没事，你来吧，我把自己的Assignment去掉了

**Comment by langningchen** [comment]
怎么又方便又省资源就怎么干

**Comment by PythonSmall-Q** [comment]
cravatar.cn

**Comment by PythonSmall-Q** [comment]
这个能上

**Comment by langningchen** [comment]
对的，我本来就想用这个，但是好像不太方便

**Comment by langningchen** [comment]
@boomzero 你在做这个吗？

**Comment by boomzero** [comment]
我在写作业...

**Comment by boomzero** [comment]
这样吧, 服务器存一下email的MD5, 那样直接fetch即可

**Comment by boomzero** [comment]
@langningchen 头像加在哪好啊

**Comment by boomzero** [comment]
@langningchen https://github.com/langningchen/XMOJ-Script/tree/avatar

**Comment by langningchen** [comment]
在bootstrap官方库的文档里面写了Toast模块是原生态支持放头像的

**Comment by langningchen** [comment]
另外，在个人主页和姓名显示前面也可以显示头@boomzero

**Comment by langningchen** [comment]
> 这样吧, 服务器存一下email的MD5, 那样直接fetch即可

你这个应该可以用kv存，应该不用d1

**Comment by langningchen** [comment]
你用什么服务？用cravatar还是cdn的gravatar？

**Comment by boomzero** [comment]
> > 这样吧, 服务器存一下email的MD5, 那样直接fetch即可
> 
> 你这个应该可以用kv存，应该不用d1

写好了...

**Comment by boomzero** [comment]
> 你用什么服务？用cravatar还是cdn的gravatar？



> https://www.libravatar.org/ 可以的,中国能开

**Comment by langningchen** [comment]
好吧

**Comment by langningchen** [comment]
别忘了Email验证

**Comment by boomzero** [comment]
> 别忘了Email验证

会写的

**Comment by langningchen** [comment]
https://www.libravatar.org/avatar/cf61d8b9b26fcfbae97951931ca01f8d?s=80&default=retro

**Comment by langningchen** [comment]
我记得原来有一个服务好像也能检测如果系统里面没有头像会自动获取其他社交媒体上的头像的

**Comment by boomzero** [comment]
> 我记得原来有一个服务好像也能检测如果系统里面没有头像会自动获取其他社交媒体上的头像的

这个可以获取gravatar上的头像

**Comment by boomzero** [comment]
> https://www.libravatar.org/avatar/cf61d8b9b26fcfbae97951931ca01f8d?s=80&default=retro
> 
> ![](https://camo.githubusercontent.com/5db5779967964f5f92f72c3ce449b996fcd60d26e337a087cc7b97ddce920bf1/68747470733a2f2f7777772e6c6962726176617461722e6f72672f6176617461722f63663631643862396232366663666261653937393531393331636130316638643f733d38302664656661756c743d726574726f)

luogu默认头像多好啊

**Comment by boomzero** [comment]
https://www.libravatar.org/avatar/cf61d8b9b26fcfbae97951931ca01f8d?s=80&default=retro

![](https://www.libravatar.org/avatar/cf61d8b9b26fcfbae97951931ca01f8d?s=80&default=retro)

https://www.libravatar.org/avatar/cf61d8b9b26fcfbae97951931ca01f8d?s=80&default=pagan

![](https://www.libravatar.org/avatar/cf61d8b9b26fcfbae97951931ca01f8d?s=80&default=pagan)


https://www.libravatar.org/avatar/cf61d8b9b26fcfbae97951931ca01f8d?s=80&default=monsterid

![](https://www.libravatar.org/avatar/cf61d8b9b26fcfbae97951931ca01f8d?s=80&default=monsterid)

https://www.libravatar.org/avatar/cf61d8b9b26fcfbae97951931ca01f8d?s=80&default=identicon

![](https://www.libravatar.org/avatar/cf61d8b9b26fcfbae97951931ca01f8d?s=80&default=identicon)
https://www.libravatar.org/avatar/cf61d8b9b26fcfbae97951931ca01f8d?s=80&default=robohash

![](https://www.libravatar.org/avatar/cf61d8b9b26fcfbae97951931ca01f8d?s=80&default=robohash)

**Comment by PythonSmall-Q** [comment]
https://www.libravatar.org/avatar/cf61d8b9b26fcfbae97951931ca01f8d?s=80&default=retro
这个看上去不错

**Comment by boomzero** [comment]
> https://www.libravatar.org/avatar/cf61d8b9b26fcfbae97951931ca01f8d?s=80&default=retro 这个看上去不错

thx

**Comment by boomzero** [comment]
@langningchen What do you think?

**Comment by boomzero** [comment]
@langningchen 后台写好了, 就差验证邮箱了

**Comment by boomzero** [comment]
firebase!

**Comment by boomzero** [comment]
`npm install firebase`等了10分钟还没好...

**Comment by boomzero** [comment]
> `npm install firebase`等了10分钟还没好...

还没好...

**Comment by langningchen** [comment]
你firebase好了对吧？

**Comment by langningchen** [comment]
这就是我未来的头像了：
![](https://www.libravatar.org/avatar/cf61d8b9b26fcfbae97951931ca01f8d?s=80&default=retro)

就用retro挺好的

**Comment by boomzero** [comment]
> 你firebase好了对吧？

对的, 开了vpn就好了...

**Comment by boomzero** [comment]
@langningchen 可以不邮箱验证吗

**Comment by boomzero** [comment]
毕竟填别人的邮箱也没什么好处

**Comment by boomzero** [comment]
主要是写起来太麻烦了

**Comment by langningchen** [comment]
...... 好吧，我有空加，你可以先不加

**Comment by PythonSmall-Q** [comment]
我的头像用github的就可以了

**Comment by PythonSmall-Q** [comment]
我在想要不就建一个repo，上传头像直接upload到github

**Comment by PythonSmall-Q** [comment]
@langningchen @boomzero

**Comment by PythonSmall-Q** [comment]
具体实现我不确定行不行

**Comment by langningchen** [comment]
你只要把你的PAT给我应该就行

**Comment by PythonSmall-Q** [comment]
啥PAT？

**Comment by langningchen** [comment]
Github Person Acess Token

**Comment by boomzero** [comment]
> 我在想要不就建一个repo，上传头像直接upload到github

不行吧, 据我所知js应该没有git?

**Comment by boomzero** [comment]
哦, 可以api

**Comment by boomzero** [comment]
> 哦, 可以api

不太行, 没有这个api

**Comment by langningchen** [comment]
有上传的API的 @boomzero

**Comment by boomzero** [comment]
> 有上传的API的 @boomzero

什么啊, commit吗

**Comment by langningchen** [comment]
我忘了，但是我原来用这个做过一个自制网盘 @boomzero

**Comment by langningchen** [comment]
@boomzero 我想到一个问题

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/e1bc7260-1919-4b43-bd27-4da1480c19e4)
为什么服务器要存他们的邮箱？

**Comment by langningchen** [comment]
@PythonSmall-Q 你也来看看

**Comment by langningchen** [comment]
头像加不了了……Crvatar崩了！

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/ec30c80a-853e-4cf0-bc45-5d12fc47e57b)

**Comment by PythonSmall-Q** [comment]
我看看

**Comment by PythonSmall-Q** [comment]
https://cravatar.cn/developer/api
https://cravatar.com/developer/creating-the-hash
@langningchen

**Comment by langningchen** [comment]
@PythonSmall-Q 现在好了，刚才是崩了

**Comment by langningchen** [comment]
同样的网址： https://cravatar.cn/avatar/cf61d8b9b26fcfbae97951931ca01f8d 现在就行了

![](https://cravatar.cn/avatar/cf61d8b9b26fcfbae97951931ca01f8d)

**Comment by langningchen** [comment]
@PythonSmall-Q 就是你，到你这里就崩溃

**Comment by PythonSmall-Q** [comment]
（？

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/893e8c9a-6359-4318-a1d3-c4a156c23ebb)

**Comment by PythonSmall-Q** [comment]
我咋了（？

**Comment by langningchen** [comment]
不知道，就是每次到你这里EmailHash获取就崩溃

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/e0edd2f7-bb96-4ba0-8ee4-a5bb3db1bc97)

**Comment by PythonSmall-Q** [comment]
……我设置头像了呀？

**Comment by PythonSmall-Q** [comment]
你md5结果发我我看看

**Comment by langningchen** [comment]
不是，我说的是获取用户Email的时候

**Comment by langningchen** [comment]
不是获取头像的时候

**Comment by PythonSmall-Q** [comment]
艹我看看email

**Comment by langningchen** [comment]
不是你的问题

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/f42f81da-9845-4013-a814-7be822975947)
有的

**Comment by langningchen** [comment]
别人都是这个元素：

```js
let EmailHash = CryptoJS.MD5(ParsedDocument.querySelector("#statics > tbody > tr:nth-child(16) > td:nth-child(2)").innerText.trim()).toString();
```

而你的是这个元素：

```js
let EmailHash = CryptoJS.MD5(ParsedDocument.querySelector("#statics > tbody > tr:nth-child(17) > td:nth-child(2)").innerText.trim()).toString();
```

不知道为什么不一样？哪里多了一个元素

**Comment by PythonSmall-Q** [comment]
我有atcoder账户啥的

**Comment by langningchen** [comment]
我试试

**Comment by langningchen** [comment]
@PythonSmall-Q 

我加了一句：
```js
if (Username == "shanwenxiao")
    debugger
```

**Comment by langningchen** [comment]
找到原因了

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/f29bc1fc-7e65-4e75-aedf-f7814aab653e)

一对比就知道了

**Comment by langningchen** [comment]
不过名字颜色炸了

**Comment by PythonSmall-Q** [comment]
《错误原因过多，导致匹配失常》

**Comment by langningchen** [comment]
？

**Comment by PythonSmall-Q** [comment]
我多了“格式错误”

**Comment by langningchen** [comment]
确实

**Comment by langningchen** [comment]
为什么颜色没了是因为我忘写了一个双引号

**Comment by PythonSmall-Q** [comment]
az

**Comment by langningchen** [comment]
这下真的好了

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/f5490fb7-b85b-482e-954b-d54d3b253c3c)

**Comment by PythonSmall-Q** [comment]
哇！快发布dev版本

**Comment by PythonSmall-Q** [comment]
你确认其他像我这样的都好了么？

**Comment by langningchen** [comment]
空的是没有填邮箱的

**Comment by langningchen** [comment]
填了邮箱没有设置头像的就是随即头像

**Comment by PythonSmall-Q** [comment]
emm但是他好像出来的默认

**Comment by langningchen** [comment]
我现在用的还是 gravatar 以为刚才 cravatar 炸了

**Comment by langningchen** [comment]
123 是默认头像，没有填邮箱
4 是用户自定义头像，填了邮箱，设置了头像
567 是随机头像，填了邮箱，没设置头像

**Comment by PythonSmall-Q** [comment]
嗯不错。但是中国上不去gravatar欸

**Comment by langningchen** [comment]
我还没换

**Comment by langningchen** [comment]
我先测试一下讨论界面能不能正常显示

**Comment by PythonSmall-Q** [comment]
嗯嗯

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/9693a434-40dc-48e9-bd34-e9bdcb515e23)

就是位置有点……

**Comment by PythonSmall-Q** [comment]
作者这里就不要了吧

**Comment by PythonSmall-Q** [comment]
短消息我觉得也有点碍眼

**Comment by langningchen** [comment]
要么把最后回复的人删掉，之六时间

**Comment by PythonSmall-Q** [comment]
也可以

**Comment by PythonSmall-Q** [comment]
> > 短消息我觉得也有点碍眼
> 
> 为什么？
你看吧

**Comment by langningchen** [comment]
删功能真简单，加功能真难！

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/f89edaa3-fe81-4173-9d5e-e61e58b1f99e)

**Comment by langningchen** [comment]
> 你看吧

我觉得还好

**Comment by langningchen** [comment]
要么最后回复使用相对时间？

**Comment by langningchen** [comment]
这样能更短一点

**Comment by PythonSmall-Q** [comment]
x分钟前？

**Comment by langningchen** [comment]
对的

**Comment by langningchen** [comment]
行吗？

**Comment by PythonSmall-Q** [comment]
我举双手双脚支持

**Comment by langningchen** [comment]
鼠标悬停再显示具体时间

**Comment by PythonSmall-Q** [comment]
可以捏

**Comment by langningchen** [comment]
但是评分炸了

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/037fff42-6b6a-4aa0-8112-4a89e811beb4)

**Comment by PythonSmall-Q** [comment]
……开发大大加油！！！

**Comment by langningchen** [comment]
原因是因为：
正确：
```js
UserInfo.innerHTML += "&emsp;评分：" + ((await GetUserInfo(UserID)).Rating);
```

错误：
```js
UserInfo.innerHTML += "&emsp;评分：" + (await GetUserInfo(UserID).Rating);
```

**Comment by langningchen** [comment]
忘了运算优先级，没加括号……

**Comment by PythonSmall-Q** [comment]
6

**Comment by langningchen** [comment]
这不就好了吗？

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/c81c66fa-e452-4a3a-bc10-5ad16c986916)

**Comment by langningchen** [comment]
开始研究个人主页加大头像的事情

**Comment by PythonSmall-Q** [comment]
有接口的好像是&size=***来着的我忘了

**Comment by langningchen** [comment]
对的

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/cbccb6cb-a268-49bd-b50c-474551dcba68)

加上了，但还没有改样式

**Comment by PythonSmall-Q** [comment]
这样是不是有点突兀（？

**Comment by langningchen** [comment]
你觉得放哪里好看呢？

**Comment by PythonSmall-Q** [comment]
第一列头像下面第一行名字，第二行昵称，第三行rating
第二列第三列原本顺义

**Comment by langningchen** [comment]
瞬移？

**Comment by langningchen** [comment]
可以

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/846f55d9-456e-4754-ab8b-791aab976557)

就是你的昵称太长了，所以换行了

**Comment by langningchen** [comment]
@PythonSmall-Q 这样应该更好一点

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/8bab37a8-fab5-42b7-8fe5-b6871141ca29)

**Comment by langningchen** [comment]
我再改改

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/ab3d987a-6493-4be8-af07-ce4cbbc6e660)
改成了这样，就是不知道为什么上面那些有点长

**Comment by langningchen** [comment]
中间有一块空白

**Comment by langningchen** [comment]
@PythonSmall-Q 就这样行吗？

![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/51d52f1f-4032-4f15-a00e-67c84101be8f)

**Comment by PythonSmall-Q** [comment]
加油！

**Comment by PythonSmall-Q** [comment]
特别好看qaq

**Comment by PythonSmall-Q** [comment]
我觉得这样挺好的！！！！

**Comment by langningchen** [comment]
刚才把文本居中了一下

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/ffea6a05-c7cf-44de-9a22-2cbf8bd0e304)

**Comment by PythonSmall-Q** [comment]
挺好看的欸

**Comment by langningchen** [comment]
这样头像和右面的文字就可以在一起了，前面那张图感觉有点错开

**Comment by langningchen** [comment]
下面就是准备在个人中心界面增加编辑头像的链接和说明

**Comment by PythonSmall-Q** [comment]
嗯挺好的（要不这个版本提前发布试试吧！

**Comment by langningchen** [comment]
https://github.com/langningchen/XMOJ-Script/pull/123

**Comment by PythonSmall-Q** [comment]
咋啦？

**Comment by langningchen** [comment]
估计自动发布会出锅

**Comment by langningchen** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/81672884/f716f7b5-f10a-4c95-83d1-7c347735b796)
你看我说吧

**Comment by PythonSmall-Q** [comment]
hh

**Comment by langningchen** [comment]
这样再试试

**Comment by langningchen** [comment]
可以了

**Comment by langningchen** [comment]
问题是好像发布发出去了，但是Cloudflare没更新

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/8ebfb314-cfe5-4246-93e0-990226d3145f)
Gravatar？？？

**Comment by PythonSmall-Q** [comment]
你确定这玩意儿国内能上（？？

**Comment by langningchen** [comment]
忘改了

**Comment by PythonSmall-Q** [comment]
我帮你做一个镜像吧

**Comment by langningchen** [comment]
不用

**Comment by langningchen** [comment]
不然到时候他们改头像也要到你的镜像上面改

**Comment by PythonSmall-Q** [comment]
cloudflare workers了解一下

**Comment by langningchen** [comment]
> cloudflare workers了解一下

？

**Comment by langningchen** [comment]
我现在在想怎么用 Github Actions 触发 Cloudflare Pages 的更新

**Comment by langningchen** [comment]
https://github.com/marketplace/actions/cloudflare-pages-github-action

**Comment by PythonSmall-Q** [comment]
做好了证书再传播了

**Comment by langningchen** [comment]
嗯

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/13897aa3-b99f-4e9a-b383-411d2ca7673e)
来了

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/39ede3d0-426a-4ad3-a093-3e2ce61e1dfe)
活了大概今天晚上就能用了。之前不小心没关重定向

**Comment by langningchen** [comment]
我已经用了cravatar，我估计那些xxs看不懂这么复杂的英文

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/1a2ff103-4c53-4ba1-955c-9e9eb60ff286)
好了

**Comment by langningchen** [comment]
嗯

**Comment by PythonSmall-Q** [comment]
cravatar不稳定哦！如果可以试试看写如果cravatar连不上链接镜像

**Comment by PythonSmall-Q** [comment]
地址之前图片里有
